### ISSUE TITLE
Unable to deploy ink contract with chain extension. (ExtrinsicFailed: Other) 

### ISSUE THREAD

**Issue by frankli-dev** [paritytech/ink#1001]
```
use crate::{errors::Error, models::AssetId};
use ink_env::Environment;
use ink_lang as ink;

/// Define the operations to interact with the substrate runtime
#[ink::chain_extension]
pub trait CurrencyExtension {
    type ErrorCode = Error;

    #[ink(extension = 2, returns_result = false)]
    fn test();
}

impl ink_env::chain_extension::FromStatusCode for Error {
    fn from_status_code(status_code: u32) -> Result<(), Self> {
        match status_code {
            0 => Ok(()),
            1 => Err(Self::TransferFailed),
            _ => panic!("encountered unknown status code"),
        }
    }
}

// #[derive(Debug, Clone, PartialEq, Eq)]
// #[cfg_attr(feature = "std", derive(scale_info::TypeInfo))]
pub enum CustomEnvironment {}

impl Environment for CustomEnvironment {
    const MAX_EVENT_TOPICS: usize = <ink_env::DefaultEnvironment as Environment>::MAX_EVENT_TOPICS;

    type AccountId = <ink_env::DefaultEnvironment as Environment>::AccountId;
    type Balance = <ink_env::DefaultEnvironment as Environment>::Balance;
    type Hash = <ink_env::DefaultEnvironment as Environment>::Hash;
    type BlockNumber = <ink_env::DefaultEnvironment as Environment>::BlockNumber;
    type Timestamp = <ink_env::DefaultEnvironment as Environment>::Timestamp;
    type RentFraction = <ink_env::DefaultEnvironment as Environment>::RentFraction;

    type ChainExtension = CurrencyExtension;
}

```

I have the following code in the ink! contract to call the extension function
```
self.env().extension().test()?;
```
But when I deploy the ink contract, it fails with the following error

![image](https://user-images.githubusercontent.com/51565705/140003941-6f44fd24-546e-40f6-9809-ccd64e17ac3f.png)

![image](https://user-images.githubusercontent.com/51565705/140004109-b3d9cf43-3756-4237-a6f5-fa9672dcbc29.png)

However, if I comment the extension calling part, it deploys successfully

```
// self.env().extension().test()?;
```

I'm not sure why this chain extension calling part affects to deployment. It is not included in the construct function.

Please help me
Thanks in advance

**Comment by frankli-dev** [comment]
Any help please?

**Comment by cmichi** [comment]
@frankli-dev I think this is likely an issue with the runtime side. Is there a chance you could point us to the corresponding runtime code?

**Comment by frankli-dev** [comment]
@cmichi sure
https://github.com/Polkadex-Substrate/Polkadex/blob/develop/runtime/src/lib.rs

**Comment by cmichi** [comment]
@frankli-dev The first thing I noticed is that it's still `type ChainExtension = ();` in there, but should be `CustomChainExtension` (probably `impl_uniswap::CustomChainExtension`).

**Comment by cmichi** [comment]
@frankli-dev Another thing which you should check is that the contract code above has
```
    #[ink(extension = 2, returns_result = false)]
    fn test();
```
But the runtime has only an extension for `0` and `1`.

**Comment by frankli-dev** [comment]
@cmichi sorry, it is mismatched code. I will share you the correct branch

**Comment by frankli-dev** [comment]
@cmichi nice you are right, `type ChainExtension = ();` was wrong. It works now.
