### ISSUE TITLE
Remove old github page site

### ISSUE THREAD

**Issue by NukeManDan** [paritytech/ink#1013]
https://paritytech.github.io/ink/ is live, and I think it should be removed, just needs an admin to remove pages in settings for the repo. Might delete the gh-pages branch too :) 

https://github.com/paritytech/ink/tree/gh-pages

Unless I am wrong, as CI is still pushing here :thinking: - but shoudn't everyone be directed to https://paritytech.github.io/ink-docs/ ?

**Comment by cmichi** [comment]
Hi there Dan,

the [Developer Documentation](https://github.com/paritytech/ink#developer-documentation) is published to the `gh-pages` branch, so all the Rust-generated documentation for the ink! crates (e.g. https://paritytech.github.io/ink/ink_env/).

We have the landing page https://paritytech.github.io/ink/ there to provide some guidance and link to the crate docs.
