### ISSUE TITLE
Why is "Hash" and "Moment" unsupported?

### ISSUE THREAD

**Issue by usd-yamazaki** [paritytech/ink#102]
If you use "Hash" or "Moment" as an argument of the function of "pub (external)", the following error will occur.
`error: Moment is unsupported as message interface type`

https://github.com/paritytech/ink/blob/fa906cadbb5679ff7017c01ac9a68a21c426c4bb/lang/src/api.rs#L278-L299

**Comment by Robbepop** [comment]
Thank you for the bug report.
We are currently working on a more general solution to the underlying problem.
A bug fix for this particular bug will be pushed soon.

**Comment by Robbepop** [comment]
Fixed by https://github.com/paritytech/ink/commit/88729e748d5f7cb13783e0af7942f7ccab4144ba.
