### ISSUE TITLE
Upstream function merging into rust mainline

### ISSUE THREAD

**Issue by athei** [paritytech/ink#1021]
Function merging is a potentially code size saving LLVM optimization pass. The inclusion of the optimization pass is done by some external researcher.

Things to do:
- Monitor [progress of the inclusion into LLVM mainline](https://reviews.llvm.org/D111912). If it gets stuck we should check whether there is anything how we can support the author.
- Once it is in LLVM mainline make sure that the optimization can be enabled in `rustc`. Probably by mainlining a patch to rustc.

This issue is resolved once we can use this optimization in a vanilla rust nightly version.

**Comment by jamesblacklock** [comment]
This page tracks the progress of Function Merging (aka HyFM) into mainline LLVM: [https://reviews.llvm.org/D111912](https://reviews.llvm.org/D111912)
