### ISSUE TITLE
Upstream function outlining into rust mainline

### ISSUE THREAD

**Issue by athei** [paritytech/ink#1022]
Function outlining is a potentially code size saving LLVM optimization pass. It is already included as an optimization pass in LLVM but it is architecture specific. It is not implemented for the wasm backend we are interested in. Michael and James did work on the wasm implementation of this optimization.

Things to do:
- Finish up the wasm implementation.
- Upstream the optimization to LLVM.
- Once it is in LLVM mainline make sure that the optimization can be enabled in rustc. Probably by mainlining a patch to rustc.

This issue is resolved once we can use this optimization in a vanilla rust nightly version.

**Comment by jamesblacklock** [comment]
This patch was tested on C code (by Michael; I did not test this) and presumably worked on C code. I integrated the patch into Rust and the compiler builds just fine, but I get crashes when trying to compile contracts. I have spent a couple weeks trying to diagnose this (and one other) optimization pass without success. I am putting this on hold for now to work on higher priorities (unless, of course, I am informed that this should be the highest priority).
