### ISSUE TITLE
Make constructors (non)payable

### ISSUE THREAD

**Issue by athei** [paritytech/ink#1027]
When https://github.com/paritytech/substrate/pull/10082 is merged there is no longer a need to pass an endowment larger than `0` except when the contract logic itself requires it. This makes `endowment` no different from `value` in a call extrinsic.

Therefore I think we should extend the `payable` logic to constructors. The UI can then remove the endowment field for non payable constructors.

**Comment by Robbepop** [comment]
Can you elaborate on this a bit?
So will it be possible to have `value` _and_ `endownment` fields upon contract instantiation?
Currently in ink! all constructors are implicitly payable since unpayable constructors make no sense since the contract would be evicted immediately after.

**Comment by athei** [comment]
> So will it be possible to have value and endownment fields upon contract instantiation?

No, there is still only `endowment`.

> Currently in ink! all constructors are implicitly payable since unpayable constructors make no sense since the contract would be evicted immediately after.

And this is exactly the part that is about to change soon. Unpayable constructors make sense then.

**Comment by Robbepop** [comment]
So should we non-confusingly rename this to "Allow ink! constructors to be non-payable" ?

**Comment by athei** [comment]
Sure, if that makes more sense to you. The issue is about allowing this `payable` attribute there which is now set by default.

**Comment by athei** [comment]
Needs to be done before the stable release because it is a breaking change.
