### ISSUE TITLE
Two core examples are outdated

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink#103]
```
cd examples/core/incrementer/
CARGO_INCREMENTAL=0 cargo build --release --target=wasm32-unknown-unknown --verbose
...
error[E0603]: type alias `ContractEnv` is private
  --> src/lib.rs:29:9
   |                                                                           
29 |         ContractEnv,
   |         ^^^^^^^^^^^  
```
Same for `examples/core/subpeep`.

I talked to @Robbepop and `ContractEnv` should not be used directly, instead the Env API from `core/src/env/api.rs` should be used.

**Comment by Robbepop** [comment]
Since `ink_lang` is our main layer we think it is best to completely remove all example codes that are not targeting the `lang` layer but the Erc20 token examples. Also we need serious clean-ups there besides the mentioned point.
Also consider this issue: https://github.com/paritytech/ink/issues/88
