### ISSUE TITLE
Extract ink_core/env into its own crate

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#106]
As far as I see there are no dependencies from within `ink_core/env` into other parts of `ink_core` and with the incoming `ink_abi` it could make sense to factor out this portion of `ink_core` into its own crate so that other ink! sub-crates can depend on it in isolation without needing the whole of `ink_core`.

I propose for the name of the new ink! sub-crate to be either `ink_sys` or `ink_env`.

**Comment by ascjones** [comment]
> As far as I see there are no dependencies from within ink_core/env into other parts of ink_core

The `EnvStorage` trait depends on `memory::vec::Vec` and `storage::Key` https://github.com/paritytech/ink/blob/master/core/src/env/traits.rs#L77

**Comment by Robbepop** [comment]
This could be resolved by simply putting both into `ink_utils` where they could properly live. The internals of `storage::Key` are already there.

**Comment by ascjones** [comment]
Yeah, and I just noticed #110 which would solve `memory::vec::Vec`

**Comment by Robbepop** [comment]
`storage::Key` is a minor problem. Let's see where we could put it.

**Comment by Robbepop** [comment]
This issue has the huge problem of having parts of `ink_core::env/2` depend on parts of `ink_core::storage`. So if we were to split `ink_core::env/2` into its own crate and cross-link from `ink_core` to `ink_env` we would end up with a cyclic dependency.

**Comment by Robbepop** [comment]
This has been implemented in https://github.com/paritytech/ink/pull/500. Closed.
