### ISSUE TITLE
what's the difference between trait_definition and trait

### ISSUE THREAD

**Issue by DashYang** [paritytech/ink#1060]
see example below

```
#[ink::trait_definition]
pub trait BaseErc20 {
    /// Creates a new ERC-20 contract and initializes it with the initial supply for the instantiator.
    #[ink(constructor)]
    fn new(initial_supply: Balance) -> Self;

    /// Returns the total supply.
    #[ink(message)]
    fn total_supply(&self) -> Balance;

    /// Transfers `amount` from caller to `to`.
    #[ink(message, payable)]
    fn transfer(&mut self, to: AccountId, amount: Balance);
}
```

```
use ink_lang as ink;

#[ink::contract]
mod erc20 {
    use base_erc20::BaseErc20;

    #[ink(storage)]
    pub struct Erc20 {
        total_supply: Balance,
        // more fields ...
    }

    impl BaseErc20 for Erc20 {
        #[ink(constructor)]
        fn new(initial_supply: Balance) -> Self {
            // implementation ...
        }

        #[ink(message)]
        fn total_supply(&self) -> Balance {
            // implementation ...
        }

        #[ink(message, payable)]
        fn transfer(&mut self, to: AccountId, amount: Balance) {
            // implementation ...
        }
    }
}
```
I can't see the difference between `trait BaseErc20` and `#[ink::trait_definition]`, why ink！ need such annotation?

**Comment by HCastano** [comment]
Hi @DashYang! Sorry for taking so long to get back to you.

The `#[ink::trait_definition]` is a [procedural macro](https://doc.rust-lang.org/reference/procedural-macros.html) which allows ink! contracts to define traits which are implementable by other ink! contracts.

In short, the macro does a couple of things to achieve this. First, at compile time it checks that your trait definition meets some requirements (e.g no unsafe methods) needed by ink!. Second, it generates some extra code to communicate to the trait implementer how to properly implement this trait.

If you're curious about some of this you can use [`cargo-expand`](https://github.com/dtolnay/cargo-expand) to see how the expanded trait definition differs from the "declared" one.

**Comment by HCastano** [comment]
@DashYang I'm gonna go ahead and close this issue. Feel free to ping us/re-open this if you feel like it hasn't been resolved.
