### ISSUE TITLE
Remove `libsecp256k1` dependency of `ink_eth_compatibility`

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink#1068]
We need the `libsecp256k1` dependency only in the `to_eth_address` function, for getting the uncompressed 65-byte public key from the ECDSA public key.

Ways to remove the dep would be to either add a new API function in the `contracts` pallet, find another no-std compatible crate, or extract the functionality from either `libsecp256k1` or `secp256k1` into `ink_eth_compatibility`.

**Comment by cmichi** [comment]
@athei @agryaznov 

There is not yet an issue for this in `pallet-contracts`, but I think we should implement it there. This would enable us to get rid of the `libsecp256k1` dependency in ink!, thus making contracts using the `ink_eth_compatibility` smaller.

I can imagine having e.g. sth like a `seal_to_eth_address(ecdsa_compressed_public_key: [u8; 32])`.

That's the code which would need to be moved to this new `pallet-contracts` function: https://github.com/paritytech/ink/blob/master/crates/eth_compatibility/src/lib.rs#L99-L119.

**Comment by athei** [comment]
I think there should be some host function available for the runtime to offload that to. Search for that here: https://github.com/paritytech/substrate/blob/master/primitives/io/src/lib.rs

**Comment by agryaznov** [comment]
> I think there should be some host function available for the runtime to offload that to. Search for that here: https://github.com/paritytech/substrate/blob/master/primitives/io/src/lib.rs

Haven't found appropriate function there, will move current impl dependent on `libsecp256k` into pallet.

**Comment by agryaznov** [comment]
We now have `seal_` function for this in pallet_contract. Do we need to implement also some fn to be used from inside ink! contracts? @cmichi

**Comment by athei** [comment]
Of course. Your linked PR should not just remove the dependency but replace it with a call of the seal function.

**Comment by agryaznov** [comment]
Do we really need this `ink_eth_compatibility` crate after all? It isn't being used anywhere, and only has one more fn aside from `to_eth_address()`, which is `to_default_account_id()` and looks like something that should be put out of ink as well (probably to the same ecdsa trait extension in frame_support).

**Comment by athei** [comment]
Yeah I don't think we need this extra crate anymore. I think we only had it to avoid pulling in the crypto dependency. But better wait for @cmichi to comment.
