### ISSUE TITLE
CR: DNS contract example: add `get_owner()` message

### ISSUE THREAD

**Issue by agryaznov** [paritytech/ink#1084]
As domain name is a tradable property, it probably worth making its current ownership verification possible through a message invocation.  

This issue is a proposal to add a `get_owner()` message to the DNS contract example, just like it is done for address mapping getter with [`get_address()`](https://github.com/paritytech/ink/blob/ce37cadecc923bb13f86a3f2b1713f3378bccfa5/examples/dns/lib.rs#L155)

**Comment by HCastano** [comment]
Closed via #1118
