### ISSUE TITLE
How to call ink! contract though js SDK or cli?

### ISSUE THREAD

**Issue by AdaLam7** [paritytech/ink#1088]
I can't found any documents about it

**Comment by HCastano** [comment]
Hi there! For a CLI, this is still a WIP, see https://github.com/paritytech/cargo-contract/pull/79 for more details. As for the JS side @statictype or @achimcc can give you a better answer than I can

**Comment by achimcc** [comment]
Hello! Did you check the Polkadot JS API docs? Especially: https://polkadot.js.org/docs/api-contract/start/contract.tx
