### ISSUE TITLE
How to transfer token from caller to contract?

### ISSUE THREAD

**Issue by AdaLam7** [paritytech/ink#1089]
The contract-transfer example,` give me ` transfer token to the caller, but how to let the caller transfer token to the contract account?

like:
```
self.env().caller().transfer(self.env.account_id, value)
```

**Comment by xgreenx** [comment]
You can't force caller to transfer some native tokens to you in the contract scope. The caller should transfer them to the contract during the calling of the methods of that contract(outside of the contract).

But if you want to transfer `PSP22` tokens(`Erc20` analog), then you can call the [`transfer_from`](https://github.com/w3f/PSPs/blob/master/PSPs/psp-22.md#transfer_fromfrom-accountid-to-accountid-value-balance-data-u8--result-psp22error) method.

**Comment by AdaLam7** [comment]
So how can I use ink! to create a Refinancing contract?

1. Caller transfer native token to contract, but how? Same as transfer to a normal account?
2. How does the contract know who transfers token to the contract, how to save the caller account id?

It would be perfect if you can provide a refinancing contract example.

**Comment by xgreenx** [comment]
1. Yes, during the calling of the method of the contract you can pass the amount what you want to send.
<img width="891" alt="image" src="https://user-images.githubusercontent.com/18346821/147405763-0df970eb-5095-4352-96cd-2a4453ea3f18.png">

2. Example of simple Crowdfunding:
```rust
#![cfg_attr(not(feature = "std"), no_std)]

#[ink_lang::contract]
pub mod crowdfunding {
    use ink_storage::{
        lazy::Mapping,
        traits::SpreadAllocate,
    };

    #[ink(storage)]
    #[derive(Default, SpreadAllocate)]
    pub struct Crowdfunding {
        deposits: Mapping<AccountId, Balance>,
    }

    impl Crowdfunding {
        #[ink(constructor)]
        pub fn new() -> Self {
            Self::default()
        }

        #[ink(message)]
        pub fn balance_of(&self, account: AccountId) -> Balance {
            self.deposits.get(&account).unwrap_or_default()
        }

        // The method should be mark `payable` to be able to receive a native token
        #[ink(message, payable)]
        pub fn deposit(&mut self) {
            let caller = self.env().caller();
            let deposited = self.env().transferred_value();

            let mut balance = self.deposits.get(&caller).unwrap_or_default();
            balance += deposited;
            self.deposits.insert(&caller, &balance);
        }

        #[ink(message)]
        pub fn withdraw(&mut self, amount: Balance) {
            let caller = self.env().caller();
            let mut balance = self.deposits.get(&caller).unwrap_or_default();
            assert!(balance >= amount, "Not enough balance");

            assert!(self.env().transfer(caller, amount).is_ok());
            balance -= amount;
            self.deposits.insert(&caller, &balance);
        }
    }
}
```

**Comment by AdaLam7** [comment]
Awesome example~ Recommended to put it in the code example.

**Comment by AdaLam7** [comment]
@xgreenx  by the way  what is test UI in your comment?

**Comment by xgreenx** [comment]
> @xgreenx by the way what is test UI in your comment?

It is [polkadot.js](https://polkadot.js.org/apps/).
