### ISSUE TITLE
Instantiation failed (`contracts.CodeRejected`) after using `serde_json`.

### ISSUE THREAD

**Issue by czyczk** [paritytech/ink#1106]
**Questions**

- Is this a bug concerning building of ink! smart contracts?
No. Testing and compilation are OK.

**Versions**

Rust Nightly:  `cargo 1.60.0-nightly (95bb3c92b 2022-01-18)`  
cargo-contract: `cargo-contract 0.17.0-unknown-x86_64-linux-gnu`
substrate-contract-node: `substrate-contracts-node 0.5.0-0ec18d9-x86_64-linux-gnu`
ink!: `3.0.0-rc8`

**Describe the bug**
I previously have an ink contract without JSON serialization and deserialization logic. It was deployed all well even with the old (`3.0.0-rc7`) ink deps. Now for some reason, I want to receive a JSON string as the parameter and parse it in the contract function. I did so by first adding the deps.

```
[dependencies]
<- snip ->
serde = { version = "^1.0", default-features = false, features = ["derive"] }
serde_json = { version = "^1.0.75", default-features = false, features = ["alloc"] }
<- snip ->

[features]
<- snip ->
    "serde/std",
    "serde_json/std",
<- snip ->
```

And had some `serde_json::from_str()` calls in the contract function, and some `serde_json::to_string()` calls in the testing function.
The testing and compilation are OK, but I can't get it deployed now.

I tried to instantiate it with Polkadot JS API and got this error (not original, enriched with some module error meta).
```
"explainedModuleError": {
    "index": "0x08",
    "error": "0x1b",
    "type": "contracts.CodeRejected",
    "details": "The contract's code was found to be invalid during validation or instrumentation. A more detailed error can be found on the node console if debug messages are enabled or in the debug buffer which is returned to RPC clients."
}
```

(Actually I can only get the detailed message of the module error after I upgraded the `substrate-contracts-node` from `0.3.0` to `0.5.0`. The error was a null in the previous version.)

And here's the related debug message in the node console (`--log debug`). I can hardly see anything through it.
(Too long to be posted here. See attachment below)

**Expected behavior**
Deployment and instantiation should pass. JSON serialization and deserialization should work. Is it something wrong with the way deps are added or something special about JSON serde in ink's environment? Or is it an internal bug with such a contract?

**Attachment**
Debug level log: https://1drv.ms/u/s!Aj_rPvkyS8y8gvE9lOLc2kr1prZmyQ?e=SeCNzt
`metadata.json`: https://1drv.ms/u/s!Aj_rPvkyS8y8gvE8xYF51SaqUYQy0w?e=NNbh3p

**Comment by athei** [comment]
Are you sure you want to parse json in a smart contract? That is a way too heavy weight operation to be ever economical. And if you had to do that you wanted to use some dependency that is smaller than the monster that serde is. Consider using parity-scale-codec for your encoding needs.

> And here's the related debug message in the node console (--log debug). I can hardly see anything through it.
> (Too long to be posted here. See attachment below)
 Use  `-lerror,runtime::contracts=debug`  for debugging as explained in the `substrate-contracts-node` readme.

That said, your log message will only show up when you pre-run the instantiate or upload via RPC because only then a debug buffer is collected. The UI won't do that.

Can you upload the wasm file that is rejected here?

**Comment by czyczk** [comment]
Thanks. The debug message is
```
2022-01-25 17:07:00.005 DEBUG tokio-runtime-worker runtime::contracts: CodeRejected: use of floating point type in locals is forbidden
```

I'm not using floating types anywhere in the contract (because the version without JSON got passed in `rc-7`, but not `rc-8`, which just led to another issue #1112 ). So is this something introduced by `serde_json`?

WASM:

**Comment by athei** [comment]
Yeah I would assume that code is introduced by serde. As I said: Don't use serde in contracts. It doesn't make sense. It is way too big.

**Comment by czyczk** [comment]
OK, I'm now well aware of this constraint. Thank you!
