### ISSUE TITLE
Remove `collections` and `lazy` module code

### ISSUE THREAD

**Issue by HCastano** [paritytech/ink#1119]
In #1111 we hid the `collections` and `lazy` modules (for reasons explained in that PR).
Eventually we'll want to actually remove the code, but until we're ready to pull the
trigger we've decided to open this issue as a reminder instead.

**Comment by w-** [comment]
might be good to remove `lazy storage values` from the tutorial as well
https://docs.substrate.io/tutorials/v3/ink-workshop/pt2/

**Comment by HCastano** [comment]
@w- yep, did that in https://github.com/substrate-developer-hub/substrate-docs/pull/853

**Comment by HCastano** [comment]
Closed via #1271
