### ISSUE TITLE
Implement storage::Map::entry API

### ISSUE THREAD

**Issue by usd-yamazaki** [paritytech/ink#112]
In order to use HashMap more like Rust, please make Entry public and implement or_insert.

Link to Rust's `BTreeMap` `Entry` API: https://doc.rust-lang.org/std/collections/btree_map/enum.Entry.html

We really want this API for ergonomics and it should be possible to have all the lifetime-safety guarantees that Rust's API brings with it, even though we are operating on storage instead of memory.

**Comment by Robbepop** [comment]
Duplicate of https://github.com/paritytech/ink/issues/379.
