### ISSUE TITLE
Review user-facing ink! chain extensions example

### ISSUE THREAD

**Issue by justinFrevert** [paritytech/ink#1121]
This [repo](https://github.com/justinFrevert/Runtime-Contract-Interactions) contains non-production-ready user-facing examples of ink! chain extensions, and calls to contracts from the runtime. The original goal of this repo was to provide examples of communication both ways between runtime and ink! contracts in order to be the basis of some user-facing materials or documentation.

The ask here is for a review of this repo by the ink! and/or pallet-contracts team to be sure it is ready for users(ie checking for any patterns we wouldn't want users to repeat, using apis in a way that doesn't make sense, etc).

There's no expected format of review - so whatever format is easiest on the repo should be fine. New issue, a PR with comments, etc.

**Comment by HCastano** [comment]
I took a (late) look back in the day and it was pretty good!
