### ISSUE TITLE
Doc bug: Data Structures Overview page links 404

### ISSUE THREAD

**Issue by justinFrevert** [paritytech/ink#1128]
**Describe the bug**
Browsing the links at the [Data Structures Overview](https://paritytech.github.io/ink-docs/datastructures/overview) page results in 404s for links. The data structures links(`Vec`, `BinaryHeap`, `HashMap`, etc...) in particular are 404'd.
Example: https://paritytech.github.io/ink/ink_storage/collections/struct.HashMap.html.

It seems everything in `/ink/ink_storage/collections` and below is 404'd and possibly outdated. 

**Expected behavior**
These links would lead to some existing informative page, like docs or a github code link. I am honestly not sure where it should go, as the entire `collections` module in ink_storage seems to be gone and no longer applicable.

**Screenshots**
![image](https://user-images.githubusercontent.com/81839854/153260446-d8678af9-ca9c-4e9f-a00b-925ab15d245d.png)

**Additional context**
I would patch, but I am not sure where the links should go.

**Comment by HCastano** [comment]
Yep, this is because of https://github.com/paritytech/ink/pull/1111.

I'll take this on.

**Comment by HCastano** [comment]
Closed via https://github.com/paritytech/ink-docs/pull/44
