### ISSUE TITLE
Implementation of HashMap initialization when using eDSL

### ISSUE THREAD

**Issue by usd-yamazaki** [paritytech/ink#113]
If you store a structure in storage::HashMap, you can not use storage::HashMap as a child structure.
The following code will actually cause an error because storage::HashMap::new() does not exist.

```
#![cfg_attr(not(any(test, feature = "test-env")), no_std)]

use ink_core::{
    env::{
        self,
        AccountId,
        Balance,
        Hash,
    },
    storage,
};
use ink_lang::contract;
use parity_codec::{Encode, Decode};

contract! {
    struct Test {
        users: storage::HashMap<AccountId, User>,
    }

    impl Deploy for Test {
        fn deploy(&mut self) {
        }
    }

    impl Test {
        pub(external) fn add(&mut self) {
            let user = User {
                balance: 0,
                items: storage::HashMap::new(),
            };
            self.users.insert(env::caller(), user);
        }
    }
}

#[derive(Encode, Decode)]
struct User {
    balance: Balance,
    items: storage::HashMap<Hash, u128>,
}
```

**Comment by Robbepop** [comment]
What you are trying to achieve is dynamic allocation of storage types.
This is possible in ink!, however requires a different initialization scheme than you are used normally in Rust.

So for example this should work:

```rust
pub(external) fn add(&mut self) {
    let user = User {
        balance: 0,
        items: storage::HashMap::allocate_using(&mut env.dyn_alloc).initialize_into(()),
    };
    self.users.insert(env::caller(), user);
}
```

To be honest this is currently quite some ugly syntax for such a simple thing.
However, we already have some plans on how to make this simpler in the future.
Also please beware, that just yesterday we found a seriour bug in dynamicly allocated instances of storage types that we have to fix - but we are already on it. (@cmichi )

**Comment by usd-yamazaki** [comment]
I did not notice the existence of env.dyn_alloc.
Thank you!
