### ISSUE TITLE
Change AccountId and Hash fields to public

### ISSUE THREAD

**Issue by usd-yamazaki** [paritytech/ink#114]
Since you want to access the original data of AccountId and Hash, please change the field to public.

https://github.com/paritytech/ink/blob/fa906cadbb5679ff7017c01ac9a68a21c426c4bb/core/src/env/srml/types.rs#L41
`pub struct AccountId(pub [u8; 32]);`

https://github.com/paritytech/ink/blob/fa906cadbb5679ff7017c01ac9a68a21c426c4bb/core/src/env/srml/types.rs#L63
`pub struct Hash(pub [u8; 32]);`

**Comment by Robbepop** [comment]
We are going to change these fundamental types soon and then it will no longer technically be possible to do this. However, we might take your feedback into consideration and try to provide ways to mutate state.

**Comment by Robbepop** [comment]
Closed since the mentioned PR has been merged.
