### ISSUE TITLE
Add lang test to ensure example contracts compile

### ISSUE THREAD

**Issue by ascjones** [paritytech/ink#116]
Existing lang tests of examples just check that the resulting `TokenStream` is as expected, but not that they compile. So it's possible to generate code that will not compile, and the tests and CI will still pass

We should add at least one example that is compiled as part of the tests/CI to catch any breakages to code gen.

Could potentially use: https://github.com/dtolnay/trybuild.

**Comment by Robbepop** [comment]
It was never the purpose of the current `lang` tests to ensure correct compilation but they check for the correct resulting code generation which is also very handy to have.
Besides that you are right that we also (besides those tests) want plenty of `lang` tests that check for compilability.

**Comment by Robbepop** [comment]
Implemented in https://github.com/paritytech/ink/pull/191. Closed.
