### ISSUE TITLE
Implement `block_timestamp` for unit test engine

### ISSUE THREAD

**Issue by forgetso** [paritytech/ink#1164]
Our team is looking to use `block_timestamp` in our contract. Currently, if we use `self.env().block_timestamp();` in a function that is called by the unit test engine, it causes this error: 
```
panicked at ‘not implemented: off-chain environment does not yet support `block_timestamp`’
```
This means that we can't use `block_timestamp` without breaking most of our unit tests.

Are there any plans to implement this feature soon?

If we were to tackle it ourselves, is there any design guidance you can give on how to implement it?

**Comment by cmichi** [comment]
@forgetso The function has been implemented in the current `master`, we will issue the next release early next week, so you can use it then.

Note though that we've removed the old testing engine and replaced it with a new one, so you'll have to make some changes to your tests to account for the new testing engine (it was previously hidden by a feature flag `ink-experimental-engine`). We will have some more information on how to migrate to the new API in the release notes.

I'll close the issue for now, but don't hesitate to reopen if you encounter any issues after the next release!

**Comment by forgetso** [comment]
Great news, thanks for the update @cmichi !
