### ISSUE TITLE
wiki: Fix Linux installation instructions.

### ISSUE THREAD

**Issue by riusricardo** [paritytech/ink#118]
>**Update to keep standard installation methods in "Deploying Your First Contract"**

**Mac OS**:

```bash
brew install wabt
cargo install pwasm-utils-cli --bin wasm-prune
```

**Arch Linux**:

```bash
sudo pacman -Syu wabt
cargo install pwasm-utils-cli --bin wasm-prune
```

**Comment by Robbepop** [comment]
Maybe it is better to generalize the section.
Otherwise we would need to have a section or code snippet about all the available package managers and build systems.

**Comment by riusricardo** [comment]
Agree, but how can it be generalized? Will it contain installation instructions or it is better to remove them?
An alternative could be to redirect them to an installation link on substrate.dev -> [Setup](https://substrate.dev/substrate-contracts-workshop/#/0/setup)

The actual line `apt install wabt` for Linux is invalid so we only have two standard alternatives, Mac OS, Linux Arch.

Another option is the script that handles Mac OS, Arch Linux, Debian/Ubuntu Linux.
```
curl https://raw.githubusercontent.com/substrate-developer-hub/substrate-contracts-workshop/master/scripts/install-wasm-tools.sh -sSf |bash -s
```

**Comment by riusricardo** [comment]
@Robbepop The general problem is how to manage the Wasm Utilities installation process. How can it be generalized?

It needs to be handles without making a mess. For now the scripts that enables development on Debian-based distros is merged into the substrate-contracts-workshop repo. The same script can install the utilities for Mac OS, Arch Linux, Debian/Ubuntu Linux.

Is it good to keep it in that repo and just update the instructions on [Installing ink](https://substrate.dev/docs/en/contracts/installing-ink)? or it should be moved to substrate-developer-hub.github.io or parity/scripts and point to it from any installation instructions?

Maybe @shawntabrizi has an opinion on this.

**Comment by shawntabrizi** [comment]
@riusricardo it should move to parity/scripts if anywhere, but as I said before, I am not a big fan of these kinds of scripts, since users install them once, and then the scripts get updated, and then users don't get that update.

Piping it through curl could work, but I question the security around it.

I would prefer clear documentation for the majority audience

**Comment by riusricardo** [comment]
>@riusricardo it should move to parity/scripts if anywhere, but as I said before, I am not a big fan of these kinds of scripts, since users install them once, and then the scripts get updated, and then users don't get that update.

Ok, it is a very valid concern.

>Piping it through curl could work, but I question the security around it.

Understandable, but to be fair it is the same way on how substrate and Rust are installed.
I get it, as you previously said in the other issue, you're not a fan of this method. I also agree that it is not 100% secure but I don't see an easier way for now.

>I would prefer clear documentation for the majority audience

I do agree on this, but how can we handle it. The script could be stripped down and used only to install the 2 missing binaries. It will not do anything else, but the instruction will end up again being specified for  3 different cases.

**Mac OS**:

```bash
brew install wabt
cargo install pwasm-utils-cli --bin wasm-prune
```

**Arch Linux**:

```bash
sudo pacman -Syu wabt
cargo install pwasm-utils-cli --bin wasm-prune
```

**Ubuntu/Debian**:

```bash
curl https://raw.githubusercontent.com/paritytech/scripts/master/install-wasm-tools.sh -sSf |bash -s
cargo install pwasm-utils-cli --bin wasm-prune
```

**Comment by shawntabrizi** [comment]
Our new documentation platform supports tabs. I can try to use it so that it is only one section, but has multiple platfrom choices

**Comment by riusricardo** [comment]
Nice! Good idea, it will also keep it clean. The next thing to do is to clean the script and strip it to only download the 2 missing binaries and keep the installation instructions as close as possible on every OS.

**Comment by riusricardo** [comment]
Closing. Wiki points now to the correct documentation.
