### ISSUE TITLE
Unused `ast::FnDecl::inputs_with_env` method

### ISSUE THREAD

**Issue by ascjones** [paritytech/ink#119]
The build warns about the following method being unused: 
https://github.com/paritytech/ink/blob/debb49aa3e7cc111818f913c9c8273686483761b/lang/src/ast.rs#L266-L286

However it looks similar to the following code, which it might have been intended to replace:
https://github.com/paritytech/ink/blob/d803c2e2cb558fd79f1d4bee8cd5a3adb3f59977/lang/src/gen/build.rs#L338-L357

So we should either use the method in place of the above code, or remove it.

**Comment by Robbepop** [comment]
If you can use the one function within the body of the other, make it use, otherwise just remove it.
