### ISSUE TITLE
Unused `ast::ArgCaptured`

### ISSUE THREAD

**Issue by ascjones** [paritytech/ink#120]
Another build warning. Introduced in https://github.com/paritytech/ink/commit/4230474cac29aaf549a2c018cca693a39246a541, but not used anywhere.

Unless intended for use, can we remove this? @Robbepop

**Comment by Robbepop** [comment]
Can be removed, if we need it again we can just restore it from history.

**Comment by ascjones** [comment]
Actually it is used in `ast::FnDecl::inputs_with_env` which itself is unused (#119), hence the warning. So if we do end up using that then this will be required. Likewise if we remove it then this can be removed.
