### ISSUE TITLE
Better api for  `ContractEnv<EnvTypes>` 

### ISSUE THREAD

**Issue by ascjones** [paritytech/ink#125]
As part of #108, generic type parameters are added for the user's concrete implementation of `EnvTypes`.

However this makes calling some (previously generic free) methods ugly. In the PR I have added a type alias `env` which mimics the old api style of calling methods via the `ink_core::env` module. However the name does collide with that module and could also cause confusion because it looks like a module but is in fact a type alias.

Given that a follow up PR implementing `ext_dispatch_call` (#124) will influence what we decide here, I think it is best to make the changes in a separate PR, or part of that one.

Also we need to consider the API for tests: see https://github.com/paritytech/ink/pull/108/files#r295806347.

Also: https://github.com/paritytech/ink/pull/108/files#r295805144

**Comment by ascjones** [comment]
Resolved as part of #108

**Comment by ascjones** [comment]
Still some `env` ugliness to fix

**Comment by Robbepop** [comment]
Can this be closed? @ascjones

**Comment by ascjones** [comment]
I'd say so, yes.
