### ISSUE TITLE
`debug_print(ln)` fails for temporary values

### ISSUE THREAD

**Issue by xgreenx** [paritytech/ink#1261]
After https://github.com/paritytech/ink/pull/1258, the `debug_print(ln)!` macro fails for temporary variables if the "ink-debug" feature is disabled.

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/18346821/169108583-48cb487f-43c5-414d-bb6e-099142e24bda.png">

**Comment by athei** [comment]
I can't reproduce. Building this example with:
```
cargo +nightly contract build --release
```

This should disable this feature. The CI would have also caught this error. Can you give more instructions?

**Comment by xgreenx** [comment]
You need to remove "ink-debug" from `Cargo.toml`=)

**Comment by athei** [comment]
Ahh okay it shouldn't be there. I think it is a left over. Can reproduce it now.

**Comment by cmichi** [comment]
Looked into it. So the story with `ink-debug` is that if you execute `cargo contract build` the default behavior is that `cargo-contract` builds the contract with `--features=ink/ink-debug`. That's the reason why the `Cargo.toml` of the `contract-transfer` example doesn't need to contain any `ink-debug` feature anymore.

If you build the contract with `cargo contract build --release` the `debug_print` and `debug_println` macros won't output whatever was passed to them:

```rust
if #[cfg(any(feature = "ink-debug", feature = "std"))] {
    …
} else {
    #[macro_export]
    /// Debug messages disabled. Enable the `ink-debug` feature for contract debugging.
    macro_rules! debug_print {
        ($($arg:tt)*) => ();
    }

    #[macro_export]
    /// Debug messages disabled. Enable the `ink-debug` feature for contract debugging.
    macro_rules! debug_println {
        () => ();
        ($($arg:tt)*) => ();
    }
}
```
(from https://github.com/paritytech/ink/blob/master/crates/env/src/lib.rs).

Hence the bug can no longer occur.
