### ISSUE TITLE
ABI V4

### ISSUE THREAD

**Issue by athei** [paritytech/ink#1265]
We should group all changes to metadata into a single version to cause the least disruption.

- [x] #1207
- [x] #1134
- [x] #1289

**Comment by yjhmelody** [comment]
Please always consider that metadata format should make other languages to adapt it easier.

**Comment by HCastano** [comment]
Closing since the [`4.0.0-beta`](https://github.com/paritytech/ink/releases/tag/v4.0.0-beta) includes these metadata changes.
