### ISSUE TITLE
Restore ink! 3.x.x backward compatibility

### ISSUE THREAD

**Issue by agryaznov** [paritytech/ink#1278]
This issue describes the reasons of [this](https://substrate.stackexchange.com/questions/2870/cargo-contract-throws-error-about-supplied-arguments-in-inkconstructor-f) StackExchange reported problem with _ink!_ `v3.0.1` 

Cargo crate dependencies version specifications [rules](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio) work as follows:
`3.0.1 := >= 3.0.1 < 4.0.0`

This leads to that `3.2.0` is being the resolved version even when `=3.0.1` is specified in the contract manifest, for the following crates:
- `ink_allocator`
- `ink_engine`
- `ink_lang_codegen`
- `ink_lang_ir`
- `ink_prelude`
- `ink_storage_derive`

As a hotfix for this, I've [changed the dependencies](https://github.com/paritytech/ink/commit/0638f8208431ffb6c188170fe1132ad746dee1b1) to be specified as [tilde requirements](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#tilde-requirements). I suggest making release `v3.0.2` out of it.

**Meanwhile, it is all really seems to me to be just about stitching to [SemVer](https://semver.org) rules**. E.g. `3.2.0` **should** have been backward compatible to `3.0.1`, if it's not then it should have been versioned `4.0.1`, instead. If these rules were followed, there would not be the need to apply tilde requirements as cargo is [SemVer compatible](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio) by default. So maybe it worth re-considering _ink!_ versioning policy more rigorously.

Other questions to regard on this topic:

1.  Why should we really increment `examples/` contracts manifest versions without actually changing the contract sources itself at all?
2.  The workflow described [here](https://github.com/paritytech/ink/blob/master/RELEASES_CHECKLIST.md) does not imply fixing older releases like issuing `v3.0.2` containing hotfix for `v3.0.1`.  
    But it turns out we still should make such releases to support older versions being used by contract developers, as e.g. to fix such issues as being reported in the aforementioned SE question.

**Comment by athei** [comment]
> This leads to that 3.2.0 is being the resolved version even when =3.0.1 is specified in the contract manifest, for the following crates:

This is wrong. `=3.0.1` will only ever resolve to `3.0.1`. But we don't use the `=` in our manifests anywhere.

> As a hotfix for this, I've [changed the dependencies](https://github.com/paritytech/ink/commit/0638f8208431ffb6c188170fe1132ad746dee1b1) to be specified as [tilde requirements](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#tilde-requirements). I suggest making release v3.0.2 out of it.

Please don't. Tilde is very uncommon.

> Meanwhile, it is all really seems to me to be just about stitching to [SemVer](https://semver.org/) rules. E.g. 3.2.0 should have been backward compatible to 3.0.1, if it's not then it should have been versioned 4.0.1, instead. If these rules were followed, there would not be the need to apply tilde requirements as cargo is [SemVer compatible](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio) by default. So maybe it worth re-considering ink! versioning policy more rigorously.

Depends on how you define the scope of semver. When just looking at the crate this is a minor release because it just adds new functionality and the old code still compiles. If you say it is also about being compatible to old `pallet-contracts` versions then, yes, it should have been a major release. However, I don't think this is really feasible: There is no semver on the substrate side where we could sync it to.

**Comment by agryaznov** [comment]
> `=3.0.1` will only ever resolve to `3.0.1`. But we don't use the `=` in our manifests anywhere.

The origin was in [this](https://substrate.stackexchange.com/a/2727/472) recommendation to specify `=3.0.1` in **contract** manifest (again, to make it possible to build contract with particular *ink!* and *pallet* versions). This then leads to e.g. getting `inv_env 3.0.1` and that, it turn, gets `ink_allocator 3.2.0` because it has its dependency specified as `ink_allocator = { version = "3.0.1"...` in its manifest, which resolves to `3.2.0` bc of the aforementioned rule (`3.0.1 := >= 3.0.1 < 4.0.0`). And then guess what, it's won't compile the contract because `3.2.0` is not compatible with `3.0.1`...

> Please don't. Tilde is very uncommon.

I agree, but what are the other options for solving this then?
 
>  If you say it is also about being compatible to old `pallet-contracts` versions then, yes, it should have been a major release. 
However, I don't think this is really feasible: There is no semver on the substrate side where we could sync it to.

What do you think about making it in this logic?: *if the release being issued is still compatible with the same `pallet_contracts` version as the previous release, than it's a MINOR release. If not, then it's a MAJOR one.*

**Comment by athei** [comment]
> What do you think about making it in this logic?: if the release being issued is still compatible with the same pallet_contracts version as the current MAJOR ink! version works with, than it's a MINOR (or PATCH) release. Otherwise, it's a new MAJOR one.

This would make us go through major versions very quickly. We want to be able to **add** functionality in a backwards compatible way without issuing a new major version. What happened here was just a mistake. We broke existing code without issuing a new major: We didn't just **add** but replaced the existing `seal_set_storage` by a new version. The issue is that we let that slip though. If we would still be using the old version for the existing `Mapping::set` and the new function for `Mapping::contains` than a minor release wouldn't have been a big issue.

**Comment by agryaznov** [comment]
> If we would still be using the old version for the existing Mapping::set and the new version for Mapping::contains than a minor release wouldn't have been a big issue.

The issue was actually not about that. Once we import a new `seal_` function (or version of a function) from *ink_env*, it makes ink! backward incompatible with previous *node* being built with *pallet_contract* having not these new function (or version of a function).   

With [#1224](https://github.com/paritytech/ink/pull/1224/files#diff-3a90c3b2c03d7afb655f6a045e8142cf3a01a4b142eb6741fda69c9afcee80ddR374) we [imported](https://github.com/paritytech/ink/pull/1224/files#diff-3a90c3b2c03d7afb655f6a045e8142cf3a01a4b142eb6741fda69c9afcee80ddR374) (and then with [#1249](https://github.com/paritytech/ink/pull/1249) had them stabilized) these two functions:

- `[seal1] seal_set_storage`
- `[seal0] seal_contains_storage`

This made `3.1.0` ink! release containing these changes incompatible with *contracts_node* `0.13.0`. This is what led to aforementioned [SE repoted issue](https://substrate.stackexchange.com/questions/2721/cargo-contract-3-0-1). It looks like people (IMHO quite reasonably) expect MINOR relases to stay compatible with the same node version within the same MAJOR release, i.e. if ink! `3.0.1` works well with node `0.13.0` then `3.1.0` is expected (by users) to work with that same version, which is not the case with current versioning policy.

**Comment by agryaznov** [comment]
So the changes that made 3.1.0 backward incompatible with the elder node version (0.13.0) are reverted in [this](https://github.com/paritytech/ink/tree/ag-3.3.0-hotfixes) branch and the MINOR ink! [3.3.0 release](https://github.com/paritytech/ink/releases/tag/untagged-e38b4961b19c1ec3d7dc) is planned.

**Comment by AwesomeIbex** [comment]
Is there any plan to yank 3.0.0 and publish a patch with ink_lang_codegen as a fixed dependency? I only just found this after spending some time on it.

**Comment by agryaznov** [comment]
The [3.3.0 release](https://github.com/paritytech/ink/pull/1284) is on its way to fix these issues.

**Comment by AwesomeIbex** [comment]
> The [3.3.0 release](https://github.com/paritytech/ink/pull/1284) is on its way to fix these issues.

I think this solves the problem for users on `3.3.0`. Not for `3.0.0`, right? 

Would it not also be useful for users facing the same issue to:
- at least have a quick note on < 3.3.0 releases to override the `ink_lang_codegen` crate
- better still, yank the defective crate and publish a patch that fixes it without having users override the crate themselves

Personally, I think users may not want to blindly update to another minor version, as it stands the only place to find this issue is in this issue, which another release does not necessarily fix the issue for users on `3.0.0`.

**Comment by agryaznov** [comment]
As cargo [sticks](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio) to SemVer on dependency crates version resolution, after ink! `3.3.0` is published, even users of `3.0.0` should become getting `ink_lang_codegen` `3.3.0`, without overriding the crate themselves.  

The backwards compatibility breaking changes described (and fixed) in the #1284 were introduced not in `3.0.0` but in `3.1.0` and fixed in `3.3.0` minor release in accordance to the [SemVer](https://semver.org/#what-do-i-do-if-i-accidentally-release-a-backwards-incompatible-change-as-a-minor-version) practices.

**Comment by agryaznov** [comment]
Solved by #1284
