### ISSUE TITLE
ink! 4.0

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink#1343]
# The Vision
With the next major release of ink! we strive to:

* implement all remaining breaking changes from our endeavor of reducing contract sizes (how the storage API works).
* Introduce a new metadata format to account for some of our current shortcomings (e.g. versioning).
* make ink! closer to the idiomatic way of Rust (by reverting transactions on `Err` returns from constructors).
* create tooling for testing cross-contract calls and testing against a custom runtime.
* improve the developer experience by bundling all ink! crates into one `ink` entrance crate.
* allow different contracts to reference and use the same event types.

We moved this point to 4.1:

* include first support for XCM and XCM testing.

# The Plan

We're already in the middle of this. See the linked view.

# Open Questions
_If you want to help us out and contribute to this issue, in this section you can find open questions and tasks where we would appreciate any input._

Currently we don't have open questions.

---
Here you can find the board with specific sub-tasks to this milestone:
https://github.com/orgs/paritytech/projects/29/views/6

**Comment by cmichi** [comment]
@forgetso It should all be on here: https://github.com/paritytech/ink/projects/8, the other one was an experiment which only existed for a short amount of time. I'm surprised that you even noticed it!

**Comment by cmichi** [comment]
Ah I get it now, the link to the board was in the GitHub description of this issue, I've updated it.

>Hi, can't wait to see cross contract testing.

Yes, me too! How are you doing it right now? redspot + scripting?

**Comment by kvinwang** [comment]
Would the `pallet-contracts` running ink! 4.0 contracts can also run ink! 3.0 contracts?

**Comment by forgetso** [comment]
Thanks for the link!

> Yes, me too! How are you doing it right now? redspot + scripting?

We are not currently testing cross contract calls although we would have used redspot, yes.

**Comment by stillonearth** [comment]
So cross-contact call is scheduled for 4.0? Should one wait for it (if it's fairly close) or go with redspot?

**Comment by HCastano** [comment]
@stillonearth yes it's already working (albeit with some rough edges). For example, take a look at the contracts in `lang-err-integration-tests` for some examples on how to use it

**Comment by HCastano** [comment]
Closed via https://github.com/paritytech/ink/pull/1653 :shipit:
