### ISSUE TITLE
Implement Trait Support

### ISSUE THREAD

**Issue by satellitex** [paritytech/ink#139]
# Allow contracts to implement traits

We want to use Rust's trait function on ink!. The trait is suitable for expressing standard protocols on contract. For example, `ERC20` is better for expressing by trait.

## Current Situation

Currently, ink! cannot use trait implementation on `contract!` macro.(only can use `Deploy` trait).

## Design Goal

contract! macro adds a function that is trait implementation. `ast.rs` adds struct `pub struct ItemTraitImpl` and `ast.rs`/`parser.rs` adds implementation to parse valid rust syntax. And, generating valid rust code should be implemented.

For example, I want to add a function that is syntax like below on contact! macro.
```
pub trait Erc20 {
    /// Returns the total number of tokens in existence.
    fn total_supply(&self) -> Balance;
    ...
}
contract! {
   struct Erc20Token {
        ...
    }
    ...
    impl Erc20 for Erc20Token {
       external fn total_supply(&self) -> Balance {...}
        ...    
    }
}
```

Are there any plans to implement?  Or, are there similar or dependent tasks?

---

### Design Goal

```rust
#[ink::contract(
    types = DefaultSrmlTypes,
    version = "0.1.0",
)]
mod erc20 {
    /// A trait implementable by contracts.
    trait Erc20 {
        /// Returns the total number of tokens in existence.
        fn total_supply(&self) -> Balance;
        /// Returns the balance of the owner.
        fn balance_of(&self, owner: AccountId) -> Balance;
    }

    #[ink(storage)]
    struct Erc20Token {
        total_supply: storage::Value<Balance>,
        balances: storage::HashMap<AccountId, Balance>,
    }

    impl Erc20 for Erc20Token {
        #[ink(message)]
        fn total_supply(&self) -> Balance { ... }
        #[ink(message)]
        fn balance_of(&self, owner: AccountId) -> Balance { ... }
    }
}
```

**Comment by Robbepop** [comment]
I am still a fan of this idea, however, its current design leaves some open questions.
In Rust it is possible to emulate function overloading by using multiple traits, like this:

```rust
pub trait Erc20 {
    fn total_supply(&self) -> Balance;
}

pub trait Erc721 {
    fn total_supply(&self) -> Balance;
}

contract! {
    struct CombinedErcToken { ... }

    impl Erc20 for CombinedErcToken {
        fn total_supply(&self) -> Balance { ... }
    }

    impl Erc721 for CombinedErcToken {
        fn total_supply(&self) -> Balance { ... }
    }
}
```

So when calling `total_supply` on `CombinedErcToken`: Which one of the two implementations to call?
With this we have two options:
1. Forbid using traits offering same method named. (Breaks Rust compat. in confusing ways)
1. Find a decent way to differentiate between both calls. This would be possible by complicating the routines behind choosing the function selectors.

So this proposal needs to find a decent solution for this (and maybe other problems) first before we can even start thinking about implementing it for ink!.

**Comment by Robbepop** [comment]
Superseeded by https://github.com/paritytech/ink/issues/441.
