### ISSUE TITLE
Custom types in mapping 

### ISSUE THREAD

**Issue by andropixels** [paritytech/ink#1398]
how to create a mapping with custom types ? 
for example 
i have a type User  and i want Mapping<i128 ,User>  
please suggest the good way and help me to inlighten myself with ink !

**Comment by SkymanOne** [comment]
As answered by Hernando in this [question](https://substrate.stackexchange.com/questions/1659/how-to-have-a-mapping-in-a-custom-structure-inside-an-ink-contract)

> Mapping requires that [values implement PackedLayout](https://paritytech.github.io/ink/ink_storage/struct.Mapping.html#impl)

So you custom type should implement [`Packed`](https://paritytech.github.io/ink/ink_storage_traits/trait.Packed.html) to be used in `Mapping<K, V>`

**Comment by 123oli** [comment]
Double mapping is not possible as per [this comment](https://github.com/paritytech/ink/issues/1175#issuecomment-1064162106)

**Comment by andropixels** [comment]
thanks for the inputs
