### ISSUE TITLE
Substrate UI is not supporting `Option` type and Vec<Vec<u8>> as a return data type when ABI is passed during instantiation

### ISSUE THREAD

**Issue by satyamakgec** [paritytech/ink#141]
I want to deploy my contract on substrate v1.0.0 UI but not able to instantiate the deployed code when I am trying to attach the ABI of the code. 

ABI used - https://gist.github.com/satyamakgec/599301a811a9fe0b8fbf4013ddadd38a

**Comment by Robbepop** [comment]
Could you please deliver more information about what doesn't work and what should work?
@jacogr

**Comment by satyamakgec** [comment]
When I am trying to instantiate my contract and attaching the ABI then I am getting this error - 
![Screen Shot 2019-07-13 at 8 51 45 AM](https://user-images.githubusercontent.com/14581509/61197946-0c980b00-a6f5-11e9-98ec-1d47b3f6c29f.png)

**Comment by jacogr** [comment]
Uploading to https://polkadot.js.org/apps/ -

![image](https://user-images.githubusercontent.com/1424473/61210325-694af400-a6fc-11e9-815d-53584cc8b4bb.png)

Support for `Option<T>`, `Array<T>`, etc. has been in for quite some time now.

The other URLs have not been deployed in some time (manual step, it is never on the latest), they may be done sometime this week.

**Comment by Robbepop** [comment]
@jacogr What about nested uses of `Array` and `Option` - I have heard that they cause problems, is that still the case? And while fixed-sized `Array` is supported, does that also count for dyn-sized `Vec` which is used above?

@satyamakgec I think it is best for the UI side to wait until we finished implementing the upcoming new metadata format into ink!. It will be much more fine grained and you as a developer will be able to also custom types.

**Comment by jacogr** [comment]
Nested is an issue atm. There are no plans to address it at this point since it is throw-away work once we bring in support for the next-generation ABIs.

**Comment by satyamakgec** [comment]
@Robbepop No worries, I can wait until those features are added into the substrate UI

**Comment by Robbepop** [comment]
So I guess this is more of a UI issue than ink! one. I would like to close this then. I think the UI side already has an open issue for this task.
