### ISSUE TITLE
Move examples to a separate repository

### ISSUE THREAD

**Issue by SkymanOne** [paritytech/ink#1410]
Following the Smart Contract Monthly Meeting from 21/09/2022, I open this issue to formalise the decision about smart contract examples in `ink` repository.

# Problem
- Currently, ink dependencies in `examples` folder point to the master branch in this repository. This means, if we introduce breaking changes, developers will get errors when trying to copy-paste the code into their project which in fact points to the `crates` version of ink.
- It was also discussed that compilation of all examples correspond to the majority of CI build time.

# Proposal
- Leave a single `mother` contract which is going to be used for CI testing
- Rename `examples` folder into `integration_testing`
- Move all examples into separate repository `paritytech/ink_examples` and make them point to the production version of ink published on crates.io

# Benefits
- Faster CI testing times
- Better developer experience
- Easier and faster PR process for modifying examples or introducing new ones

**Comment by xermicus** [comment]
> Move all examples into separate repository paritytech/ink_examples and make them point to the production version of ink published on crates.io

Just an idea, this could potentially be added as submodule

**Comment by athei** [comment]
The point is to link the examples via crate.io. The idea is **not** to build them as part of the ink! CI which the submodule idea suggests. Putting them into their own repo is merely to make them more visible. The crux is to not have them depend on master but rather on the latest release.

**Comment by HCastano** [comment]
So we're keeping contracts in this repo but as integration tests.

Our "stable" examples were moved in https://github.com/paritytech/ink/pull/1659 to https://github.com/paritytech/ink-examples.
