### ISSUE TITLE
the link: ink! documentation portal seems down

### ISSUE THREAD

**Issue by thiolliere** [paritytech/ink#1419]
in the readme the link: ink! documentation portal seems down

it opens `https://use.ink/` which show 404 error gihtub page not found

**Comment by cmichi** [comment]
Sorry for that, we're switching to a new domain [use.ink](http://use.ink) for the documentation portal right now and there is some delay due to DNS updates.

**Comment by cmichi** [comment]
@thiolliere Hey Gui, does any of the above domains work for you? Btw. happy to see that you're exploring this project :-).

**Comment by thiolliere** [comment]
yes use.ink works now :-)
