### ISSUE TITLE
`cargo contract test` fails with "associated consts cannot be referenced in patterns"

### ISSUE THREAD

**Issue by Kartos102** [paritytech/ink#1433]
I made the new project using the `cargo contract new flipper`

and the test it by using `cargo +nightly test`
But I get this error
How to solve this?
![image](https://user-images.githubusercontent.com/83195375/195399687-a4e1bd71-4c18-4eb7-b46a-9555d2100fcc.png)

**Comment by 123oli** [comment]
> `cargo test` it works why doesn't `cargo +nightly test' work?
> 
> cargo-contract version is 1.5.0

I use `cargo +nightly-2022-08-15 test` rather `cargo +nightly test` to test and `cargo +nightly-2022-08-15 contract build` to build rather `cargo +nightly contract build` today and it works for me. My cargo contract version `cargo-contract 1.5.0-unknown-x86_64-apple-darwin`

**Comment by HCastano** [comment]
So the answer on SO mentions installing a different `nightly`, as follows:

```
rustup toolchain install nightly-2022-08-15
rustup target add wasm32-unknown-unknown --toolchain nightly-2022-08-15
rustup component add rust-src --toolchain nightly-2022-08-15
cargo +nightly-2022-08-15 contract build
```

@Kartos102 I'm gonna close this, but feel free to re-open with more specific steps to replicate your problems (ink! version, `cargo-contract` version, `rustc` version, etc.) if this is still an issue for you
