### ISSUE TITLE
Simple struct requires SpreadLayout trait implementation

### ISSUE THREAD

**Issue by h4x3rotab** [paritytech/ink#1440]
Suppose we just want to write a simple contract to store some `H160` EVM contract address:

```rust
#[derive(Encode, Decode, Debug, PackedLayout, SpreadLayout)]
struct Config {
  evm_contract: H160,
}

#[ink(storage)]
struct MyContract {
  config: Config,
}
```

The compiler will complain that `primitive_types::H160` doesn't implement `SpreadLayout`. So it cannot derive `PackedLayout` for `struct Config`.

It would be nice if any data type implements `Encode + Decode` can be stored in the storage by packing as a bytes blob by default. In this case, `H160` is defined outside in the crate `primitive_types`. I cannot easily implement a trait for that, unless I create a wrapper type and write the boilerplate code.

Tested with ink v3.3.1

**Comment by HCastano** [comment]
Hey, sorry for the late response here. As part of ink! 4.0 we've removed `SpreadLayout`, `PackedLayout`, et. al (see https://github.com/paritytech/ink/pull/1331). I'm gonna close this since you should be able to do this without any problems with ink! 4.0. If you can't feel free to re-open it.
