### ISSUE TITLE
'mother' example causes exception in contracts UI

### ISSUE THREAD

**Issue by psfblair** [paritytech/ink#1451]
**Questions**

- Is this a bug concerning building of ink! smart contracts?
    No.
- Is this a bug that appears when interacting with smart contracts via the Polkadot JS browser UI?
    Contracts UI, not polkadot-js

**FAQ**

- Are you using the nightly Rust channel to compile your smart contract?
toolchain `nightly-2022-06-30-x86_64-apple-darwin`

- Are you using an up-to-date `cargo-contract`? Check via `cargo contract --version`.
cargo-contract-contract 2.0.0-alpha.4-unknown-x86_64-apple-darwin

- Are you using an up-to-date ink! version in your smart contract?
Using master branch of ink repo at commit c083c8ca77e556ea209ee7b38a94c6c506b15663
(Cargo.toml has ink = { path = "../../crates/ink", default-features = false } )

**Describe the bug**

Trying to add the contract via the Contracts UI (https://contracts-ui.substrate.io) on a local node running substrate-contracts-node results in a blank screen after the "Upload and Instantiate" button is clicked -- regardless of which deployment constructor is used. 

The following appears in the substrate-contracts-node log: 
2022-10-26 13:46:39.630 DEBUG tokio-runtime-worker runtime::contracts: Execution finished with debug buffer: panicked at 'dispatching ink! constructor failed: could not read input', /Users/paulblair/notbackedup/tutorials/ink/examples/mother/lib.rs:131:5

The following appears in the console log for the Contracts UI in the browser in Opera:

react.ec1551b3.js:32 TypeError: Cannot read properties of undefined (reading 'displayName')
    at encodeTypeDef (polkadot.4d4418f9.js:2:559593)
    at M9 (index.139004f8.js:253:20908)
    at vo (react.ec1551b3.js:30:19495)
    at Qa (react.ec1551b3.js:32:44038)
    at Ba (react.ec1551b3.js:32:39748)
    at ud (react.ec1551b3.js:32:39679)
    at Jr (react.ec1551b3.js:32:39539)
    at Du (react.ec1551b3.js:32:35928)
    at $a (react.ec1551b3.js:32:34881)
    at E (react.ec1551b3.js:17:1562)

The following appears in the console log for the Contracts UI in the browser in Firefox:

TypeError: e is undefined
    encodeTypeDef https://contracts-ui.substrate.io/assets/polkadot.4d4418f9.js:2
    M9 https://contracts-ui.substrate.io/assets/index.139004f8.js:253
    vo https://contracts-ui.substrate.io/assets/react.ec1551b3.js:30
    Qa https://contracts-ui.substrate.io/assets/react.ec1551b3.js:32
    Ba https://contracts-ui.substrate.io/assets/react.ec1551b3.js:32
    ud https://contracts-ui.substrate.io/assets/react.ec1551b3.js:32
    Jr https://contracts-ui.substrate.io/assets/react.ec1551b3.js:32
    Du https://contracts-ui.substrate.io/assets/react.ec1551b3.js:32
    $a https://contracts-ui.substrate.io/assets/react.ec1551b3.js:32
    E https://contracts-ui.substrate.io/assets/react.ec1551b3.js:17
    ot https://contracts-ui.substrate.io/assets/react.ec1551b3.js:17
    EventHandlerNonNull* https://contracts-ui.substrate.io/assets/react.ec1551b3.js:17
    <anonymous> https://contracts-ui.substrate.io/assets/react.ec1551b3.js:17
[react.ec1551b3.js:32:161](https://contracts-ui.substrate.io/assets/react.ec1551b3.js)
    Eu https://contracts-ui.substrate.io/assets/react.ec1551b3.js:32
    callback https://contracts-ui.substrate.io/assets/react.ec1551b3.js:32
    hi https://contracts-ui.substrate.io/assets/react.ec1551b3.js:30
    Mi https://contracts-ui.substrate.io/assets/react.ec1551b3.js:32
    Ua https://contracts-ui.substrate.io/assets/react.ec1551b3.js:32
    td https://contracts-ui.substrate.io/assets/react.ec1551b3.js:32
    id https://contracts-ui.substrate.io/assets/react.ec1551b3.js:32
    gn https://contracts-ui.substrate.io/assets/react.ec1551b3.js:32
    $a https://contracts-ui.substrate.io/assets/react.ec1551b3.js:32
    E https://contracts-ui.substrate.io/assets/react.ec1551b3.js:17
    ot https://contracts-ui.substrate.io/assets/react.ec1551b3.js:17
    (Async: EventHandlerNonNull)
    <anonymous> https://contracts-ui.substrate.io/assets/react.ec1551b3.js:17
    <anonymous> https://contracts-ui.substrate.io/assets/react.ec1551b3.js:17

**Expected behavior**
Expect to see a page where I can interact with the contract

**Screenshots**
[Page is completely blank, so not much to see there.]

**Additional context**
Substrate Contracts Node version 0.21.0-e336e78ee2d

**Comment by psfblair** [comment]
Also - when instantiating I tried various names under "Contract name" including "Mother contract" and "Mother2".

**Comment by SkymanOne** [comment]
Have you tried to build to contract with rust stable? ink! v4 does not require rust nightly.
Let me know if the problem still persists.

**Comment by psfblair** [comment]
I'm having some trouble with this -- even though stable is my default toolchain, I can't seem to get cargo to see it. 
So far I've tried
`cargo +stable contract build`
also
`rustup default stable`
also
`rustup override set stable`
also creating a rust-toolchain.toml inside the `mother` directory with
```
[toolchain]
channel = "stable"
```
Regardless, each time I run, the build starts with
```
% cargo +stable contract build
 [1/6] Checking ink! linting rules
    Updating git repository `https://github.com/paritytech/ink/`
Checking with toolchain `nightly-2022-06-30-x86_64-apple-darwin`
```
I don't see any configuration files in the directory or elsewhere that are setting the toolchain to nightly, so I'm stumped.

The cargo-contract repository says: "cargo contract build must be run using the nightly toolchain." (Although it indicates that the +nightly switch is necessary for doing so.)

I am running with cargo-contract-contract 2.0.0-alpha.4-unknown-x86_64-apple-darwin

What am I missing?

**Comment by HCastano** [comment]
@statictype can you take a look to see if this is still an issue? I suspect not, but better to double check

**Comment by statictype** [comment]
as far as I see Mother is no longer part of the examples. i tested with `ink! 4.0.0-beta` and works fine

**Comment by HCastano** [comment]
It's in the `integration-tests` folder now. 

Cool, thanks for checking!
