### ISSUE TITLE
Use latest rust nightly when building ink!

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/ink#147]
After discussion with @Robbepop, we agreed that using the latest version of Rust nightly will provide a better onboarding experience for new ink! developers.

Mainly, we want to eliminate the issue around the compiler complaining that the nightly version is not installed, when it means the _specific_ nightly version in the toolchain that we specify is not installed.

**Comment by Robbepop** [comment]
Probably fixed by https://github.com/paritytech/ink/pull/148.
