### ISSUE TITLE
ERROR: Mismatching versions of `parity-scale-codec` were found!

### ISSUE THREAD

**Issue by avirajkhare00** [paritytech/ink#1485]
I am trying to run the following command to build the erc20 contract inside examples. I am getting this issue. How do I fix it?

```
cargo +nightly contract build
ERROR: Mismatching versions of `parity-scale-codec` were found!
Please ensure that your contract and your ink! dependencies use a compatible version of this package.
```

**Comment by avirajkhare00** [comment]
I am using

I am using cargo contract version: `cargo-contract 1.5.0-unknown-aarch64-apple-darwin`
Ink version is `4.0.0-alpha.3`

**Comment by Robbepop** [comment]
This should do the trick for you: `cargo install cargo-contract --version 2.0.0-alpha.5`

**Comment by avirajkhare00** [comment]
Already updated.

**Comment by avirajkhare00** [comment]
It's resolved.
`cargo contract build` didn't work out.
`cargo-contract contract build` did work out.

@Robbepop is it intentional?

**Comment by keeganquigley** [comment]
Note that as mentioned [here](https://github.com/paritytech/ink/blob/master/CHANGELOG.md#compatibility), you actually need to use `cargo-contract --version v2.0.0-beta` to work with ink! 4.0 contracts.
