### ISSUE TITLE
`Mapping::insert()` fails in E2E tests

### ISSUE THREAD

**Issue by SkymanOne** [paritytech/ink#1488]
# Summary
When trying to use a message contains `Mapping::insert()` in E2E test, the test errors at dry-run stage for this specific function.

# Reproducer
1. Checkout [gn/mapping-take-tests](https://github.com/paritytech/ink/tree/gn/mapping-take-tests)
2. Navigate to [examples/mappings](https://github.com/paritytech/ink/tree/gn/mapping-take-tests/examples/mappings) folder
3. Run [`substrate-contracts-node V0.21.0`](https://github.com/paritytech/substrate-contracts-node/releases/tag/v0.21.0) - `substrate-contracts-node --dev -linfo,runtime::contracts=debug`
4. Run `RUST_LOG=debug cargo test`
5. You should get the following error message
```
***
2022-11-09T16:02:34Z INFO  ink_e2e] [test: insert_and_get_works] call: [E8, 8D, 16, 46, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00]
[2022-11-09T16:02:34Z INFO  ink_e2e] [test: insert_and_get_works] call dry run: Err(Module(ModuleError { index: 7, error: 25, message: None }))
[2022-11-09T16:02:34Z INFO  ink_e2e] [test: insert_and_get_works] call dry run debug message: 
test mappings::e2e_tests::insert_and_get_works ... FAILED

failures:

---- mappings::e2e_tests::insert_and_get_works stdout ----
thread 'mappings::e2e_tests::insert_and_get_works' panicked at 'call failed: CallDryRun', lib.rs:117:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    mappings::e2e_tests::insert_and_get_works

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.23s

error: test failed, to rerun pass '--lib'
***
```

Module error that the message refers to is [`StorageDepositLimitExhausted`](https://github.com/paritytech/substrate/blob/a6da808575fe403ab2bd7f6cd009896cdc6fd71a/frame/contracts/src/lib.rs#L824)

# Edge cases
* Commenting out the code block containing `Mapping::take()` does not cause the problem, so it is definitely to do something with the function.
* Specifying `storage_limit` has no effect
* Executing normal & dry-run call via `cargo-contract` and PolkadotJS app *do not* result in error
* The implementations of dry-run call both in `cargo-contract` and `E2E` crate seem to be the same.

**Comment by athei** [comment]
Which node do you run against?

**Comment by SkymanOne** [comment]
> Which node do you run against (which version)? Just asking for proper reproduction. Not that I think that it actually broke in the node.

Updated the description to indicate the node version

**Comment by SkymanOne** [comment]
After looking into the issue. I have found the message bytes in logs:
```
[2022-11-10T21:05:01Z INFO  ink_e2e] [test: insert_and_get_works] call: [E8, 8D, 16, 46, 40, 42, 0F, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00]
```
I then converted them to hash and put them as arg in PolkadotJS RPC Call and also got error. So my guess it is the problem with encoding of the the message in E2E
