### ISSUE TITLE
Suggestion: Add example section for crate docs

### ISSUE THREAD

**Issue by doutv** [paritytech/ink#1493]
It's convenient to know the usage from crate docs.  

For example, [the docs for Rust std HashMap](https://doc.rust-lang.org/std/collections/struct.HashMap.html#examples) contain an example section so that developers can quickly understand its usage.

I think ink! crate docs also need an example section, such as [Mapping docs](https://paritytech.github.io/ink/ink_storage/struct.Mapping.html).

I'm willing to open pull requests for adding some of these example sections if needed.

**Comment by ascjones** [comment]
Absolutely, we definitely want to make our docs as comprehensive as possible. We'd love your contribution, so feel free to open a PR!
