### ISSUE TITLE
`ReturnTypeSpec` should take a `TypeSpec` directly

### ISSUE THREAD

**Issue by HCastano** [paritytech/ink#1515]
Right now `ReturnTypeSpec` expects an `Option` to be passed indicating whether or not a function returns something. 

With recent changes related to #1450 and #1504 all messages and constructors now return a value,so there's no need to have `ReturnTypeSpec` expect an `Option`.

Related discussion [here](https://github.com/paritytech/ink/pull/1504#discussion_r1026250084).

**Comment by xermicus** [comment]
[Also related](https://github.com/paritytech/ink/pull/1450), I sketched a [possible approach here](https://github.com/paritytech/ink/commit/a37af7553e9c87ae8af7375bec4b7af0d5517299).
