### ISSUE TITLE
Incorrect codegen for trait methods

### ISSUE THREAD

**Issue by kvinwang** [paritytech/ink#1530]
**Describe the bug**
I am trying out the ink 4.0-beta.

Given the following trait definition:
```rust
#[ink::trait_definition(namespace = "pink_system")]
pub trait System {
    #[ink(message)]
    fn version(&self) -> (u16, u16);
}
```
The generated forwarder is:
```rust
impl<E> System for __ink_TraitCallBuilderSystem<E>
where
    E: ::ink::env::Environment,
{
    fn version(&self) -> Self::versionOutput {
        ::ink::env::call::build_call::<Self::Env>()
            .call_type(
                ::ink::env::call::Call::new()
                    .callee(::ink::ToAccountId::to_account_id(self)),
            )
            .exec_input(::ink::env::call::ExecutionInput::new(
                ::ink::env::call::Selector::new([0x87_u8, 0xC9_u8, 0x8A_u8, 0x8D_u8]),
            ))
            .returns::<(u16, u16)>()
    }
}
```
And also the metadata.json:
```json
{
  "args": [],
  "docs": [],
  "label": "System::version",
  "mutates": false,
  "payable": false,
  "returnType": {
    "displayName": [],
    "type": 6
  },
  "selector": "0x87c98a8d"
},
...
{
"id": 6,
"type": {
  "def": {
    "tuple": [
      7,
      7
    ]
  }
}
},
```

**Expected behavior**
It should be:
```.returns::<Result<(u16, u16),LangError>>()```
and ditto in the metadata.

**Comment by ascjones** [comment]
I see the handling of `LangError` for traits was left as a follow-up in the @HCastano's original PR: https://github.com/paritytech/ink/pull/1450.

**Comment by kvinwang** [comment]
Hey guys,

I've noticed that `4.0.0-rc` has been released.
Are the follow-ups in #1450 been done? This issue is definitely blocking us to upgrade to ink-4.0.

**Comment by ascjones** [comment]
Yes I believe the issues you have raised here are now fixed via https://github.com/paritytech/ink/pull/1525 (call builder return type) and #1531 (metadata). Can you double check and then we can close this issue?

**Comment by kvinwang** [comment]
Great, it works with `4.0.0-rc`.
