### ISSUE TITLE
Mis-aligned allocation in ink

### ISSUE THREAD

**Issue by kvinwang** [paritytech/ink#1535]
I am trying to port the quickjs runtime into ink. It always crashes because it rely on the heap allocation alignment.

Looks like the ink's bump allocator doesn't obey Rust's alignment requirements.
Given the follow code:
```rust
let buf1 = Vec::<u8>::with_capacity(3);
let buf2 = Vec::<u64>::with_capacity(1);
info!("ptr to buf1 :{:?}", buf1.as_ptr());
info!("ptr to buf2 :{:?}", buf2.as_ptr());
info!("align of u64:{}", align_of::<u64>());
```
Runing in ink would get somthing like:
```
 ptr to buf1 :0x30022
 ptr to buf2 :0x30025
 align of u64:8
```
Where the ptr of buf2 is mis-aligned.

**Expected behavior**
It should be aligned as Rust's default allocator do. See [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d360e8a505d68acb41aadd985de0e063) which meets the [Allocator requirements](https://doc.rust-lang.org/beta/core/alloc/trait.Allocator.html#required-methods).

**Comment by kvinwang** [comment]
> @kvinwang can you share the code that you're trying to run?

Here is the project I am working on.
Steps to reproduce:
1. Clone the source
```bash
git clone https://github.com/kvinwang/qjs.git --recursive
cd qjs
```
2. Remove the feature `wee-alloc` here: https://github.com/kvinwang/qjs/blob/bd36fa41d9b7687bb96053e4c8bec8381b8d893f/Cargo.toml#L13
3. Use another way to print the log here: https://github.com/kvinwang/qjs/blob/bd36fa41d9b7687bb96053e4c8bec8381b8d893f/lib.rs#L10
4. Build
```
cargo +nightly contract build --skip-linting --release
```
Now we got a compiled contract with a method `eval` which accepts a piece of JavaScript code as input.
For example: `JsTest::eval("console.log('Hello, World!')");`
However, the contract is indeterministic, so we need another contract to call it via delegate_call.

**Comment by SkymanOne** [comment]
@kvinwang Sorry for picking this up late. The links seem to be broken. Can you please either update them or confirm the issue?

**Comment by SkymanOne** [comment]
Just for records. I managed to partially reproduce the issue by inspecting logs from 
```rust
#[ink(message)]
pub fn buffer(&self) {
    let buf1 = Vec::<u8>::with_capacity(3);
    let buf2 = Vec::<u64>::with_capacity(1);
    ink::env::debug_println!("ptr to buf1 :{:?}", buf1.as_ptr());
    ink::env::debug_println!("ptr to buf2 :{:?}", buf2.as_ptr());
    ink::env::debug_println!("align of u64:{}", align_of::<u64>());
}
```
