### ISSUE TITLE
Print EmittedEvent in `test`

### ISSUE THREAD

**Issue by abhi3700** [paritytech/ink#1577]
This issue is related to printing event on terminal.

We need to implement `Debug` trait for [EmittedEvent](https://github.com/paritytech/ink/blob/master/crates/env/src/engine/off_chain/test_api.rs#L33)

**Comment by ascjones** [comment]
It is fairly simple, so feel free to open a PR for that. Alternatively you can just access the individual fields `data` and `topics` and print those the terminal.

**Comment by ascjones** [comment]
Closed by #1583
