### ISSUE TITLE
Failed to update a field in custom struct

### ISSUE THREAD

**Issue by 327istesting** [paritytech/ink#1599]
Hi, I got an error when I try to update a field in a custom struct in my project. I drafted a simple demo here for your reference.

I define the custom struct as following:

```
    #[derive(scale::Encode, scale::Decode, Debug, PartialEq, Eq,)]
    #[cfg_attr(
        feature = "std",
        derive(scale_info::TypeInfo, ink::storage::traits::StorageLayout)
    )]
    #[derive(Default)]
    struct CustomBool {
        boolean: bool,
    }
```
Then in the storage, I use the custom struct as the value of a mapping:
```
    #[ink(storage)]
    pub struct Test {
        count: u128,
        mappings: Mapping<u128, CustomBool>,
    }
```

In the following methods, I try to add new data into the mapping, then change the field `boolean` to `true` if it's `false` before.

```
        #[ink(message)]
        pub fn insert_value (&mut self, boolean: bool) -> Result<()>{
            let mut c = CustomBool{boolean};
            self.mappings.insert(self.count,  &mut c);
            self.count += 1;
            Ok(())
        }


        #[ink(message)]
        pub fn change_value (&mut self, id: u128) -> Result<()>{
            match self.mappings.get(id){
                None => return Err(Error::NotExist),
                Some(mut v) =>{
                    if v.boolean == true {
                        return Err(Error::NotFalse);
                    }else{
                        ink::env::debug_println!("before change, boolean is: {}", v.boolean);
                        v.boolean = true;
                        ink::env::debug_println!("after change, boolean is: {}", v.boolean);
                    }
                }
            }
            match self.mappings.get(id){
                None => return Err(Error::NotExist),
                Some(v) =>{
                    ink::env::debug_println!("outside first match, boolean is: {}", v.boolean);
                }
            }
            Ok(())
        }
```
Then I found I couldn't change the field `boolean` from `false`  to `true`. I added two `debug_println` in the `match` which will get the value of that field by the index, one before the statement updating the field showing the field value and one after it. I also put second `match` in the same method to check whether the field has been updated or not, however it returns the original value.

From contract-ui:
![](https://raw.githubusercontent.com/327istesting/test_custom_struct/master/contract-ui-output.png)

From terminal:
![](https://raw.githubusercontent.com/327istesting/test_custom_struct/master/debug-output.png)

Complete code could be found here: https://github.com/327istesting/test_custom_struct

cargo-contract version: `2.0.0-beta`
ink version: `4.0.0-beta`

**Comment by ascjones** [comment]
> Then I found I couldn't change the field boolean from false to true. I added two debug_println in the match which will get the value of that field by the index, one before the statement updating the field showing the field value and one after it. I also put second match in the same method to check whether the field has been updated or not, however it returns the original value.

Mapping is a thin wrapper over the underlying contract storage. In your example, modifying the `v` `Some(mut v)`  will not result in those changes being written to storage. You would need to do an explicit `insert` operation to update it. So when you read from storage again with `self.mappings.get(id)` it just reads a fresh value from the storage.

**Comment by 327istesting** [comment]
Hey @ascjones thanks for the answer, it solved my problem, cheers!
