### ISSUE TITLE
Cargo contract generates invalid config when - is used in name

### ISSUE THREAD

**Issue by jeluard** [paritytech/ink#160]
Using a contract name containing an `-` generates files that can't be build. It would be nice to either forbid those names or generate correct files.

e.g. 

`cargo contract new test-contract`

Changes required:

* Cargo.toml lib/name can't contain `-`
* build.sh `PROJECT_NAME` can't contain `-`

**Comment by flyq** [comment]
this is `Carge`'s rules:
https://github.com/rust-lang/cargo/blob/master/src/cargo/util/toml/targets.rs#L154
