### ISSUE TITLE
Add check for minimum supported Rust version

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink#1606]
Extracted from https://github.com/paritytech/cargo-contract/pull/848#discussion_r1038068702:

Add a check for the minimum supported Rust version to the `ink` crate. This can be done via  [`rust_version`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field). 

The minimum supported stable Rust version is 1.63.

**Comment by ascjones** [comment]
Closed by #1609
