### ISSUE TITLE
Getting issue on calling `wasIsTen()` function in contract-transfer

### ISSUE THREAD

**Issue by 123oli** [paritytech/ink#1608]
I have build and deploy ink [ink/examples/contract-transfer](https://github.com/paritytech/ink/tree/master/examples/contract-transfer) in  `Substrate Contracts UI Local Node`. Then, I called function `giveMe()` and passed 10 balance as arguments. After calling the function  works fine. I have included screenshots below:

<img width="1440" alt="2" src="https://user-images.githubusercontent.com/42571338/213840967-16905061-1470-4a0a-8322-80000571420f.png">

I have called `wasIsTen()` function, then I faced `Contract Reverted! Contract trapped during execution` issue and  I can't call contract. What is the issue here? What I am doing wrong?

<img width="1440" alt="3" src="https://user-images.githubusercontent.com/42571338/213841219-75cd0571-7295-483a-ac9e-787122d7a989.png">

**Comment by statictype** [comment]
this is not how the contract works. try adding the amount in the `value` input

<img width="1380" alt="Screenshot 2023-01-30 at 10 54 43" src="https://user-images.githubusercontent.com/42985153/215496505-844cec34-8b11-4a6c-b6f3-05768f33667e.png">
