### ISSUE TITLE
ink_e2e: Macro freaks out when no `crate-type = [`cdylib`]` is found

### ISSUE THREAD

**Issue by athei** [paritytech/ink#1631]
Apparently there is some flawed logic in the macro that tries to discover the contract crate by logic for a lib crate having the property `crate-type = ["cdylib"]`. The logic should be changed to just pick the `lib` crate of the package. There can only be one. So no need to filter.

**Comment by ascjones** [comment]
I believe this should be fixed now since  paritytech/cargo-contract#929, and now the latest release is used by `ink_e2e`. Please confirm.

**Comment by athei** [comment]
So I need to depend on `ink_e2e` master to test this behaviour?

**Comment by athei** [comment]
Jup. This is fixed. Thanks.
