### ISSUE TITLE
Unexpected values received for types i8 and i16 from ink! contract

### ISSUE THREAD

**Issue by sharma66mahesh** [paritytech/ink#1657]
**Describe the bug**
While querying the ink contract state from polkadot-js/api js library, I get unexpected values for types i8 and i16.
An issue was opened in the polkadot-js/api repo. However, due to lack of activity there, I'm mentioning it here too.
https://github.com/polkadot-js/api/issues/5483

**Comment by cmichi** [comment]
@statictype @DoubleOTheven Any idea?

**Comment by DoubleOTheven** [comment]
I left a comment [here](https://github.com/polkadot-js/api/issues/5483#issuecomment-1438622231) a few days ago.

**Comment by HCastano** [comment]
@DoubleOTheven this looks more like a PJS issue, can we close this?
