### ISSUE TITLE
`use.ink` example links 404

### ISSUE THREAD

**Issue by ggwpez** [paritytech/ink#1664]
Just opened up https://use.ink/ and saw that https://github.com/paritytech/ink/pull/1659 probably 404ed the `Smart Contract Examples` example links in the bottom.

**Comment by cmichi** [comment]
Maaann you're fast! We just merged https://github.com/paritytech/ink/pull/1659. Will be fixed in a sec!

**Comment by cmichi** [comment]
Fixed in https://github.com/paritytech/ink-docs/pull/174.

**Comment by Daanvdplas** [comment]
Found a remaining old link in [mapping.rs](https://github.com/paritytech/ink/blob/master/crates/storage/src/lazy/mapping.rs#L82). Apart from CHANGELOG.md I also found two in this [README](https://github.com/paritytech/ink/blob/master/integration-tests/upgradeable-contracts/README.md#forward-calls) (forward-calls & set-code-hash) and [here](https://github.com/paritytech/ink/blob/master/linting/rust-toolchain.toml#L2).

**Comment by ggwpez** [comment]
Can recommend this CI link checker for the markdown files: https://github.com/marketplace/actions/markdown-link-check
