### ISSUE TITLE
Accelerate CI

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#167]
Currently a single CI run takes roughly 35-40 minutes on Travis CI.
It being so slow has several reasons:
- Travis CI only allows for a very limited amount of compute resources (at least as long as we use the free version of it.)
- We do a lot of computations and re-computations over and over with our current CI approach. A big deal here is that our example checks are all isolated and do not share their build artifacts even though they could do that in theory.

So to fix CI we need to switch to a better environment, e.g. GitLab runners and we also need to find ways to reduce the recomputations and improve sharing of build artifacts.

The target goal for CI runs is 5-10 minutes, down from 35-40 minutes at the moment.

The current workflow for Travis CI can be found here: https://github.com/paritytech/ink/blob/master/.travis.yml
Internally it uses the scripts found in https://github.com/paritytech/ink/tree/master/scripts.

**Comment by Robbepop** [comment]
Typical ink! CI run at the moment takes approximately 50 minutes.

**Comment by TriplEight** [comment]
WIP: https://github.com/paritytech/ink/pull/196

**Comment by TriplEight** [comment]
Closed with #196
