### ISSUE TITLE
Add subxt like generation of the `Call` enum

### ISSUE THREAD

**Issue by athei** [paritytech/ink#1675]
The [`call_runtime`](https://docs.rs/pallet-contracts/16.0.0/pallet_contracts/api_doc/trait.Current.html#tymethod.call_runtime) API offered by pallet-contracts  allows contracts to pass an encoded `Call` to the runtime which then executes it.

The API still has a few issues:
* It is unstable (it will stay unstable if we don't start tinkering with it)
* Dispatchables can't return data on `Ok`. This is a constraint in FRAME. But I think it can be changed (I am looking into this).
* We don't have support for `call_runtime` in ink!, yet ( #1641).

As of right now those call data structures need to be constructed manually which is quite cumbersome. We need some code generation that constructs the `Call` enum of a runtime from metadata which can then be passed to `call_runtime`.

The code for this should already exist within `subxt`. We need to make it conveniently accessible within ink!.

This is the inverse direction of #1674.

**Comment by pmikolajczyk41** [comment]
I've already started looking at it some time ago and I'm planning to work on that next week as a follow-up to the mentioned PR :)

**Comment by athei** [comment]
`call_runtime` will be deprecated in favour of `execute_xcm` as the `Call` is not stable enough to use it in contracts. Hence we  don't want to build more codegen around it. We rather double down on XCM.
