### ISSUE TITLE
`e2e` additional_contract metadata randomly failing

### ISSUE THREAD

**Issue by boyswan** [paritytech/ink#1677]
I'm regularly getting this error when running `cargo +nightly test --features e2e-tests`. Nightly is required due to openbrush. The contracts are in the target dir as expected. Project is following a similar structure to `delegator` example.

```rust
error: custom attribute panicked
   --> src/lib.rs:134:9
    |
134 |         #[ink_e2e::test(additional_contracts = "foo/Cargo.toml bar/Cargo.toml")]
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: message: Metadata artifacts not generated
```

The only way around this is by making a change to one of the additional contracts and rerunning the test command, which will then rebuild and correctly run the tests as expected, or display an error message if any of the tests have failed to compile.

**Comment by ascjones** [comment]
Can you try with https://github.com/paritytech/ink/pull/1696 and confirm if it fixes the issue

**Comment by boyswan** [comment]
> @boyswan can you try with #1696 and confirm if it fixes the issue

Hmm sorry a slight tangent but  I'm having difficulty compiling with ink `4.0.1`. A little stumped by this - should this be working?

```rust
use ink::env::DefaultEnvironment;

async fn assert_owner_of(
    client: &mut Client<ink_e2e::PolkadotConfig, DefaultEnvironment>,
) {
 ...
}
```
```rust
332 |             client: &mut Client<ink_e2e::PolkadotConfig, DefaultEnvironment>,
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `ink_env::types::Environment` is not implemented for `DefaultEnvironment`
    |
    = help: the trait `ink_env::types::Environment` is implemented for `ink_env::types::DefaultEnvironment`
```

**Comment by ascjones** [comment]
There could be conflicting versions of `ink_env`. Try `cargo tree -p ink_env` to check.

**Comment by boyswan** [comment]
Looks like it, but this unfortunately leads down a rabbit hole of crates vs git dependency conflicts. Trying to patch my way around it but it's a bit of a hellish mess! Will let you know if I progress
