### ISSUE TITLE
Update documentation of the `Mapping`'s `size` method

### ISSUE THREAD

**Issue by wottpal** [paritytech/ink#1686]
Currently, [the documentation](https://docs.rs/ink_storage/4.0.0/ink_storage/struct.Mapping.html#method.size) does not say which unit the return value has (it is bytes).

CC @cmichi

**Comment by HCastano** [comment]
Can you open a PR for this?

**Comment by wottpal** [comment]
Yeah ofc. But never done rust/crate documentation before – It's just the comment/docstring above the function that needs to be changed, right?

**Comment by wottpal** [comment]
Yeah ofc. But never done rust/crate documentation before – It's just the comment/docstring above the function that needs to be changed, right?
