### ISSUE TITLE
E2E fails to compile when running in a separate file

### ISSUE THREAD

**Issue by SkymanOne** [paritytech/ink#1692]
1. create a separate file `e2e_tests.rs` and move all the code from `e2e_tests` module there (without `mod e2e_tests`)
2. add these lines on top of e2e_tests.rs file:
```rust
use crate::flipper::*;

#[cfg(all(test, feature = "e2e-tests"))]
pub use ink_e2e::build_message;
```
3 .in lib.rs add this:
```rust
#[cfg(all(test, feature = "e2e-tests"))]
pub mod e2e_tests;
```

It may run for the first time, but when rust-analyzer analyzes the project and expands macros, it messes up built artefacts.
When trying to run `cargo test --features e2e-tests` after rust-analyzer analysis:
```sh
   Compiling flipper v4.0.1 (/Users/skyman/Projects/ink-examples/flipper)
 [1/*] Building cargo project
    Finished release [optimized] target(s) in 0.13s
error: custom attribute panicked
 --> e2e_tests.rs:8:1
  |
8 | #[ink_e2e::test]
  | ^^^^^^^^^^^^^^^^
  |
  = help: message: Metadata artifacts not generated
```

**Comment by ascjones** [comment]
This is likely a result of subsequent contract builds not returning the metadata artifact paths, because they were unchanged. I have an in progress fix for this https://github.com/paritytech/cargo-contract/pull/992

**Comment by ascjones** [comment]
Can you try with https://github.com/paritytech/ink/pull/1696 and confirm if it fixes the issue

**Comment by SkymanOne** [comment]
> Can you try with #1696 and confirm if it fixes the issue

I can confirm that the PR fixed the issue!

**Comment by ascjones** [comment]
> > Can you try with #1696 and confirm if it fixes the issue
> 
> I can confirm that the PR fixed the issue!

You know what to do then :heavy_check_mark:
