### ISSUE TITLE
Allow setting block time for off-chain testing

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink#1713]
Escalated from this StackExchange question: https://substrate.stackexchange.com/questions/7034/is-it-possible-to-override-ink-envtest-default-block-time.

## ToDo
- [ ] Add a method `Engine::set_block_time(time: BlockTimestamp)`.

**Comment by CrommVardek** [comment]
I'm working on this, but before submitting my PR, shouldn't the env_access (using Env api) also implement a ink_env::set_block_time() function ?

Sorry if I'm missing something here, first time digging into ink! code base.

**Comment by cmichi** [comment]
@CrommVardek Yes, you're correct.

It's best if you look at the function `advance_block` in `crates/engine/src/test_api.rs` and implement `set_block_time` analog to it. So in your IDE you can look for usages of `advance_block` and add `set_block_time` to all these places as well.

**Comment by CrommVardek** [comment]
PR #1721 opened

**Comment by cmichi** [comment]
Closed with https://github.com/paritytech/ink/pull/1721.
