### ISSUE TITLE
`ink_e2e` excessive recompiling 

### ISSUE THREAD

**Issue by boyswan** [paritytech/ink#1734]
I have a dedicated crate for e2e tests, depending on several contracts. Whenever a test is changed, it rebuilds every single contract in release mode, regardless of whether any contract sources have changed.

This makes writing and running e2e tests a very slow process for when you are using several contracts.

**Comment by ascjones** [comment]
I believe this improves the situation. If you want to try it out you should be able to patch the `ink_e2e` -> `contract-build` dependency to point at my PR branch.

Otherwise you will have to wait for releases of `contract-build` and `ink_e2e`.

**Comment by ascjones** [comment]
I believe this should be fixed now since https://github.com/paritytech/cargo-contract/pull/1079 has been released
