### ISSUE TITLE
Allow multiple constructors

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#180]
ink! smart contracts currently only allow for a single deploy handler (aka constructor).
This is done by implementing the abstract `Deploy` trait like so:

```rust
impl Deploy for MyContract {
    fn deploy(&mut self, ...) {
        // deployment initialization goes here
    }
}
```

Confusingly enough the `Deploy` trait is just virtual and even allows for a variadic `deploy` function implementation. Also it being a `&mut self` function is also confusing for Rust people since there generally a constructor has the form `fn() -> Self`.

A more rustic approach to support constructors in ink! is to allow for multiple constructors.
Constructors should be of the form `fn(...) -> Self` and look syntactically like normal Rust functions.

## Example: Flipper

Below is the Flipper example constract using the proposed syntax.

```rust
contract! {
    /// Simple contract holding a single boolean value.
    ///
    /// Allows to flip and return the boolean value.
    struct Flipper {
        value: storage::Value<bool>,
    }

    impl Flipper {
        /// Initializes the value to the given value.
        pub fn new(init_value: bool) -> Self {
            Self { value: true }
        }

        /// Initializes the value to false.
        pub fn default() -> Self {
            Self::new(false)
        }

        /// Flips the value.
        pub fn flip(&mut self) {
            *self.value = !*self.value;
        }

        /// Returns the value.
        pub fn get(&self) {
            *self.value
        }
    }
}
```

## Open Questions

- How are we going to do the translation from `fn() -> Self` to what we actually do in the background?
- Is the proposed initialization syntax where we can even do `Self { value: false }` even possible generally?
- Looking at a `storage::Vec` or `storage::HashMap`; how would we initialize it naively?
- How can we access the environment? `self.env` (old: `env`)

**Comment by jeluard** [comment]
Naïve question: why use `Self` and not `Flipper` here?

Similarly, why `default` ?

**Comment by Robbepop** [comment]
> Naïve question: why use `Self` and not `Flipper` here?
> 
> Similarly, why `default` ?

Good questions!
`Self` is a Rust keyword and always stands for the implementer. So in this case `Self` is equal to `Flipper` so you could also you `Flipper` instead of `Self` but I wouldn't recommend so to not repeat yourself.
The `default` is just a name I came up with. You can call your constructors whatever you like.

**Comment by jeluard** [comment]
> Self is a Rust keyword and always stands for the implementer

Ah ok!

> The default is just a name I came up with.

Right! I was wondering if there was a specific reason not to use `new` everywhere.

**Comment by Robbepop** [comment]
> Right! I was wondering if there was a specific reason not to use new everywhere.

Rust generally doesn't allow for function overloading (for good reasons!) and so ink! doesn't either. So your constructors have to have a unique name each.

**Comment by jeluard** [comment]
Hmm thanks for clarifying 😅 

So any fn returning `Self` would qualify as a contract constructor?
I guess this is the reason you introduced `#[ink::constructor]` in #184

**Comment by Robbepop** [comment]
> 
> 
> Hmm thanks for clarifying 😅
> 
> So any fn returning `Self` would qualify as a contract constructor?

Ideally yes! However, there are some complications about this exact syntax so we might require another approach that is demonstrated by the `#[ink::constructor]` custom attribute in order to indicate a function being a constructor.

**Comment by Robbepop** [comment]
Implemented in https://github.com/paritytech/ink/pull/191. Closed.
