### ISSUE TITLE
Events `2.0`: manually specify signature topic

### ISSUE THREAD

**Issue by ascjones** [paritytech/ink#1838]
> How about allowing to manually specify the signature topic? If for whatever reason, the exact definition of types can not be used, we can at least allow to specify the topic manually. We are doing that with custom selectors, why not do it with the event signatures?

_Originally posted by @SkymanOne in https://github.com/paritytech/ink/pull/1827#discussion_r1252290352_

How it might look:

```rust
#[derive(ink::Event)]
#[ink(signature_topic = 0x000...]
pub struct Event {}
```
The type of the signature topic should be `[u8; 32]`, although we may need to consider making this configurable to `Environment::Hash`.

**Comment by SkymanOne** [comment]
> How it might look:

I think the best approach is to keep it consistent with custom selectors:
```rust
#[ink(event, signature_topic = 0xDEADBEEF)]
pub struct Event {}
```
or 
```rust
#[ink::event]
#[ink::signature_topic = 0xDEADBEEF]
pub struct Event {}
```
