### ISSUE TITLE
ink! Syntax 2.0

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#184]
This is the tracking and collecting issue for the roadmap to ink! Syntax 2.0.
This represents a major overhaul of the ink! syntax with the goals to more closely match Rust syntax and to allow for better Rust tooling, i.e. `rustfmt`, `clippy` and better out-of-the-box syntax highlighting of ink! Rust code.

## Tracked Issues

- `pub(external) -> pub` for messages: https://github.com/paritytech/ink/issues/179
- new contructor syntax & allow for multiple constructors: https://github.com/paritytech/ink/issues/180
- make `env` accessible through `self`: https://github.com/paritytech/ink/issues/181
- make ink! a custom attribute on inline modules: https://github.com/paritytech/ink/issues/182
- new event syntax: https://github.com/paritytech/ink/issues/183

## Example

The following code demonstrates all of the above changes combined for the simplified (without allowances) Erc20 token contract.

```rust
#[ink::contract(
    types = DefaultSrmlTypes,
    version = [0, 1, 0],
)]
mod erc20 {
    #[ink(storage)]
    struct Erc20 {
        total_supply: storage::Value<Balance>,
        balances: storage::Map<AccountId, Balance>,
    }

    #[ink(event)]
    struct Transfer {
        from: Option<AccountId>,
        to: Option<AccountId>,
        value: Balance,
    }

    impl Erc20 {
        #[ink(constructor)]
        fn new(&mut self, init_value: Balance) {
            self.total_supply.set(init_value);
            self.balances.insert(self.env.caller(), init_value);
        }

        #[ink(message)]
        fn total_supply(&self) -> Balance {
            *self.total_supply
        }

        #[ink(message)]
        fn balance_of(&self, owner: AccountId) -> Balance {
            self.balances.balance_of_or_zero(&owner)
        }

        #[ink(message)]
        fn transfer(&mut self, to: AccountId, value: Balance) -> bool {
            self.transfer_impl(env.caller(), to, value)
        }

        fn balance_of_or_zero(&self, of: &AccountId) -> Balance {
            *self.balances.get(of).unwrap_or(&0)
        }

        fn transfer_impl(&mut self, from: AccountId, to: AccountId, value: Balance) -> bool {
            let balance_from = self.balance_of_or_zero(&from);
            let balance_to = self.balance_of_or_zero(&to);
            if balance_from < value {
                return false
            }
            self.balances.insert(from, balance_from - value);
            self.balances.insert(to, balance_to + value);
            self.env.emit(Transfer {
                from: Some(from),
                to: Some(to),
                value: value
            });
            true
        }
    }
}
```

**Comment by jeluard** [comment]
Nice move! Definitely much better.

Have you considered some syntax that would make the env access explicit? This would reduce the magic factor and would provide IDE completion support.

Also it would be nice to have a more programmatic/extensible syntax to create contracts. Ideally we could have generic library of reusable contract logic that could be easily customised and combined.

**Comment by Robbepop** [comment]
> Also it would be nice to have a more programmatic/extensible syntax to create contracts. Ideally we could have generic library of reusable contract logic that could be easily customised and combined.

For that we ideally have something like dynamic linking for Wasm which currently is unsupported when working with Rust. But it is definitely something we want to have in the future to create composable smart contracts.

**Comment by jeluard** [comment]
> But what exactly have you meant by "programmatic/extensible syntax to create contracts" ?

Some contract can probably be customised via basic types (plain token). Now I would expect some will require more complex customisation like custom logic inserted in pre-defined hooks. Contracts calls might be the way to do that but it sounds a bit fragile?
Now looks like that kind of approach could conflict with how contract code is shared between instances.

> If you have better ideas, please please tell us more! :D

I am afraid I don't atm ! :D

**Comment by Robbepop** [comment]
Implemented in https://github.com/paritytech/ink/pull/191. Closed.
