### ISSUE TITLE
Possible bug ink! integration test (terminate_contract/rustc 1.73.0-nightly)

### ISSUE THREAD

**Issue by gcp-development** [paritytech/ink#1859]
I have a function that [terminates](https://docs.rs/ink_env/latest/ink_env/fn.terminate_contract.html) my contract and it's working as a charm in real live production("cargo contract build --release").

![image](https://github.com/paritytech/ink/assets/76512851/78b88aea-3a3f-4a1b-a724-c72f2292b7c7)

But it gives this error when I run the integration tests ("cargo test").

![image](https://github.com/paritytech/ink/assets/76512851/f18a539c-e522-461f-8dcd-fa4f2e5efc21)

function test

![image](https://github.com/paritytech/ink/assets/76512851/50d18d8e-d7e4-43e4-b201-e94bb33eaf70)

My Cargo.toml
```

[package]
name = "bug"
version = "0.1.0"
authors = ["Hello hello"]
edition = "2021"

[dependencies]
ink = { version = "4.2.1", default-features = false }

scale = { package = "parity-scale-codec", version = "3.6.3", default-features = false, features = ["derive"] }
scale-info = { version = "2.5", default-features = false, features = ["derive"], optional = true }

[dev-dependencies]
ink_e2e = { version = "4.2.1" }

[lib]
path = "./src/lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",
]
ink-as-dependency = []
e2e-tests = []
```
rustup show

![image](https://github.com/paritytech/ink/assets/76512851/0738da1a-faa4-4e94-bd8a-d9b68746356f)

**Comment by SkymanOne** [comment]
Have you tried to compile the contract with the stable toolchain and `cargo-contract` v3.1.0 ?

**Comment by gcp-development** [comment]
yes to both.

![image](https://github.com/paritytech/ink/assets/76512851/f7bb585f-d177-48e2-bfbd-49580804e4b7)

cargo test

![image](https://github.com/paritytech/ink/assets/76512851/5386833c-a243-4ce4-b2bb-933262fa4005)

Cheers,

**Comment by gcp-development** [comment]
For the looks of it this only works with the [assert_contract_termination](https://paritytech.github.io/ink/ink_env/test/fn.assert_contract_termination.html).

Oh well...

```
            let result = move || obj.destructor().unwrap();
            ink::env::test::assert_contract_termination::<ink::env::DefaultEnvironment, _>(
                result,
                beneficiary_account_id,
                10,
            );

```
