### ISSUE TITLE
Get rid of the cargo warning about unused manifest key

### ISSUE THREAD

**Issue by pmikolajczyk41** [paritytech/ink#1929]
When we introduced workspace dependencies (#1835) we had to employ an ugly hack to be able to use `parity-scale-codec` behind an alias in workspace member crates. Just now a fix for the underlying problem has been published: https://github.com/bkchr/proc-macro-crate/pull/39, and thus soon (once `parity-scale-codec` incorporates the new version of [proc-macro-crate](https://github.com/bkchr/proc-macro-crate)) we can get rid of the hack and finally avoid seeing:
```
warning: /home/piomiko/Desktop/ink/crates/e2e/Cargo.toml: unused manifest key: dependencies.scale.package
warning: /home/piomiko/Desktop/ink/crates/storage/Cargo.toml: unused manifest key: dependencies.scale.package
warning: /home/piomiko/Desktop/ink/crates/engine/Cargo.toml: unused manifest key: dependencies.scale.package
warning: /home/piomiko/Desktop/ink/crates/ink/Cargo.toml: unused manifest key: dependencies.scale.package
warning: /home/piomiko/Desktop/ink/crates/storage/traits/Cargo.toml: unused manifest key: dependencies.scale.package
warning: /home/piomiko/Desktop/ink/crates/ink/codegen/Cargo.toml: unused manifest key: dependencies.scale.package
warning: /home/piomiko/Desktop/ink/crates/ink/macro/Cargo.toml: unused manifest key: dependencies.scale.package
warning: /home/piomiko/Desktop/ink/crates/env/Cargo.toml: unused manifest key: dependencies.scale.package
warning: /home/piomiko/Desktop/ink/crates/primitives/Cargo.toml: unused manifest key: dependencies.scale.package
```
during every compilation run.

**Comment by ascjones** [comment]
I've made a PR to update `proc-macro-crate` in `parity-scale-codec`: https://github.com/paritytech/parity-scale-codec/pull/535

**Comment by pmikolajczyk41** [comment]
@ascjones are you able to push next version of `parity-scale-codec`? the newest one doesn't include your contribution

**Comment by ascjones** [comment]
> @ascjones are you able to push next version of `parity-scale-codec`? the newest one doesn't include your contribution

It is slightly tricky since there is apparently a breaking change on `master` which would require a major release. I have asked to see whether we should do that or juts cherry pick my commit into a new patch release.
