### ISSUE TITLE
Implement `storage::BTreeMap`

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#198]
Currently ink! supports only `storage::HashMap` as a map data structure that operates efficiently on the contract's storage.

## Problem

However, due to contracts being transparent to the outside world and thus their whole storage can be inspected from the outside usages of `storage::HashMap` can be attacked. This is done by inspecting the contract's storage with regards to knowledge about the `storage::HashMap` probe algorithm provided by ink!.

Attacking of a hash map data structure generally means that its access times are weakened and no longer expected to be constant (or similar to that) but rather linear to the amount of elements they store.

## storage::BTreeMap

Rust's `BTreeMap` is also a map data structure that doesn't depend on a certain probing of its underlying data structure. Its operations are generally in O(log n) where `n` is the number of elements stored in the `BTreeMap`.

In ink! we could make use of Rust's `BTreeMap` as the new fundamental map data structure and hereby deprecate the current `storage::HashMap` once that lands in `master`.

## Design

As with all ink! data structures the `storage::BTreeMap` shall mimic the public interface of Rust's `BTreeMap` as closely as possible.

**Comment by athei** [comment]
Is the pull request I linked the one that correlates to this issue? If so this should be closed?

**Comment by Robbepop** [comment]
Yeah this should have been closed. Thanks for mentioning.
