### ISSUE TITLE
Encode function/constructor selector as JSON byte array

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#200]
Currently we encode function/constructor selectors in the JSON representation of the contract metadata as `u32`.

This is problematic since selector is basically just 4 bytes and doesn't have a notion of endianess which `u32` has. This means that we effectively should also communicate endianess if we were to continue encoding selectors as `u32` otherwise this will create confusion. Btw.: Current endian is big-endian.

So instead we are going to encode them as simple 4 bytes which they are.

**Comment by ascjones** [comment]
Consider encoding fixed sized byte array as a hex string: e.g. https://github.com/paritytech/substrate/blob/0cfe7438b6cf2a2a3cb1f4ba98a83a17d3fe866c/core/sr-version/src/lib.rs#L176.

https://github.com/polkadot-js/api/blob/master/packages/types/src/json/RuntimeVersion.002.json#L6
