### ISSUE TITLE
Split up `ink_linting` into two `dylint` libraries

### ISSUE THREAD

**Issue by jubnzv** [paritytech/ink#2006]
`ink_linting` should be split up into two `dylint`-based libraries: `ink_linting` and `ink_linting_extra`.

In `cargo-contract`, we require only the essential lints that detect compilation errors in ink!; these are executed each time a contract is built. The lints from `ink_linting_extra` should remain optional, being executed only upon direct user request (e.g. `cargo contract build --extra-lints`). This approach is intended to speed up the build process.

For more context see: https://github.com/paritytech/cargo-contract/pull/1412#discussion_r1407425483

**Comment by deuszx** [comment]
Hi. Are you aware of [scout](https://github.com/CoinFabrik/scout)?
