### ISSUE TITLE
Update ink with cargo install --force --git occurs error[E0432]

### ISSUE THREAD

**Issue by XatMassacrE** [paritytech/ink#213]
use `cargo install --force --git https://github.com/paritytech/ink cargo-contract` to update ink, occurs error.

![screen](https://user-images.githubusercontent.com/7938748/67462641-94859d80-f672-11e9-8630-b972d491479d.jpg)

**Comment by Robbepop** [comment]
We are aware of this issue and a fix has already been implemented (not merged yet):
https://github.com/paritytech/substrate-subxt/pull/29

**Comment by ascjones** [comment]
^^ Just merged this. Please confirm that it fixes the issue.

**Comment by XatMassacrE** [comment]
Yeah, the issue was fixed. Thank you guys. @Robbepop @ascjones
