### ISSUE TITLE
ink_lang2 follow-up: Remove old ink_core::env, ink_lang and ink_model

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#220]
This is a follow-up on the https://github.com/paritytech/ink/pull/191 PR.
Also before we can work on this we have to ensure that we have a proper transition guide up and running for users of `ink_lang`.

The transition guide needs to teach users of `ink_lang` what has changed in comparison to `ink_lang2` and it shall guide users on what they can and should do with the new engine. Also it should provide help to them to easily take the task of transitioning to the new `ink_lang2`.

Note that this task is _NOT_ about renaming `ink_lang2` to `ink_lang`. It will simply be called `ink_lang2` for some time until we come up with a proper naming scheme for it.

## Sub Tasks

- [ ] Remove `ink_core::env` and relink everything that directly depends on it to `ink_core::env2`
- [ ] Remove `ink_model` and everything that directly depends on it
- [ ] Remove `ink_lang`
- [ ] Remove all `ink_lang` examples

**Comment by Robbepop** [comment]
This is implemented in #312 and can be closed once the PR has been merged.

**Comment by Muhammad-Altabba** [comment]
The samples at Substrate Contracts Workshops are not updated yet (https://substrate.dev/substrate-contracts-workshop/)
