### ISSUE TITLE
Safe maths are not correctly applied in compiled contracts

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#226]
For asserting that overflow checks are enabled in Rust compiled smart contracts we include the following lines into `Cargo.toml` files:

```
[profile.release]
overflow-checks = true
```

However, when inspecting the compiled Incrementer example found [here](https://github.com/paritytech/ink/tree/master/examples/lang2/incrementer) we can clearly see that it deterministically underflows and overflows when given certain values. E.g. when the current value of a deployed Incrementer contract is `-42` and we decrease it by `2^32-1` we receive `-41` as result but instead we expect it to trap.

Thanks to @TriplEight for reporting this bug. :tada:

**Comment by SkymanOne** [comment]
Overflow checks have been disabled in #1831 
```
ERROR: Overflow checks must be disabled. Cargo contract makes sure that no unchecked arithmetic is used.
```
