### ISSUE TITLE
Constructor can be called after Initialization

### ISSUE THREAD

**Issue by riusricardo** [paritytech/ink#232]
```
    #[cfg(test)]
    mod tests {
        use super::*;

        #[test]
        fn new_works() {
            let mut contract = Erc20::new(0);
            assert_eq!(contract.total_supply(), 0);
            contract.new(100);
            assert_eq!(contract.total_supply(), 100);
        }
    }
```

**Comment by Robbepop** [comment]
As far as I can see it right now this is going to be implemented by the upcoming PR to improve contract initialization and finalization. We should keep this issue in mind for that.

**Comment by Robbepop** [comment]
Fixed quite recently with the move to the `ink_core::storage2` module and the change to the new ink! constructor syntax where it now resembles normal Rust constructors.
