### ISSUE TITLE
Implement simple API for test environment

### ISSUE THREAD

**Issue by riusricardo** [paritytech/ink#233]
ink! 1.0 had a predefined way of setting the caller on the test env.
`env::test::set_caller::<Types>(AccountId::from([0x0; 32]));`

**Comment by Robbepop** [comment]
The current off-chain test environment of `ink_core::env2` is not capable of setting simple environmental values, e.g. the caller of the next transaction. This should be implemented quickly so that users can implement more elaborate off-chain tests again.

**Comment by Robbepop** [comment]
This is implemented in #312 and can be closed once the PR has been merged.
