### ISSUE TITLE
error: failed to select a version for `ink_lang`.

### ISSUE THREAD

**Issue by syuukawa** [paritytech/ink#241]
1: 
**cargo install --force --git https://github.com/paritytech/ink cargo-contract**
    Updating git repository `https://github.com/paritytech/ink`
  Installing cargo-contract v0.1.2 (https://github.com/paritytech/ink#509cf65f)
    Updating `https://code.aliyun.com/rustcc/crates.io-index.git` index
    Updating git repository `https://github.com/paritytech/substrate/`
    Updating git repository `https://github.com/paritytech/substrate-subxt/`
**error: failed to compile `cargo-contract v0.1.2 (https://github.com/paritytech/ink#509cf65f)`, intermediate artifacts can be found at `/var/folders/cj/xl06nxwj1yl3vbz9fdh3rs4w0000gn/T/cargo-installHO44kI`**

Caused by:
  no matching package named `srml-metadata` found
location searched: https://github.com/paritytech/substrate/
required by package `substrate-subxt v0.1.0 (https://github.com/paritytech/substrate-subxt/?branch=v0.1#ba880d36)`
    ... which is depended on by `cargo-contract v0.1.2 (https://github.com/paritytech/ink#509cf65f)`

2: 
cargo +nightly test
    Updating git repository `https://github.com/paritytech/ink`
    Updating `https://code.aliyun.com/rustcc/crates.io-index.git` index
    Updating git repository `https://github.com/type-metadata/type-metadata.git`
**error: failed to select a version for `ink_lang`.
    ... required by package `flipper v0.1.0 (/Users/zhouhe/blockchain/substrate/record-substrate/substrate-ink/flipper)`**
versions that meet the requirements `*` are: 0.1.0

the package `flipper` depends on `ink_lang`, with features: `generate-api-description` but `ink_lang` does not have these features.

failed to select a version for `ink_lang` which could resolve this conflict

**Comment by Robbepop** [comment]
There has been a major renaming in the Substrate codebase from `srml-*` to `paint-*` and ink! unfortunately hasn't been updated so far. We will update to the new Substrate SRML name as soon as possible.

**Comment by Robbepop** [comment]
I didn't mean to close this issue. @syuukawa can you approve that it now works?
