### ISSUE TITLE
Safe Math Types

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#247]
We found out that enabling `overflow-checks` for an entire binary results in increased Wasm binary size. This is unfortunate since one of the main goals of ink! is to make sure that binary sizes are kept as small as possible.

For this we could try to move to another strategy by only having "safe maths", e.g. overflow checked math for the user provided ink! parts. E.g. only within those parts of ink! that are actually written by users and to not have overflow checks enabled for all the other generated parts that should generally be assumed to behave "correctly".

## Potential Solution

One potential work-loaded solution is to provide some custom primitive integer types such as `ink::{U8, U16, ..., U128, I8, I16, ... I128}` that should be usable just like their primitive counterparts with the only difference of always being overflow-checked.

As their primitive counterparts they should also provide APIs to allow for overflow-enabled arithmetic, e.g. `wrapped_add` etc.

This solution would require lots of work on our side to provide those wrappers and also make it clear through documentation and tutorial efforts for users to make use of them instead of Rust's primitive types. Maybe we might be able to even assert at compile time that users do not use Rust's primitive types if we have good reasons to do so.

**Comment by DemiMarie-parity** [comment]
I wonder if the real problem is missing optimizations in LLVM.

How well would LLVM handle as-infinitely-ranged semantics, as Ada uses?  Especially if we do not ask it to give useful diagnostics, just trap.  My understanding is that this allows for many optimizations.

**Comment by Robbepop** [comment]
I have no clue tbh.

The only thing I currently know is that our Incrementer example is 12kB Wasm binary without overflow-checks and 15kB with overflow checks enabled which is simply put too much overhead.

**Comment by DemiMarie-parity** [comment]
I am still worried about our own code, tbh.

We could also use `.wrapping_*` functions explicitly in our own code, while leaving overflow checks enabled.

**Comment by Robbepop** [comment]
It was decided that adding those safe math types is not a solution we want to further explore.
