### ISSUE TITLE
Can #[ink(message)] functions return Result?

### ISSUE THREAD

**Issue by kigawas** [paritytech/ink#248]
```rust
#[ink(message)]
fn transfer_from(
    &mut self,
    from: AccountId,
    to: AccountId,
    value: Balance,
) -> bool {
    let caller = self.env().caller();
    let allowance = self.allowance_of_or_zero(&from, &caller);
    if allowance < value {
        return false;
    }
    self.allowances.insert((from, caller), allowance - value);
    self.transfer_from_to(from, to, value)
}
```

For code like this, we have to manually return `false` instead of using rust's `?` since we are not using `Result`. Can we use `Result` in `#[ink(message)]`?

**Comment by Robbepop** [comment]
Thank you for the feedback.

Yes, `#[ink(message)]` functions can return anything that implements `scale::Codec` which is true for `Result` and many other types. You can even implement it for your own types. We did not use `Result` here to be closer to the original Erc20 interface. However, since it confuses people we might want to change that.

**Comment by kigawas** [comment]
Thanks for quick reply.
Another question is that what will happen if our contract function panicked? Will it roll back all the changes we made or not? And to what extent? If it rolls back, will it roll back all the changes in other function calls?

```rust
fn contract_f(&mut self) {
    self.var.set(1);  // <- rollback?
    change1(); // <- rollback?
    change2(); // <- if we panic here
    change3();
}
```

**Comment by Robbepop** [comment]
Yes, panicking in a contract results in state reversion and refunding of the remaining gas.

**Comment by kigawas** [comment]
> We did not use `Result` here to be closer to the original Erc20 interface.

Actually since solidity has something like `require`, it's more like `assert!` in Rust. But the example uses `bool` instead, I'm afraid it'll not be transactional sometimes even if you write the code very carefully.

**Comment by kigawas** [comment]
> We did not use `Result` here to be closer to the original Erc20 interface.

Actually since solidity has something like `require`, it's more like `assert!` in Rust. But the example uses `bool` instead, I'm afraid it'll not be atomic sometimes.
