### ISSUE TITLE
How to call existing contracts without creating them first?

### ISSUE THREAD

**Issue by kigawas** [paritytech/ink#249]
```rust
#[ink(constructor)]
fn new(
    &mut self,
    init_value: i32,
    accumulator_code_hash: Hash,
    adder_code_hash: Hash,
    subber_code_hash: Hash,
) {
    self.which.set(Which::Adder);
    let total_balance = self.env().balance();
    let accumulator = Accumulator::new(init_value)
        .value(total_balance / 4)
        .using_code(accumulator_code_hash)
        .create_using(self.env())
        .expect("failed at instantiating the `Accumulator` contract");
    let adder = Adder::new(accumulator.clone())
        .value(total_balance / 4)
        .using_code(adder_code_hash)
        .create_using(self.env())
        .expect("failed at instantiating the `Adder` contract");
    let subber = Subber::new(accumulator.clone())
        .value(total_balance / 4)
        .using_code(subber_code_hash)
        .create_using(self.env())
        .expect("failed at instantiating the `Subber` contract");
    self.accumulator.set(accumulator);
    self.adder.set(adder);
    self.subber.set(subber);
}
```

Here we are creating contracts, but what if I want to call an existing contract without instantiating? In ethereum we just pass the contract address, but not sure how to do this in `ink!`.

**Comment by Robbepop** [comment]
You can see an example how to do it in the Adder and Subber contracts.
They allow to receive an `Accumulator` as parameter. In the case where you cannot have an `Accumulator` type directly you can still have a contract that takes an `AccountId` and then converts that given `AccountId` to the appropriate contract using the `FromAccountId` trait: `self.accumulator.set(Accumulator::from_account_id(account_id));`

**Comment by kigawas** [comment]
Thanks, and how can I write test for this? It complains:
```
error[E0599]: no method named `test` found for type `ink_core::env2::call::create::CreateBuilder<ink_core::env2::test::accessor::TestEnv<ink_core::env2::types::DefaultSrmlTypes>, mycontract::mycontract::__ink_private::__ink_cross_calling::StorageAsDependency, ink_core::env2::call::utils::seal::Sealed, ink_core::env2::call::create::state::CodeHashUnassigned>` in the current scope
```

**Comment by Robbepop** [comment]
What exactly do you want to test? Can you show me your test code please?

**Comment by kigawas** [comment]
```rust

use mycontract::MyContract;

#[ink::contract(version = "0.1.0")]
mod Caller {
    #[ink(storage)]
    struct Caller {
        callee: storage::Value<MyContract>,
    }

    impl Caller {
        #[ink(constructor)]
        fn new(&mut self, callee: MyContract) {
            self.callee.set(callee);
        }

        #[ink(message)]
        fn get(&self) -> u32 {
            self.callee.test()
        }
    }

    #[cfg(test)]
    mod tests {
        use super::*;

        #[test]
        fn it_works() {
            let mut callee = MyContract::new(1);
            callee.test(); // should return 1
            // let mut caller = Caller::new(callee);
        }
    }
}
```

**Comment by kigawas** [comment]
```
  --> lib.rs:39:19
   |
39 |             callee.test();
   |                    ^^^^ method not found in `ink_core::env2::call::create::CreateBuilder<ink_core::env2::test::accessor::TestEnv<ink_core::env2::types::DefaultSrmlTypes>, mycontract::mycontract::__ink_private::__ink_cross_calling::StorageAsDependency, ink_core::env2::call::utils::seal::Sealed, ink_core::env2::call::create::state::CodeHashUnassigned>`
```

**Comment by Robbepop** [comment]
Have you defined the `test` in your `MyContract` type so the Rust compiler can find one? You might want to add it with with `fn test(&self) { /* your test code */ }` in the `impl` block of your `MyContract` type. However, I am not sure: What is the purpose of `test`? Normally you test your contracts in isolation. E.g. `Callee` tests itself, `MyContract` tests itself etc.

There are plans to implement this but right now it is not possible with ink! to cross-contract call properly in off-chain test code. We want to implement this but it isn't done yet.

Also if you have a typed `callee: storage::Value<MyContract>` then this requires you to somehow instantiate the `MyContract` in some other (or this) contract because otherwise it is currently impossible to find out the exact type of the contract. So what you really want in the case you mentioned above is:

```rust
#[ink::contract(version = "0.1.0")]
mod Caller {
    #[ink(storage)]
    struct Caller {
        callee: storage::Value<MyContract>,
    }

    impl Caller {
        #[ink(constructor)]
        fn new(&mut self, callee: AccountId) {
            self.callee.set(FromAccountId::from_account_id(callee));
        }

        #[ink(message)]
        fn get(&self) -> u32 {
            self.callee.test()
        }
    }
}
```

**Comment by kigawas** [comment]
Well `test` just return the value initialized in MyContract's `new`

**Comment by Robbepop** [comment]
As I have said cross-contract calling does not yet work properly with the off-chain test environment. you can for now only test this functionality on-chain using a `--dev` node for example. We are going to add this feature in the future.

**Comment by kigawas** [comment]
@Robbepop 
I found it's complex to play with rust workspaces, it's better to seperate them.

```rust
// callee lib.rs
#[cfg(feature = "ink-as-dependency")]
pub use crate::mycontract::MyContract;
```
```toml
# caller Cargo.toml
mycontract = { path = "../mycontract", default-features = false, features = ["ink-as-dependency"] }
```
Is this usage idiomatic?

**Comment by Robbepop** [comment]
> @Robbepop
> I found it's complex to play with rust workspaces, it's better to seperate them.
> 
> ```rust
> // callee lib.rs
> #[cfg(feature = "ink-as-dependency")]
> pub use crate::mycontract::MyContract;
> ```
> 
> ```toml
> # caller Cargo.toml
> mycontract = { path = "../mycontract", default-features = false, features = ["ink-as-dependency"] }
> ```
> 
> Is this usage idiomatic?

Generally I'd recommend for now to keep dependent contracts in their own crates and not re-export them from within your crate which is what `pub use crate::mycontract::MyContract;` looks to me - I might also just be confused. But in theory you shouldn't need such a line of code.

Depending on a contract and setting its `ink-as-dependency` crate feature is idiomatic for ink! contracts at the moment, yes.

**Comment by kigawas** [comment]
If I'm not using `pub use`, how do I use the contract from outside :confused: ?

**Comment by Robbepop** [comment]
> If I'm not using `pub use`, how do I use the contract from outside confused ?

Ahhhh, sorry. Now I got it. Yes, you are right that's perfectly fine. Sorry.
