### ISSUE TITLE
How to self-destruct contract?

### ISSUE THREAD

**Issue by kigawas** [paritytech/ink#252]
Say I want to transfer all the remaining balances to the creator of the contract's account and destruct the contract. Any reference for this?

**Comment by Robbepop** [comment]
We might add an example contract for this soon.

**Comment by kigawas** [comment]
Can you list some code I can refer? Tried searching "destruct" in the code, but found nothing

**Comment by Robbepop** [comment]
Example code for this does not exist and I am even wondering if we forgot to provide the underlying API to actually simply transfer value back from contract to user.

**Comment by Robbepop** [comment]
https://github.com/paritytech/ink/issues/260

**Comment by Robbepop** [comment]
Closed since respective issues have been created.
