### ISSUE TITLE
erc20 token example transferring bug

### ISSUE THREAD

**Issue by kigawas** [paritytech/ink#254]
![image](https://user-images.githubusercontent.com/4182346/69224381-c7fb0f80-0bbf-11ea-98b2-38f5276a00fc.png)

Transferring to yourself `x` balance will actually add `x` balance!
```rust
            let to_balance = self.balance_of_or_zero(&to);  // <- A
            self.balances.insert(from.clone(), from_balance - value); // <-B
            self.balances.insert(to.clone(), to_balance + value); // <-C
```
Should be B A C

**Comment by Robbepop** [comment]
I think it is far simpler to add a check to prevent sending money to yourself.
```rust
if sender == owner {
    return false;
}
```

**Comment by kigawas** [comment]
> Good catch!
> 
> I think it is far simpler to add a check to prevent sending money to yourself.
> 
> 
> ```rust
> if sender == owner {
>     return false;
> }
> ```

It may look simpler, but doesn't really resolve the problem - the order of updating balance.

Actually I'd like to have something like:
```rust
self.balances.update(from.clone(), |balance| { *balance -= value; });
self.balances.update(to.clone(), |balance| { *balance += value; });
```

**Comment by Robbepop** [comment]
Instead of `self.balances.update` you might want to use the existing `self.balances.mutate_with` function which does exactly what you need from what I can tell.

**Comment by kigawas** [comment]
https://doc.rust-lang.org/std/collections/hash_map/enum.Entry.html#method.and_modify

Maybe we need something like `and_modify` and `or_insert` to provide more ergonomics.

```rust
assert(from_balance >= value);
self.balances.entry(&from).and_modify(|balance| { *balance -= value }).or_insert(0);
self.balances.entry(&to).and_modify(|balance| { *balance += value }).or_insert(0);
```
This is almost semantically equivalent (if we ignore safe math) to solidity's
```solidity
_balances[sender] = _balances[sender].sub(amount, "ERC20: transfer amount exceeds balance");
_balances[recipient] = _balances[recipient].add(amount);
```
