### ISSUE TITLE
Add --manifest-path option to cargo-contract

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#258]
The `cargo-contract` plugin (ink! CLI) currently lacks support for setting a `manifest-path` as CLI parameter to make it usable on contracts without requiring the caller to have their `cwd` in the contract's root directory. The `manifest-path` should work the same as the one supported by `Cargo` and should be provided for

- `cargo contract build`
- `cargo contract generate-metadata`
- `cargo contract deploy`

**Comment by ascjones** [comment]
Moved to https://github.com/paritytech/cargo-contract/issues/3
