### ISSUE TITLE
Update ink! CLI

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#267]
Running `cargo outdated` on the ink! codebase yields that mainly ink! CLI is using some outdated dependencies.

```
cargo-contract
================
Name              Project  Compat  Latest  Kind    Platform
----              -------  ------  ------  ----    --------
futures           0.1.29   ---     0.3.1   Normal  ---
idna              0.1.5    ---     0.2.0   Normal  ---
percent-encoding  1.0.1    ---     2.1.0   Normal  ---
url               1.7.2    ---     2.1.0   Normal  ---
```

We could update `futures` to `0.3.1` and by this introduce the new `async` and `await` stuff from stable Rust. We should generally just update the others if simple enough.

**Comment by ascjones** [comment]
rel: https://github.com/paritytech/substrate-subxt/issues/36

**Comment by ascjones** [comment]
Moved to https://github.com/paritytech/cargo-contract/issues/2
