### ISSUE TITLE
Unexpected argument generate-metadata

### ISSUE THREAD

**Issue by damianoazzolini** [paritytech/ink#281]
I'm following the flipper contract guide on the website. However, when i execute the command `cargo contract generate-metadata`, it returns an error:
```
.../Desktop/flipper$ cargo contract generate-metadata
error: Found argument 'generate-metadata' which wasn't expected, or isn't valid in this context

USAGE:
    cargo contract <SUBCOMMAND>

For more information try --help
```

**Comment by Robbepop** [comment]
Looks like your cargo-contract version is not up to date. Have you checked?

**Comment by damianoazzolini** [comment]
Indeed, I updated to 0.2.0 and now the option is present
