### ISSUE TITLE
Add automated docs generation to GitLab CI

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#288]
Currently ink! CI does not perform any checks on `docs` nor does it automatically generate or upload updated code docs from the source code to a dedicated GitHub or GitLab branch.

With GitHub pages, Rust's `cargo doc` and the `ghp-import` tool it is easy and simple to update a crate's reference docs and deploy it to a branch.

Generally ink! reference docs are highly outdated due to missing automation.
We want to update our reference docs for every successful push to ink! `master`.

As a reference https://github.com/paritytech/wasmi already deployed such a method to update its docs automatically.

**Comment by athei** [comment]
The documentation should be generated with the `ink-generate-abi` feature enabled. The current documentation is not which makes all metadata related traits invisible.

**Comment by TriplEight** [comment]
So right now it's generated with `time cargo doc --release --no-deps --all --verbose`.
So I should add `--features ink-generate-abi` but it won't work in the root of the worspace, so where exactly should I use this feature?
Also: it would probably make sense to change `--all` with `--workspace` (but it won't help running `--features`)

**Comment by athei** [comment]
Supplying features to a workspace is not supported. If you think about it it does not make that much sense.

To have about the same output + `type-metadata` run the follwing command from the `ink/` sub directory:

`cargo doc --no-deps --all-features -p type-metadata -p ink_abi -p ink_abi_derive  -p ink_core -p ink_core_derive -p ink_primitives -p ink_prelude -p ink_lang -p ink_lang_macro`
