### ISSUE TITLE
Contract metadata format 

### ISSUE THREAD

**Issue by ascjones** [paritytech/ink#294]
@jacogr is not happy with the current contract metadata format - it requires a hand-rolled parser which is difficult to maintain. 

I will add some proposed metadata formats to this issue once I come up with them. Also we will most likely need to make changes in https://github.com/type-metadata/type-metadata. In the meantime I will collect some raw thoughts from Riot chat here:

------------------
This brings me to my next point, after looking at all the examples - I would appreciate it if we can actually move the ABI JSON also to something standard that aligns with the way we actually do things in Substrate. As it stands Keith had to roll a parser by hand since he couldn't use any of the "define the structure, and it parse" code that we use everywhere.

This means that when we eventually get it in metadata, all that work is completely wasted an has to be re-done. (Instead of having well-defined structures that can parse byte streams, JSON, etc.)

This means -

- no Rust-like namings, stick to JSON standard, e.g. `return_type:` ... va `returnType:` ...
- build up proper structures, so they can be parsed as such, e.g. `range.offset`: ... vs `range: { offset: ... }`
- this is not a `[u8; 4]` output, `["0x5E","0xBD","0x88","0xD6"]`, this is `0x5edb88d6`
Everything being non-aligned-with-Substrate in this world is just creating untold pain. With the simple things above in place, you can just feed the createType a definition and magically full-parsed objects appear. Currently there are special types defined, a hand-rolled parser for each type of field, special conversions for e.g. the selectors, etc. etc.

----------------
I am telling you that the ABI JSON as it stands,

- encodes data incorrectly
- has like "range.offset", "range.len" next to each other (instead of enums)
- cannot be parsed with anything that we use to parse the normal SCALE . and RPC stuff
So I want a proper format that I can define in terms of structures (enums, structs) that I can just . parse "magiclally".

**Comment by jacogr** [comment]
Sorry for being grumbly ;)

**Comment by ascjones** [comment]
See #296 for example of proposed new metadata format. Please give feedback there.
