### ISSUE TITLE
Constraining `invoke_runtime` type

### ISSUE THREAD

**Issue by ascjones** [paritytech/ink#297]
In `env2` the function `dispatch_call` was renamed `invoke_runtime`. Previously the type of the call was constrained to `EnvTypes::Call` to ensure that only valid calls could be dispatched:

https://github.com/paritytech/ink/blob/8165b244cec50d6dbf83a147c13c6d863154caf3/model/src/exec_env.rs#L195-L200

The new `invoke_runtime` allows any type which implements `Encode`:

https://github.com/paritytech/ink/blob/b7ca7525563e576ebef41801174c413d43166dc1/core/src/env2/srml/impls.rs#L352-L360

Should we consider replicating the old api whereby the type of the `Call` is restricted? This will guarantee that the `Call` is decodable by the runtime (assuming the types are compatible). 

This was discovered by @liuchengxu: https://github.com/paritytech/ink-types-node-runtime/pull/7.

**Comment by jaybutera** [comment]
I second this, as someone new to the code base it would also make it clear what type needs to be passed in.

Which I assume is now `CallData` https://github.com/paritytech/ink/blob/master/core/src/env2/call/utils.rs#L74

**Comment by Robbepop** [comment]
> I second this, as someone new to the code base it would also make it clear what type needs to be passed in.
> 
> Which I assume is now `CallData` https://github.com/paritytech/ink/blob/master/core/src/env2/call/utils.rs#L74

The `CallData` type is not correct in this context.
We currently do not have a `Call` type in the `EnvTypes` of `env2` in ink! so we'd have to recreate that one.

**Comment by Robbepop** [comment]
This is partially implemented in https://github.com/paritytech/ink/pull/312 and can be closed once the PR has been merged.
