### ISSUE TITLE
Add `invoke_runtime` to EnvAccessMut wrapper

### ISSUE THREAD

**Issue by jaybutera** [paritytech/ink#301]
#### Problem
`invoke_runtime` is a function of the Env trait [env2/traits.rs#L150](https://github.com/paritytech/ink/blob/master/core/src/env2/traits.rs#L150)

But is not implemented by its wrapper trait, `EnvAccessMut` [env2/env_access/mutable.rs#L156](https://github.com/paritytech/ink/blob/master/core/src/env2/env_access/mutable.rs#L156) that is accessible from an ink contract.

#### Solution
In order to call this method from a contract, the `invoke_runtime` definition should be added to the`EnvAccessMut` trait.

#### More Context
Other methods like `invoke_contract` in `Env` are implemented in both traits. On the same note, the env2 `CallBuilder` code [specifically mentions](https://github.com/paritytech/ink/blob/master/core/src/env2/call/builder.rs#L115) its use for calling other contracts, but doesn't mention invoking the runtime. It is somewhat unclear what type should be passed into `invoke_runtime` since the only constraint is that the input parameter implements `Encode`. Maybe this can be constrained to an `EnvTypes::Call` in the `invoke_runtime` definition like it is in [env/api.rs#L84](https://github.com/paritytech/ink/blob/master/core/src/env/api.rs#L84)
[Related issue] #297

**Comment by jaybutera** [comment]
Ok it looks like this feature has already been implemented elsewhere but not yet submitted in a PR https://github.com/paritytech/ink-types-node-runtime/pull/7

**Comment by Robbepop** [comment]
This is partially implemented in https://github.com/paritytech/ink/pull/312 and can be closed once the PR has been merged.
