### ISSUE TITLE
Issues when calling methods inside a simple smart contract

### ISSUE THREAD

**Issue by Muhammad-Altabba** [paritytech/ink#304]
Hello,
I am following the "ink! Smart Contracts Tutorial". I am at the step "Calling Your Contract": https://substrate.dev/substrate-contracts-workshop/#/0/calling-your-contract

Calling the `get()` method results in empty brackets as in this snapshot:
![image](https://user-images.githubusercontent.com/24407834/71782420-eaaf7f00-2fd9-11ea-9091-99555bd9d07c.png)
Note: There is no error in the Console when calling `get()`.

And when calling `flip()`, there are errors with no value returned!
![image](https://user-images.githubusercontent.com/24407834/71782511-f9e2fc80-2fda-11ea-8be5-63310cb2b8b8.png)

![image](https://user-images.githubusercontent.com/24407834/71782506-e172e200-2fda-11ea-9ce5-5da3cb09681d.png)

> substrate --version
> substrate 2.0.0-5dece712a-x86_64-linux-gnu

**Comment by jacogr** [comment]
"Payment" refers to no funds available to pay for the tx fees. You need to make sure your calling account ha sufficient funds available.

**Comment by Muhammad-Altabba** [comment]
As I mentioned, even calling `get()` that is read-only, has issues.
Additionally, the accout has more than 2 million of coins.
What do you suggest?
Thanks,

**Comment by Robbepop** [comment]
It could very well be that the current combination of Substrate, Polkadot JS and ink! do not work. We are currently investigating the many issues with this and are implementing routines in order to stabilize this process in the future. Can you please tell us which exact versions of the mentioned applications you are using?

**Comment by Muhammad-Altabba** [comment]
This is great!
Thanks for that,

The Substrate version is as mentioned:

> substrate --version
> substrate 2.0.0-5dece712a-x86_64-linux-gnu

The Polkadot JS is the running version of the public stie (as per the screen shots)

How to get the `ink` version?
(I will provide it tomorrow morning)

**Comment by Muhammad-Altabba** [comment]
Hello,
Do you still need the `ink` version? Or you are able to reproduce the issue?
If you still need the `ink` version, please tell me how to get it for you.
Many thanks,

**Comment by Muhammad-Altabba** [comment]
Just to be sure that the issue is not related to low balance, I ran `substrate purge-chain --dev`, then `substrate --dev`. And then I deployed the same `flipper` smart contract and got the same error:

![image](https://user-images.githubusercontent.com/24407834/72223896-359a3b00-3574-11ea-88e8-e1f683b06d16.png)

And here is how much Alice has:
![image](https://user-images.githubusercontent.com/24407834/72223931-932e8780-3574-11ea-8ce9-8c64f5eb9231.png)

Note that also `get()` has an issue and it did not succeed (shown in the screenshot).

**Comment by Muhammad-Altabba** [comment]
So it turned out there are 3 issues not one:
 - Calling `get()` does not return any value.
 - Calling `flip()` from an account with sufficient fund gives an error that there is no enough balance.
 - Calling `flip()` from Alice account gives a different error.

Do you like me to have 3 issues opened? Or this will be closed soon?

Thanks,

**Comment by qalqi** [comment]
I had a similar issue. I figured out my contract went tombstone. You can figure out by filling your contract address in `contractAddress ` at https://polkadot.js.org/apps/#/js

```javascript
let contractAddress = 'xxx';
 
const creationFee = await api.consts.balances.creationFee;
const transferFee= await api.consts.balances.transferFee;
const contractInfoOf = await api.query.contracts.contractInfoOf(contractAddress );

console.log( 'creationFee: ' + creationFee  );
console.log( 'transferFee: ' + transferFee);
console.log('contractInfoOf ' + contractAddress + ' : ' + contractInfoOf );

**Comment by Robbepop** [comment]
> I had a similar issue. I figured out my contract went tombstone. You can figure out by filling your contract address in `contractAddress ` at https://polkadot.js.org/apps/#/js
> 
> ```js
> let contractAddress = 'xxx';
>  
> const creationFee = await api.consts.balances.creationFee;
> const transferFee= await api.consts.balances.transferFee;
> const contractInfoOf = await api.query.contracts.contractInfoOf(contractAddress );
> 
> console.log( 'creationFee: ' + creationFee  );
> console.log( 'transferFee: ' + transferFee);
> console.log('contractInfoOf ' + contractAddress + ' : ' + contractInfoOf );
> ```
> 
> You should get
> 
> ```
> creationFee: 1000000000000
> transferFee: 1000000000000
> contractInfoOf xxx: {"Alive":{"trieId":"xxx","storageSize":xx,"codeHash":"xx","rentAllowance":"xx","deductBlock":xx,"lastWrite":xx}}
> ```

If this is true we should definitely provide better user experience in regard to smart contracts turning tombstones. It should definitely be an event that a user cannot oversee easily.
We thank you very much all the bug reports and we hope we can fix all those issues soon.

Better not to file three new bugs. Let's keep it in this thread until we have certainty in which component (Substrate, Polkadot JS Apps, ink! or ink! CLI) it is actually happening.

**Comment by qalqi** [comment]
Yeah, an icon to indicate if a contract is a tombstone or alive would be great along with showing tombstone fees during the contract creation

**Comment by Muhammad-Altabba** [comment]
Thanks @Robbepop 
And are you able to reproduce the issues?
If not, have a fresh Virtual Machine and follow the mentioned tutorial. If you are still not able to reproduce it then, I can show it to you on my machine in a video call.

**Comment by Muhammad-Altabba** [comment]
The contact was turning into `tombstone` immediately after creation. This can be prevented when rasing the default `endowment` at deployment.

The tutorial seems to be updated now and at the step when deploying the smart contract (https://substrate.dev/substrate-contracts-workshop/#/0/deploying-your-contract) it contains:

> To instantiate our contract we just need to give this contract account an **_endowment_** of 10,000,000 and again set the **_maximum gas allowed_** to 500,000 units. 


So like what @qalqi said, I also suggest:

> Yeah, an icon to indicate if a contract is a tombstone or alive would be great along with showing tombstone fees during the contract creation

Additionally, at deployment time the default value should be a fair-enough value for `endowment` specific for the contract that is about to be deployed.

**Comment by Muhammad-Altabba** [comment]
Should I close this issue or should I keep it for the suggestions? Or you will manage to open issues for those suggestions in the concerned repositories?
Thanks,

**Comment by Robbepop** [comment]
Thank you for your reports.
I will close the issue once we have resolved some suggestions and improvements to the current situation.

**Comment by Robbepop** [comment]
Note that we quite recently added support for emitting events upon contract restoration and eviction processes. So in theory Polkadot JS Apps could utilize this information in order to improve this transparency situation for users.

**Comment by kwingram25** [comment]
Probably not a lot, there are at least some events that already trigger a notice so it has been done before

**Comment by Robbepop** [comment]
I think this issue is better kept at Polkadot JS Apps. Will move.

**Comment by Muhammad-Altabba** [comment]
Actually, it is not only the UI that needs improvements. It is very essentials also to have a very clear error message. All error messages have to be reviewed. Something like "Extrinsic Error" does not help at all.
The other very important point is also the ease of tracing errors and reading the detailed logs. Having this issue as an example, if we could see clear indicated logs, we could figure out the issue very fast. (For example, this question https://stackoverflow.com/questions/57377600/why-showing-a-error-messag-system-extrinsicfailed-while-calling-a-smart-contra waited 5 months till the first answer came!)

**Comment by Robbepop** [comment]
I think this issue can be closed since its related problems seems to be outdated and also they are more of a Polkadot JS side problem atm.
