### ISSUE TITLE
Missing iteration interface for storage::HashMap

### ISSUE THREAD

**Issue by bedeho** [paritytech/ink#317]
For normal runtime modules, `decl_storage` offers the `linked_map` variant, which allows iteration of mappings. The `HashMap` collection currently offered has no such iteration.
Importantly, `Vec` and `BTreeMap` style storage containers are not a good alternative in all contexts, because they do not have sublinear running time on insertion/deletion, and no light client proofs for individual elements or mappings, respectively.

**Comment by Robbepop** [comment]
This is indirectly superseeded by https://github.com/paritytech/ink/issues/347 since making the hash map aware of its keys will also allow iteration. Closed.
