### ISSUE TITLE
Fix runtime storage example

### ISSUE THREAD

**Issue by ascjones** [paritytech/ink#325]
It was just reported on Riot that it is not working. A cursory glance suggests it's caused by a change in substrate to how balances are stored:

https://github.com/paritytech/ink/blob/321fe03a5c1cfc5b71e4d41ea9f09109d534cfee/examples/runtime-storage/src/lib.rs#L49

I believe the way to get the free balance now is via "System Account": https://github.com/paritytech/substrate/blob/master/frame/system/src/lib.rs#L299.

This will require duplicating the `AccountData` struct https://github.com/paritytech/substrate/blob/5a2824d9b20f151466d92f20c767141c30a35b65/frame/balances/src/lib.rs#L307

**Comment by Robbepop** [comment]
triage @ascjones this has been fixed, right?

**Comment by ascjones** [comment]
Nope it still needs fixing
