### ISSUE TITLE
Rustdoc "landing" crate for contract developers

### ISSUE THREAD

**Issue by athei** [paritytech/ink#328]
Currently, when looking at the rustdoc of ink! it is not clear what are the responsibilities of each crate. When consulting the rustdocs I was often in the situation that I did not know which crate or types should be used in a contract and which are used internally.

I propose that we have a single crate (`ink_api` already sounds like such a crate) that contains documentation for the contract developer and reexports everything that is needed for contract development. The crate itself does not contain code. By doing this we make it easy for new contract developers to find everything they need.

**Comment by Robbepop** [comment]
Note that something like this is already being planned, however, there are some problems and potential bugs with macro re-exports and macro codegen that this would cause. So we did not touch it yet since there are much more critical tasks atm.

**Comment by athei** [comment]
You can prioritize how you see fit. I did not find an issue for that.  Feel free too close of this is an duplicate.

**Comment by HCastano** [comment]
@Robbepop @athei I'm not quite sure what the state of this is (I don't know what the docs looked like a year ago and they're fine to me now). Is this still valid?

**Comment by Robbepop** [comment]
We now have ink! docs which is our public documentation portal for ink! and the most significant change for developer focused documentation. However, it is not an API documentation per se. So we are still in need of this proposed `ink_api` but it is still a problem to implement properly. It is the long vision for ink! to have this.

**Comment by cmichi** [comment]
>So we are still in need of this proposed `ink_api` but it is still a problem to implement properly. It is the long vision for ink! to have this.

@Robbepop Could you create an issue for this? I'd also be interested to know which problems are preventing implementing this currently.

**Comment by SkymanOne** [comment]
Closing as we have https://github.com/paritytech/ink/blob/master/ARCHITECTURE.md doc and use.ink doc portal
