### ISSUE TITLE
error: already initialized off-chain environment when using run_test

### ISSUE THREAD

**Issue by athei** [paritytech/ink#331]
When trying to run a test with `ink_core::env::test::run_test` I get the following error:

`thread 'multisig_plain::tests::construction_works' panicked at 'encountered already initialized off-chain environment: OffChain(TypedEncoded(AlreadyInitialized { initialized_id: TypeId { t: 596591791173715099 }, new_id: TypeId { t: 596591791173715099 } }))', lib.rs:46:1`

This example is taken from this [PR](https://github.com/paritytech/ink/pull/327).

```
mod tests {
        use super::*;
        use ink_core::env::test;
        type Accounts = test::DefaultAccounts<MyEnv>;

        #[test]
        fn construction_works() {
            test::run_test(|accounts: Accounts| {
                MultisigPlain::new(
                    ink_prelude::vec![accounts.alice, accounts.bob, accounts.eve],
                    2,
                );
                Ok(())
            })
            .unwrap();
        }
    }
}
```

**Comment by Robbepop** [comment]
The problem is that `ink_lang_macro` ingeniously already initializes the off-chain environment in `test-env` mode when a new contract instance is being created ...

**Comment by athei** [comment]
So we are already where we want to be and `test::run_test` is not needed after all?

**Comment by Robbepop** [comment]
I am not sure if we actually want to initialize the off-chain environment in `ink_lang_macro`. I guess the best approach could be to craft yet another small proc macro `#[ink(test)]` to do the job.

**Comment by athei** [comment]
I agree. It seems to be a very surprising thing if even you are surprised.

**Comment by master-davidlee** [comment]
i've meet the same problem in the ink tutorial  the "flipper" contract  when i run test just like the tutorial says  
    #[cfg(test)]
    mod tests {
        /// Imports all the definitions from the outer scope so we can use them here.
        use super::*;

        /// We test if the default constructor does its job.
        #[test]
        fn default_works() {
            // Note that even though we defined our `#[ink(constructor)]`
            // above as `&mut self` functions that return nothing we can call
            // them in test code as if they were normal Rust constructors
            // that take no `self` argument but return `Self`.
            let flipper = Flipper::default();
            assert_eq!(flipper.get(), false);
        }

        /// We test a simple use case of our contract.
        #[test]
        fn it_works() {
            let mut flipper = Flipper::new(false);
            assert_eq!(flipper.get(), false);
            flipper.flip();
            assert_eq!(flipper.get(), true);
        }
    }
}
so  i have to run just one test one time

**Comment by Robbepop** [comment]
> so i have to run just one test one time

what do you mean by this?
normally the off-chain test environment is thread local upon testing so tests should not interfere with each other.

**Comment by master-davidlee** [comment]
https://substrate.dev/substrate-contracts-workshop/#/0/creating-an-ink-project
this tutorial says run two test one time  but i get an error 
![image](https://user-images.githubusercontent.com/49427668/78002750-3c15a300-736a-11ea-82d5-9132b2c4f09f.png)
like this  I don't know why

**Comment by riusricardo** [comment]
@master-davidlee what version of cargo-contract are you using?
```
cargo contract --version
```

**Comment by master-davidlee** [comment]
0.5.0
![image](https://user-images.githubusercontent.com/49427668/78032815-28813100-7398-11ea-9e4a-3cfd1a4a6077.png)

**Comment by master-davidlee** [comment]
and in the same tutorial , when i upload wasm somenthing wrong occurs extrinsicfailed    but transfer extrinsicsucced

**Comment by Robbepop** [comment]
Please update `cargo-contract` to `0.6` via crates.io:
`cargo install --force cargo-contract`

**Comment by master-davidlee** [comment]
![image](https://user-images.githubusercontent.com/49427668/78040487-10aeaa80-73a2-11ea-9f87-9de68e0e3842.png)
i have update to 0.6   still failed i don't know why

**Comment by master-davidlee** [comment]
but update to 0.6 i can run two test

**Comment by Robbepop** [comment]
Please also update your Substrate version to `2.0.0-alpha.5`.

**Comment by master-davidlee** [comment]
OK that’s done

**Comment by master-davidlee** [comment]
Ops the error occurs again I want to run three test in one time but just the first passed 
![A76BBABE-B87D-4492-BD44-8EDBFEF82D49](https://user-images.githubusercontent.com/49427668/78234934-77e76e80-750a-11ea-9321-cf0b1a859ede.png)

**Comment by Robbepop** [comment]
Can you show me the `Cargo.toml` of your smart contract please?

**Comment by master-davidlee** [comment]
Yeah I don’t know which one you mean so I put both 
![86CB4472-8993-4A73-BCC4-3ED194AF1D2E](https://user-images.githubusercontent.com/49427668/78239136-f1ce2680-750f-11ea-92fd-85339a47cca4.png)
The first one is 
![D09B4B1E-055E-40F8-8B50-94FEFAD11092](https://user-images.githubusercontent.com/49427668/78239221-09a5aa80-7510-11ea-9ffe-9adbbe16b356.png)
The second is 
![8FB1B98B-4447-4EF8-A12C-2ABDD377DA87](https://user-images.githubusercontent.com/49427668/78239260-132f1280-7510-11ea-9eed-ed72f74a5109.png)
![Uploading DECD3C0E-C603-45F2-9E8F-FC966D101ABE.png…]()

**Comment by master-davidlee** [comment]
![CBC89EEB-D64E-484B-8AFE-1B959AFE03C0](https://user-images.githubusercontent.com/49427668/78239357-31950e00-7510-11ea-9478-50586ce42560.png)

**Comment by master-davidlee** [comment]
One of the The second .toml gone so I upload again 
![6E473BA3-3F1E-4988-9198-ACF83D549DAA](https://user-images.githubusercontent.com/49427668/78239522-5db08f00-7510-11ea-8023-a0c76610d4fb.png)

**Comment by Robbepop** [comment]
Why are you using your own ink! fork instead of the official one?
Does it solve the problem if you switch to the `paritytech` ink! back?

**Comment by master-davidlee** [comment]
Because the speed update from github is too slow so I import the whole official repository to the gitee which just like the github but I can update faster than github

**Comment by Robbepop** [comment]
But can you please still try out if it fixes your problem? I have

**Comment by master-davidlee** [comment]
Ok I will try thanks bro


| |
李懿
|
|
邮箱：18920396056@163.com
|

签名由 网易邮箱大师 定制

On 04/02/2020 19:08, Hero Bird wrote:

But can you please still try out if it fixes your problem? I have

**Comment by master-davidlee** [comment]
Ok I will try thanks bro

**Comment by master-davidlee** [comment]
i change back to the official repo and running test ,got the same result  1 passed 2 failed  because the same error 
![image](https://user-images.githubusercontent.com/49427668/78252300-36b08800-7525-11ea-9e2e-4e833b819752.png)

**Comment by Robbepop** [comment]
Have you changed the test codes? If so please paste them here. More information -> more help.

**Comment by master-davidlee** [comment]
no i just copy from the tutorial and running  it 
`
#![cfg_attr(not(feature = "std"), no_std)]

use ink_lang as ink;

#[ink::contract(version = "0.1.0")]
mod incrementer {
    use ink_core::storage;

    #[ink(storage)]
    struct Incrementer {
        // Storage Declaration
        value: storage::Value<i32>,
        my_value: storage::HashMap<AccountId,u64>,
    }

    impl Incrementer {
        #[ink(constructor)]
        fn new(&mut self, init_value: i32) {
            // Contract Constructor
            self.value.set(init_value);
        }

        #[ink(constructor)]
        fn default(& mut self){
            self.new(0);
        }

        #[ink(message)]
        fn get(&self) -> i32{
            // Contract Message
            *self.value
        }

        #[ink(message)]
        fn inc(&mut self, by : i32){
            *self.value += by
        }

        #[ink(message)]
        fn get_mine(&self) -> u64{
            self.get_my_vlaue_or_0(&self.env().caller())
            
        }

        #[ink(message)]
        fn get_my_vlaue_or_0(&self, account:& AccountId) -> u64{
            *self.my_value.get(account).unwrap_or(&0)
        }

        #[ink(message)]
        fn inc_mine(&mut self, by: u64){
            let caller = self.env().caller();
            let cur_value  = self.get_my_vlaue_or_0(&caller);
            self.my_value.insert(caller, cur_value + by);
        }
    }

    #[cfg(test)]
    mod tests {
        use super::*;

        #[test]
        fn default_works() {
            let contract = Incrementer::default();
            assert_eq!(contract.get(), 0);
        }

        #[test]
        fn it_works() {
            let mut contract = Incrementer::new(42);
            assert_eq!(contract.get(), 42);
            contract.inc(5);
            assert_eq!(contract.get(), 47);
            contract.inc(-50);
            assert_eq!(contract.get(), -3);
        }

        #[test]
        fn my_value_works() {
            let mut contract = Incrementer::new(11);
            assert_eq!(contract.get(), 11);
            assert_eq!(contract.get_mine(), 0);
            contract.inc_mine(5);
            assert_eq!(contract.get_mine(), 5);
            contract.inc_mine(10);
            assert_eq!(contract.get_mine(), 15);
        }
    }
}`

**Comment by athei** [comment]
Can you reproduce the issue when you just clone the current master of the ink! repository and run `cargo +nightly test` inside the `examples/incrementer` directory?

**Comment by Robbepop** [comment]
I am also a bit confused because your picture above shows the following test functions
- `default_works`
- `inc_works`
- `get_mine_works`
While your pasted code shows different test functions.

**Comment by master-davidlee** [comment]
@Robbepop @athei  sorry guys i am a little mess let's  go through the process
first  i change back to official repo 
![image](https://user-images.githubusercontent.com/49427668/78268951-88640d00-753b-11ea-8b25-a11a4e03410b.png)
and i running test 
![image](https://user-images.githubusercontent.com/49427668/78269079-ab8ebc80-753b-11ea-8104-8c3c4d54d3b9.png)
here is my code 
`
#![cfg_attr(not(feature = "std"), no_std)]

use ink_lang as ink;

#[ink::contract(version = "0.1.0")]
mod incrementer {
    use ink_core::storage;

    #[ink(storage)]
    struct Incrementer {
        // Storage Declaration
        value: storage::Value<i32>,
        my_value: storage::HashMap<AccountId,u64>,
    }

    impl Incrementer {
        #[ink(constructor)]
        fn new(&mut self, init_value: i32) {
            // Contract Constructor
            self.value.set(init_value);
        }

        #[ink(constructor)]
        fn default(& mut self){
            self.new(0);
        }

        #[ink(message)]
        fn get(&self) -> i32{
            // Contract Message
            *self.value
        }

        #[ink(message)]
        fn inc(&mut self, by : i32){
            *self.value += by
        }

        #[ink(message)]
        fn get_mine(&self) -> u64{
            self.get_my_vlaue_or_0(&self.env().caller())
            
        }

        #[ink(message)]
        fn get_my_vlaue_or_0(&self, account:& AccountId) -> u64{
            *self.my_value.get(account).unwrap_or(&0)
        }

        #[ink(message)]
        fn inc_mine(&mut self, by: u64){
            let caller = self.env().caller();
            let cur_value  = self.get_my_vlaue_or_0(&caller);
            self.my_value.insert(caller, cur_value + by);
        }
    }

    #[cfg(test)]
    mod tests {
        use super::*;

        #[test]
        fn default_works() {
            let contract = Incrementer::default();
            assert_eq!(contract.get(), 0);
        }

        #[test]
        fn it_works() {
            let mut contract = Incrementer::new(42);
            assert_eq!(contract.get(), 42);
            contract.inc(5);
            assert_eq!(contract.get(), 47);
            contract.inc(-50);
            assert_eq!(contract.get(), -3);
        }

        #[test]
        fn my_value_works() {
            let mut contract = Incrementer::new(11);
            assert_eq!(contract.get(), 11);
            assert_eq!(contract.get_mine(), 0);
            contract.inc_mine(5);
            assert_eq!(contract.get_mine(), 5);
            contract.inc_mine(10);
            assert_eq!(contract.get_mine(), 15);
        }
    }
}`

**Comment by Robbepop** [comment]
The confusion that resulted in this issue was that apparently the old ink! code generation would automatically create test code that already initializes the off-chain environment. This "magic" has been removed in recent iterations so this confusion should no longer apply. Closed.
