### ISSUE TITLE
Implement core::iter::Extend for storage collections

### ISSUE THREAD

**Issue by athei** [paritytech/ink#333]
Usually we use memory data structures as arguments and storage data structures, well, for contract storage. Given this assumption the following situation seems likely to arise:
```
fn new(&mut self, owners: Vec<AccountId>,) {
    for owner in &owners {
        self.owners.push(*owner)
    }
}
```
A simple ergonomic improvement would be to implement `Extend` for the storage structures. That would simplify the above example to:
```
fn new(&mut self, owners: Vec<AccountId>,) {
    self.owners.extend(owners);
}
```

**Comment by Robbepop** [comment]
When https://github.com/paritytech/ink/pull/311 is done we might also want `FromIterator` implementations for our storage data structures.
