### ISSUE TITLE
Is ink! supporting arrays?

### ISSUE THREAD

**Issue by AchalaSB** [paritytech/ink#346]

**Comment by Robbepop** [comment]
Hi, depends on what you understand by array.
ink! provides you with the `storage::Vec` which has a very similar API to a Rust `Vec` (vector) which is basically a automatically growing/shrinking stack and can be accessed like an array.

**Comment by Robbepop** [comment]
@AchalaSB Was the question answered to your satisfaction? If yes, I'd like to close this issue again.

**Comment by AchalaSB** [comment]
Yes, I got the answer. Thanks
