### ISSUE TITLE
Create example contract that uses ext_transfer

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#355]
We have a new native `ext_transfer` with which a contract can easily transfer value to another account. We should have an example contract to demonstrate this new API.

**Comment by jonahb27** [comment]
Do you have documentation for the `ext_transfer` function?

**Comment by Robbepop** [comment]
This would be my best bet so far in terms of proper docs:
https://github.com/paritytech/substrate/blob/master/frame/contracts/COMPLEXITY.md#transfer

**Comment by jonahb27** [comment]
Wow! Thank you!
