### ISSUE TITLE
Write high-level usage documentation for smart contract developers

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#36]
We currently only have low-level documentation for the pDSL describing all the low level library parts that are more targeted towards pDSL developers. For smart contract developers that aim to use the pDSL to write Wasm based smart contracts we need high-level documentation, tutorials and many more examples.

Since `pdsl_lang` is the highest possible level of abstraction that can be targeted by a smart contract developer we should start writing high-level documentation for it. Smart contract developers that want to target the more low-level abstractions such as `pdsl_model` or `pdsl_core` will have to wait a bit more for proper usage documentation.

**Comment by Robbepop** [comment]
Started here: https://github.com/Robbepop/pdsl/wiki

**Comment by shawntabrizi** [comment]
I am starting on this, but I need contribution access to the Wiki. I will put it on HackMD in the meantime.

**Comment by shawntabrizi** [comment]
I have started two wiki pages:
https://github.com/Robbepop/pdsl/wiki/Deploying-Your-First-Contract
https://github.com/Robbepop/pdsl/wiki/Writing-Your-First-Contract

Both are still in progress, but mostly done. Main issue right now is actually calling and testing your contract in the Deploy tutorial.

Contract writing tutorial needs peer review.

**Comment by Robbepop** [comment]
The workshop clearly cuts this. Closed.
