### ISSUE TITLE
Create example contract that uses built-in crypto hashes

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#361]
With the addition of efficient built-in cryptographic hashes we should provide contract writers with an example contracts that demonstrates usage of those.

Implementation PR: https://github.com/paritytech/ink/pull/360
Issues for the built-in hashes: https://github.com/paritytech/ink/issues/358

**Comment by ascjones** [comment]
I've updated the runtime storage example #365 based on #363 - just waiting for the API to be stabilised.

**Comment by Robbepop** [comment]
Nice! Closed.
