### ISSUE TITLE
How to get the contract execution Err type result?

### ISSUE THREAD

**Issue by jeremymj** [paritytech/ink#366]
I'm not sure if this issue belongs here. 
 In the previous `ink` version, when the contract function was called through `polkadot-js/api`, the contract execution process did not satisfy the contract logic and returned Err <T>, there would be an `extrinsic failure` message. However, in recent `2.0` versions, the `Err` prompt message is gone, and the contract caller does not know the contract execution result.
Is there a way to get `Err` detail in ink `2.0`?

**Comment by Robbepop** [comment]
Can you please reformulate your question - I could really not make a whole lot of sense of it. Or can you provide some expamples? Is this mainly concerned about the RPC interface or ink! or something completely different?

**Comment by jeremymj** [comment]
I tried to create two comparison examples, but recently the versions of `ink`、`cargo-contract`、`substrate` have changed so quickly that it is difficult to achieve this goal.

I take [erc721](https://github.com/paritytech/ink/tree/master/examples/erc721) as an example. After deploying an instance, I immediately call the tranfer method. Input parameters are shown in the following figure.
![Screenshot from 2020-03-26 10-17-44](https://user-images.githubusercontent.com/13585788/77605279-7b4d8980-6f4f-11ea-8893-030ae019a1de.png)
According to the logical contract execution, `Err(Error :: TokenNotFound)` error has been returned, but the execution result indicates success, and no error information can be seen in the block details.As shown below
![Screenshot from 2020-03-26 10-22-25](https://user-images.githubusercontent.com/13585788/77605387-b8b21700-6f4f-11ea-88f0-60679e0dab46.png)

Do you understand this description? In the current version, is there a way to get the error information returned during the execution of the contract？ that will have a better user experience for application development. If I remember correctly, this is the effect in previous versions.

 I use: `ink tag 2.0`、`substrate  2.0.0-alpha.4-b5d330f-x86_64-linux-gnu`、`cargo-contract 0.5.0`

**Comment by Robbepop** [comment]
I'd like to know if this is still a problem with ink! 3.0 and an updated version of Polkadot JS Apps and/or the Canvas UI.
Other than that we should probably close this as it seems to be outdated.

**Comment by jeremymj** [comment]
I used the latest version of ink to verify on substrate v2.0.1.When the contract call return something like `Err(Error::NotAllowed)`, the extrinsic execution failed, the reason for the failure is `contracts.ContractTrapped`.
Is it possible to prompt more accurate error information in `system.ExtrinsicFailed`?

**Comment by HCastano** [comment]
@jeremymj I just tested this with some more recent versions of Ink, Canvas, and Polkadot JS Apps and this is still a problem (the unhelpful error part, not the successful extrinsic part). 

I've opened [an issue](https://github.com/paritytech/canvas-ui-v2/issues/27) so that the team working on the new UI gets to fixing this.

In the meantime, if you're developing your own contracts you may want to use something like [`ink_env::debug_println!`](https://paritytech.github.io/ink/ink_env/macro.debug_println.html) to see what the "actual" error is.
