### ISSUE TITLE
ink!   tutorial problem

### ISSUE THREAD

**Issue by master-davidlee** [paritytech/ink#373]
![image](https://user-images.githubusercontent.com/49427668/77977554-9135c280-7332-11ea-92b1-d4897de01a3e.png)
when i want to generate-matadata  from my contract but it has 3 errors   i don't konw if i miss some thing or the flipper contract has problems

the tutorial site is this https://substrate.dev/substrate-contracts-workshop/#/0/building-your-contract

**Comment by Robbepop** [comment]
Can you please explain why you closed the issue again?

**Comment by master-davidlee** [comment]
yeha it's my own problem. Updating dependences from GitHub is too slow  so i import the entire repository to the gitee which can improve the speed  But it cause updating the same dependence “type-metadata" from two repo which makes the error .So i have to change ever source back to github .the  problem gone

**Comment by master-davidlee** [comment]
But i acutally meet another problem . the same tutorial  
https://substrate.dev/substrate-contracts-workshop/#/0/deploying-your-contract
when i upload the  wasm the  extrinsicfailed  but the transfer extrinsicsucced
