### ISSUE TITLE
Implement storage entry API

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#379]
Currently we have 3 different APIs to access a contract's storage in `ink_core`:

- `env::get_contract_storage`: To retrieve a decoded `T` from the contract storage cell.
- `env::set_contract_storage`: To encode a `T` into the contract storage cell.
- `env::clear_contract_storage`: To clear all data from the contract storage cell.

This API is fine, however, it doesn't scale well for additional operations.
For example, adding the ability to query if a contract storage is vacant or occupied requires adding yet another API to the already large set of root functions.

Instead we could unify all accesses to a single contract storage cell using one entry API:

```
fn storage_entry(at: &Key) -> StorageEntry { ... }


pub struct StorageEntry<'a> {
    key: &'a Key,
}

pub enum StorageEntryState {
    Vacant,
    Occupied,
}

impl StorageEntry<'_> {
    pub fn is_vacant(&self) -> bool {
        ...
    }

    pub fn is_occupied(&self) -> bool {
        ...
    }

    pub fn get<R>(&self) -> Result<Option<R>>
    where
        R: scale::Decode,
    {
        ...
    }

    pub fn set<V>(&self, value: &V)
    where
        V: scale::Encode,
    {
        ...
    }
}
```

This is also easily extensible in case we later add the subtrie API for contracts.

**Comment by cmichi** [comment]
Closed, see #532 for the reasoning.
