### ISSUE TITLE
JSON api description: compound types

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#39]
Our current JSON api description implementation is kept very minimal and can only support the Rust primitives `bool`, `u{8,16,32,64,128}` and `i{8,16,32,64,128}` as well as the SRML primitives `Address` and `Balance`.

To allows for custom user types and tuples we need to extend the set of available types to include compound types. These can be named and unnamed optionally. A compound type is transparent in that it tells how it is structured inside to make it work language agnostic.

```json
{
    "name": "Vec3",
    "fields": [
        { "x": "i32" },
        { "y": "i32" },
        { "z": "i32" }
    ]
}
```
The above example would demonstrate something like a
```rust
struct Vec3 {
    "x": i32,
    "y": i32,
    "z": i32,
}
```
We also want to support tuple structs like the following:
```json
{
    "name": "Foo",
    "fields": [
        "i32", "bool", "Address"
    ]
}
```
This represents a tuple struct like the following:
```rust
struct Foo(i32, bool, Address);
```

It is important to note that this representation is recursive. So we could easily define something like this:

```json
{
    "name": "Song",
    "fields": [
        { "duration": "u32" },
        { "title": "[u8; 32]" },
        { "date":
            {
                "name": "Date",
                "fields": [
                    { "year": "u16" },
                    { "month": "u8" },
                    { "day": "u8" }
                ]
            }
        }
    ]
}
```

**Comment by Robbepop** [comment]
Implemented by https://github.com/Robbepop/pdsl/pull/41.
Closed.

**Comment by xlc** [comment]
I have implemented something similar to this for substrate metadata and was hoping it could be used for smart contracts as well. I wonder if any of my code could help? https://github.com/paritytech/substrate/pull/1328

For this particular issue, there are few catches to the proposed solution:
- Circular types: It simplify cannot handle circular types without some kind of references. One example is `enum LinkedList { Node(T, Box<LinkedList>), Empty }`
- Duplicated information. Example: `struct A { field: u8, field2: u8 }; struct B { field: A, field2: A }`. You don't want to store the data for `struct A` twice.

**Comment by Robbepop** [comment]
We might want to consider using a similar or your approach (and code) in the future. Thank you for linking it!

**Comment by Robbepop** [comment]
Implemented by https://github.com/paritytech/ink/pull/104

Can be closed once merged.

**Comment by Robbepop** [comment]
Merged. Closed.
