### ISSUE TITLE
How to transfer balance to the contract?

### ISSUE THREAD

**Issue by liuchengxu** [paritytech/ink#394]
We already have `transfer` for transferring value from the contract to the destination account, my question is how to transfer some balances to the contract itself from some external account?

**Comment by Robbepop** [comment]
When making an extrinsic call to a smart contract you can not only provide it with its input data (function selector + arguments) and the maximum gas limit but you can also set an endowment for the call which is basically value you provide the contract with. That's how you transfer value to a smart contract. Also via `transfer` you can transfer value from one smart contract to another. Same for instantiation and calls to other smart contracts. So even without `transfer` you can transfer value from one smart contract to another.

**Comment by liuchengxu** [comment]
Hmm, how can the contract perceive the endowment? Sometimes the contract logic could be: user deposits some balances into the contract, and contract needs to know this deposit, how could I do this?

**Comment by Robbepop** [comment]
Something like this in ink!:
```
/// Returns `true` if the contract is happy with the received endowment.
#[ink(message)]
pub fn receive_endowment(&self) -> bool {
    if self.env().transferred_value() > 1000 {
        return true
    }
    false
}
```
Note: I just scribbled this so the above code could contain bugs or errors. But that's technically how you can write a smart contract with a message just for receiving endowment and inspecting it.

**Comment by liuchengxu** [comment]
That should solve my problem, thanks @Robbepop !
