### ISSUE TITLE
Add storage::VecDeque data structure

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#404]
We currently do not provide a so-called `VecDeque` storage data structure in ink! but we should. From the Rust standard library:

> A double-ended queue implemented with a growable ring buffer.
>
> The "default" usage of this type as a queue is to use `push_back` to add to the queue, and `pop_front` to remove from the queue. `extend` and append push onto the back in this manner, and iterating over `VecDeque` goes front to back.

So technically speaking a `VecDeque` is a ring buffer and we can utilize this in ink!.
For creating the `storage::VecDeque` we can take the `storage::Vec` as a template since both work very similar. Both operate internally on a `LazyIndexMap`. The `LazyIndexMap` itself operates on 2^32 adjacent storage cells that it can index via a single `u32`. The `storage::VecDeque` has the following set of methods:

- [ ] `new`: Creates a new storage queue.
- [ ] `len`: Returns the length of the storage queue.
- [ ] `is_empty`: Returns `true` if the storage queue is empty.
- [ ] `iter`: Returns an iterator over shared references to the elements of the queue from front to back. The returned iterator should be a `DoubleEndedIterator` and ExactSizeIterator`.
- [ ] `iter_mut`: Returns an iterator over the exclusive references to the elements of the queue from front to back. The returned iterator should be a `DoubleEndedIterator` and ExactSizeIterator`.
- [ ] `push_front`: Pushes an element to the front of the queue.
- [ ] `push_back`: Same as in `storage::Vec`.
- [ ] `pop_front`: Pops the element at the front of the queue and returns it.
- [ ] `pop_back`: Same as in `storage::Vec`.
- [ ] `front`: Returns a shared reference to the front element if any.
- [ ] `front_mut`: Returns an exclusive reference to the front element if any.
- [ ] `back`: Returns a shared reference to the last element if any.
- [ ] `back_mut`: Returns an exclusive reference to the last element if any.
- [ ] `get`: Returns a shared reference to the element at the given index.
- [ ] `get_mut`: Returns an exclusive reference to the element at the given index.
- [ ] `swap`: Swaps two elements within the queue.
- [ ] `swap_remove_front`: Swaps front and the indexed element and then pops front.
- [ ] `swap_remove_back`: Swaps back and the indexed element and then pops back.
- [ ] **Bonus:** `clear`: Clears all elements efficiently (without reading from contract storage if not necessary) from the stash and setting its length field only once. This should be a lot more efficient than popping all the elements for the same effect. Benchmarks should be provided to proof this.

Besides the above implementations it should also have the following Rust trait implementations:

- [ ] derive for `Debug`
- [ ] `Default`
- [ ] `PartialEq` + `Eq` if `T: PartialEq` and `T: Eq`
- [ ] `PartialOrd` + `Ord` if `T: PartialOrd` and `T: Ord`
- [ ] `Hash` if `T: Hash`
- [ ] `Index` and `IndexMut`
- [ ] `SpreadLayout`

As with `storage::Vec` it must be taken care to properly clean up its elements. For an example with `storage::Vec` look at its `clean_cells` internal methods called by its `Drop` implementation.

Unit tests need to be written in the same vein as with `storage::Vec`. Maybe `storage::Vec` can provide some inspiration as to how to write them properly.

## Internal Structure

The internal structure of the `storage::VecDeque` works quite similar to the one of a `storage::Vec`. The key difference is that it wraps around the `u32` that it uses as index in case some element is pushed to its front or back and it already operates on limits. E.g. let's take a `storage::VecDeque` that has `0: 'A'` and `1: 'B'` as elements. Then pushing another element to the front would not shift all its elements by one but instead allocates another elements at index `0.wrapping_sub(1)` which should be `2^32-1 == u32::MAX`. So the `storage::VecDeque` needs not only to store its current length as the `storage::Vec` does but also keeps track of where its start is currently within the 2^32 wide array of possible cells of the underlying `LazyIndexMap`.

**Comment by SkymanOne** [comment]
`VecDeque` is not exported in ink! prelude
