### ISSUE TITLE
Got ExtrinsicFailed when use `Extrinsics -> contract -> call` with right selector

### ISSUE THREAD

**Issue by hammeWang** [paritytech/ink#45]
Hi, after I got `Flipper.json`,  transformed the function `selector` into hex format. And then, open substrate UI and use:
```
Extrinsics -> contract -> putCode
Extrinsics -> contract -> create
Extrinsics -> contract -> call
```
the first two steps got done well, but at 3rd step, even with the right `selector`, I still got `ExtrinsicFailed`.
I have asked in Riot and was told that there might be a problem with extrinsic dispatch mechanism, hope it would be fixed soon.

**Comment by Robbepop** [comment]
Thank you for your bug report. We are currently working on a fix.

**Comment by Robbepop** [comment]
I was able to identify 2 minor bugs on the pDSL side and one major bug on substrate side: https://github.com/paritytech/substrate/issues/2277

The problem should be fixed as soon as the Substrate side bug is fixed as well.

**Comment by Robbepop** [comment]
@hammeWang the problem should be fixed now.

**Comment by Robbepop** [comment]
We can confirm this to be working properly now. Closed. Note that users should no longer use contracts using the extrinsics tab but the new specialized UI for it.
