### ISSUE TITLE
Re-evaluate `Option<()>` vs. `Result` for ink! 3.0 API

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink#458]
At the moment the public ink! API often returns `Option<()>` when there is only one error case (i.e. returning `None` in the error case).

Sometimes it can be more semantically speaking and self-explaining to return `Result<(), SpeakingErrType>` though. We did this e.g. for `storage2/Vec`:

```
pub struct IndexOutOfBounds;
pub fn set(&mut self, index: u32, new_value: T) -> Result<(), IndexOutOfBounds> { }
```

Once we have decided which variant works better for us we should refactor the public API to this variant before releasing ink! 3.0.

**Comment by HCastano** [comment]
@cmichi any updates here?

**Comment by Robbepop** [comment]
Yeah we found out that it was indeed a bad idea originally and have (by now since months) implemented the proposal. Closed.
