### ISSUE TITLE
Roadmap and timeline

### ISSUE THREAD

**Issue by xlc** [paritytech/ink#47]
Are there any roadmap and timeline for this project?
I want to know what is the end goal for this project, what features are going to be included in the 1.0 version, and when it is likely to happen (Q2 or Q3?)

**Comment by Robbepop** [comment]
There is a rough roadmap.
Our current major goal is to make pDSL "ready" for the Sub0 workshop.

**Comment by xlc** [comment]
Where can I see the rough roadmap?

https://github.com/Robbepop/pdsl/projects/1
Those are the tasks for Sub0 right?

**Comment by Robbepop** [comment]
There is no concrete roadmap online so far. We are thinking about creating one. Thanks for the reminder!

**Comment by Robbepop** [comment]
https://github.com/paritytech/ink/issues/153

Closed.
