### ISSUE TITLE
Add support for pure contract functions

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#471]
## Current State

We currently do not support so-called pure functions in ink!.
The pure function concept comes from Solidity and means that a function that has the `pure` modifier will never modify state or even query runtime information about its state. It is like a purely mathematical function.

This allows to implement certain optimizations: For example, calling such a `pure` function from another smart contract will just embed its code directly into the caller and will never do a proper call over the chain with all the associated overhead.

## Problems

In comparison to Solidity ink! is not a compiler but just a macro and thus only has a syntactical view on the whole ink! source code. This means that semantic checks such as the one required for a `pure` function that it will never modify or query contract specific runtime information is impossible to implement in ink!.

## Proposal

However, the ink! macros do not exist in isolation and we additionally have the `cargo-contract` build tool for our ink! smart contracts. While `cargo-contract` is also not a compiler it has the knowledge how to build an ink! smart contract for its WebAssembly (Wasm) target as well as how to generate ink! metadata.
So what we could do to support `pure` functions in ink! is the following:

1. We add a new callable type next to messages and constructors that is the `pure` ink! function.
     - Pure ink! functions must have no `self` receiver. Besides this they are very similar to ink! messages.
2. We need to add pure functions to the ink! metadata to expose them to other tools such as `cargo-contract`.
3. Then `cargo-contract` must implement the semantics check using the extended ink! metadata and the generated Wasm. It should use already existing Wasm tools in order to analyze the resulting Wasm blob. The semantics check should be fairly simple:
    1. Query the `pure` function under test in the Wasm blob by its selector or other means.
    2. Check if its associated Wasm instructions make calls to any of the forbidden `ext_*` functions. Note though that there are some functions that are still allowed, e.g. `ext_input`.
    3. If the Wasm instructions associated with the `pure` function are using such an `ext_*` function bail out with an error.

Also `cargo-contract` maybe should provide a `cargo contract check` command in order to only check an ink! smart contract without the need to actually have a resulting Wasm blob at the end. This could come in handy in the future.

**Comment by KaiserKarel** [comment]
Why exactly would one use an ink! pure function over just including a library and embedding the function that way?

**Comment by SkymanOne** [comment]
Closing as inactive
