### ISSUE TITLE
new metadata json file can't load properly

### ISSUE THREAD

**Issue by ProgramAPE** [paritytech/ink#473]
Recently I use the new example project to compile contract wasm file.
First my contract version 0.6.+. this build wasm properly. But can't generate the metadata json file. So I upgrade the contract to 0.7.0. Now both wasm and metadata json file were compiled. But when I load them to my local chain through the polkadot.js.org UI some wrong happens. The wasm file can load properly. But I can't load the metadata json file. 
I use the contract 0.6.+ to generate the metadata json file and wasm. Both files can be loaded to  the chain .
Did someone know why? thanks

**Comment by Robbepop** [comment]
Some questions:

- Which ink! version? (Found in `Cargo.toml`)
- Which `cargo-contract` version? Query by `cargo contract --version`
- Which Substrate version? Rc3, 4, 5?
- Which Polkadot JS Apps version?
- Your own custom chain or the default one?
- Tried with an offchain `--dev` chain?
- What do you mean by "version `0.6`? Is that your `cargo-contract` version?

Problem with all those entities is that not all of them work with each other.
We are currently working on ink! 3.0 which has not yet been released (it is what you see in this repo's `master` branch) and Substrate just very recently did a huge update to its contracts pallet which breaks everything for good. For as long as you are using Substrate rc4, `cargo-contract` 0.6.X and ink! 2.1 things should hopefully work.

**Comment by ProgramAPE** [comment]
ink! Version: 2.1.0
cargo contract: 0.7.0
substrate: Rc 4
Polkadot JS: v0.49.0-beta.16
Chain: substrate-developer-hub/substrate-node-template with contract enabled
No --dev
above software is tested with fail to upload metadata json file. But they can produce wasm and metadata json file properly.
Once I use cargo-contract 0.6.+. Everything is OK. except I can not use the ink_core::storage2 API.

**Comment by Robbepop** [comment]
> the ink_core::storage2 API.

This is part of ink! 3.0 and since you are using ink! 2.1 you cannot use it, yet.

**Comment by ascjones** [comment]
Also `cargo-contract` 0.7.0 is not released yet (it is what is on `master`), and I wouldn't expect it to be able to generate the metadata for `ink! 2.1.0`

**Comment by ProgramAPE** [comment]
> > the ink_core::storage2 API.
> 
> This is part of ink! 3.0 and since you are using ink! 2.1 you cannot use it, yet.
> Sorry for the confusion, we try to release ink! 3.0 as soon as we can but it will take a little bit more time.
> As you have found out `cargo-contract` 0.7 is deliberately not compatible with ink! 2.1.
> We could make it compatible but this would seriously delay release of ink! 3.0.

My origin attention is just finding some ink contract examples. So I dive into the master branch examples and then I get errors.
But I should say the new ink is more like Rust code they are wonderful! So expecting the ink!3.0 coming!
