### ISSUE TITLE
tutorials putCode returns system.ExtrinsicFailed with substrate rc5

### ISSUE THREAD

**Issue by Matrix-Zhang** [paritytech/ink#482]
i just follow the tutorials to upload flipper contract to substrate, but always return system.ExtrinsicFailed

**Comment by ascjones** [comment]
`ink!` is currently not compatible with substrate `rc5` - we're [working on it](https://github.com/paritytech/ink/pull/478). In the meantime you can still use `rc4`.

**Comment by gopherine** [comment]
@ascjones rc4 does not compile though, right now i am only able to compile rc6 and i see #478 merged i still get the same error when uploading the above

**Comment by ascjones** [comment]
@gopherine see latest comment https://github.com/paritytech/ink/issues/484#issuecomment-686969167 to get rc4 to build.

We're working as hard as we can to get a set of releases ready for `rc6`.
