### ISSUE TITLE
[ink!3.0] the trait `BaseEvent` is not implemented

### ISSUE THREAD

**Issue by hammeWang** [paritytech/ink#483]
**Description**

I am using ink!3.0(the latest commit of ink repo, which is `ba5aed197a31109367a935cee0f5671987c7de90`), and I tried to,
1. add a simple event in `ink/example/delegator/subber`,
2. run `cargo +nightly contract build` inder `ink/example/delegator`
then I met this error:
```rust
error[E0277]: the trait bound `subber::Subber: ink_lang::BaseEvent` is not satisfied
  --> /Users/hammer/Documents/paritytech/code/ink/examples/delegator/subber/lib.rs:20:1
   |
20 | #[ink::contract(version = "0.1.0")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `ink_lang::BaseEvent` is not implemented for `subber::Subber`

```

It seems that dependency contract can not have event in itself.

**Comment by Robbepop** [comment]
Fixed issue in https://github.com/paritytech/ink/pull/470.

**Comment by Robbepop** [comment]
Can you confirm that this is fixed now @hammeWang with current ink! `master` ?

**Comment by Robbepop** [comment]
Just checked myself. No longer a bug for current ink! `master`. Closed.
