### ISSUE TITLE
Outdated workshop doc 2020-09-03

### ISSUE THREAD

**Issue by franleplant** [paritytech/ink#484]
**Questions**

- Is this a bug concerning building of ink! smart contracts?
    - no
- Is this a bug that appears when interacting with smart contracts via the Polkadot JS browser UI?
    - no

It is a problem with the workshop doc setup. I am reporting it here because I couldn't find where is the workshop doc source.

**Describe the bug**

A couple of problems in the setup section https://substrate.dev/substrate-contracts-workshop/#/0/setup

1- devs should install nightly wasm

```diff
- rustup target add wasm32-unknown-unknown --toolchain stable
+ rustup target add wasm32-unknown-unknown --toolchain nightly
```

2- devs should install version v2.0.0-rc6 of substrate instead of v2.0.0-rc4 (which fails to compile BTW)

```diff
- cargo install node-cli --git https://github.com/paritytech/substrate.git --tag v2.0.0-rc4 --force --locked
+ cargo install node-cli --git https://github.com/paritytech/substrate.git --tag v2.0.0-rc6 --force --locked
```

Maybe we can even specify devs to go to the substrate repo and find the latest rcX tag and use that.

Perhaps most of the setup can be replaced by simply linking to the substrate docs so that we get a single source of truth.

After making these changes the installation worked (no compilation errors when installing node-cli)

**Expected behavior**

That the tutorial setup works without errors.

**Screenshots**

Following the docs the first error was regarding missing Wasm target support, digging a little bit I found that
I should install the wasm target for the nightly channel and that allow me to move forward.

Then I found the following error:

<img width="1524" alt="Screen Shot 2020-09-03 at 10 45 01" src="https://user-images.githubusercontent.com/1852455/92123026-88aa5200-edd2-11ea-9944-d6214ed28424.png">

After using the `rc6` it went away

**Additional context**

Here's my setup

- os: macos

```sh
rustc --version
rustc 1.46.0 (04488afe3 2020-08-24)

rustup run nightly rustc --version
rustc 1.48.0-nightly (d006f5734 2020-08-28)

```

With the right pointers I can make the PR to the docs to apply these fixes.

Edit1:

When using rc6 and going through the flipper tutorial I get this error `system.ExtrinsicFailed` while uploading the contract through polkadot UI connected to my local substrate chain.

I've found this issue https://github.com/paritytech/ink/issues/482 that talks about rc6 not working correctly with ink and so I tried

```sh
cargo install node-cli --git https://github.com/paritytech/substrate.git --tag v2.0.0-rc5 --force --locked
```

And it fails with this error

```sh
     Compiling sp-consensus-babe v0.8.0-rc5 (/Users/franleplant/.cargo/git/checkouts/substrate-7e08433d4c370a21/e00d78c/primitives/consensus/babe)
  error[E0424]: expected value, found module `self`
      --> /Users/franleplant/.cargo/git/checkouts/substrate-7e08433d4c370a21/e00d78c/frame/support/src/traits.rs:1184:11
       |
  1182 | / bitmask! {
  1183 | |     /// Reasons for moving funds out of an account.
  1184 | |     #[derive(Encode, Decode)]
       | |              ^^^^^^ `self` value is a keyword only available in methods with a `self` parameter
  1185 | |     pub mask WithdrawReasons: i8 where
  ...    |
  1200 | |     }
  1201 | | }
       | |_- this function has a `self` parameter, but a macro invocation can only access identifiers it receives from parameters
       |
       = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

  error: aborting due to previous error

  For more information about this error, try `rustc --explain E0424`.
  error: could not compile `frame-support`.

  To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `node-cli v2.0.0-rc5 (https://github.com/paritytech/substrate.git?tag=v2.0.0-rc5#e00d78cb)`, intermediate artifacts can be found at `/var/folders/8g/hjnk29zn4y3_t8_j8c1h20q00000gn/T/cargo-install9REQYF`

```

At this point Im lost about what to do

Thanks!

Fran

**Comment by saingsab** [comment]
I would suggest the following toolchain preparation:

```
#!/usr/bin/env bash

set -e

echo "*** Initializing WASM build environment"

if [ -z $CI_PROJECT_NAME ] ; then
    rustup install nightly-2020-07-02
    rustup default nightly-2020-07-02
    rustup update stable
fi

rustup target add wasm32-unknown-unknown --toolchain nightly-2020-07-02
```
Add above bash script to scripts/init.sh directory. As per mention the Contract pallet only support the RC4 and at the mean time you have to specify your nightly toolchain.

Hopefully it's help you.

**Comment by franleplant** [comment]
Thanks @saingsab , very late yesterday I found further information on the Element chat and using a particularly nightly basically fixed everything, I used a different one from the on you are specifying though.

So, for short term future reference, you should use `nightly-2020-06-1` for the tutorial to work:

```sh
rustup install nightly-2020-06-01
rustup target add wasm32-unknown-unknown --toolchain nightly-2020-06-01
```


If you already installed everything make sure you reinstall everything with the 2020-06-01 nightlies.

Hope this helps!

@saingsab what's the best way of getting involved with the development of substrate and ink?
