### ISSUE TITLE
Add `#[ink::test]` procedural macro to reduce code duplication

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink#486]
## Problem

We currently have a lot of code duplication for ink! core tests:

```rust
#[test]
fn spread_layout_works() -> env::Result<()> {
    env::test::run_test::<env::DefaultEnvTypes, _>(|_| {
       // test code returning a Result<(), env::Error>
    })
}
```

In the past we sometimes had the case of having to adapt all these tests, because of some change to this setup.

## Proposal

Add a procedural macro à la `#[ink::test]` to mitigate this:

```rust
use ink_lang as ink;

#[ink::test]
fn spread_layout_works() -> env::Result<()> {
   // test code that returns Result<(), env::Error>
}
```

or 

```rust
use ink_lang as ink;

#[ink::test]
fn spread_layout_works() {
   // testing code that returns nothing
}
```

**Comment by Robbepop** [comment]
It should probably be called `ink::test` where `ink` is just the crate name where it was defined which should be the same as `ink_lang_macro`. You can just define yet another proc. macro there and register it under the name `test`.

**Comment by Robbepop** [comment]
duplicate: https://github.com/paritytech/ink/issues/335
