### ISSUE TITLE
Failed to create new contract（Extrinsic contracts.putCode）

### ISSUE THREAD

**Issue by charkali** [paritytech/ink#489]
When I create a new contract and upload the new contract via https://polkadot.js.org/apps/?rpc=wss://mainnet1.edgewa.re#/contracts/code, the following error appears. Is it a problem with my environment or other questions.

cargo contract new flipper 

 ****
![image](https://user-images.githubusercontent.com/20460739/93965566-05f33200-fd95-11ea-9d3f-9c7ae5794446.png)

**Comment by Robbepop** [comment]
This looks more like a UI issue than an issue directly connected to ink!. @kwingram25

**Comment by athei** [comment]
It looks like a mismatch between UI and node. We dropped one argument from `putCode` a while back. It looks like the UI is too new for the node as it already dropped the argument.

**Comment by charkali** [comment]
@athei Other test nodes on the same ui are normal

**Comment by athei** [comment]
Then I assume that the specific node you are testing here with is out of date. Make sure it uses the `pallet_contracts` from substrate `2.0.0-rc4`.

**Comment by charkali** [comment]
> 然后，我假设您要在此处测试的特定节点已过时。确保它使用`pallet_contracts`from基材`2.0.0-rc4`。



> Then I assume that the specific node you are testing here with is out of date. Make sure it uses the `pallet_contracts` from substrate `2.0.0-rc4`.

I am using `2.0.0-rc4`

**Comment by Robbepop** [comment]
This is fixed when using the newly released ink! 3.0-rc1 and the updated Polkadot JS Apps or Canvas UI. Closed.
