### ISSUE TITLE
Get contract balance and transfer token to another account / contract

### ISSUE THREAD

**Issue by xlc** [paritytech/ink#50]
Needs ways to:
- get the contract's current balance
- transfer balance to another account
- transfer balance to another contract and call it
- ? transfer balance to another contract without calling it?

Relates to #30 as I think currently the only way to transfer balance from a contract to another contract / account is use `ext_call`

Depends on #4 because contract have to know the type of `Balance`

**Comment by Robbepop** [comment]
This basically comes down to what we want to achieve through being able to call back into the runtime via https://github.com/Robbepop/pdsl/issues/42.

**Comment by xlc** [comment]
No. #42 is using `ext_dispatch_call` but this one is using `ext_balance` and `ext_call`
The balance work is handled by [AccoundDb](https://github.com/paritytech/substrate/blob/master/srml/contract/src/account_db.rs) which did not actually involve with rest of the runtime much.

**Comment by Robbepop** [comment]
Getting balance is done by `ext_balance`.
Doing transfers is done by https://github.com/paritytech/ink/pull/108.
Closed since feature is already provided.
Docs about https://github.com/paritytech/ink/pull/108 will follow soon.
