### ISSUE TITLE
"error: toolchain 'nightly-2020-06-01-x86_64-pc-windows-msvc' is not installed"

### ISSUE THREAD

**Issue by GowthamChowdary** [paritytech/ink#505]
This is the error i get when i follow the [tutorial](https://substrate.dev/substrate-contracts-workshop/#/0/setup)
When i just remove the "+nightly-2020-06-01" part, it installs fine.  I'm making this so you can update the docs and people who have the same error and google it ,come across this. 
 not really a "fix" but, just do 
"cargo install node-cli --git https://github.com/paritytech/substrate.git --tag v2.0.0-rc4 --force --locked"

**Comment by Robbepop** [comment]
Closed since this issue applies to the (now) outdated ink! 2.1 tutorial. We recommend using the latest ink! 3.0-rc1.
