### ISSUE TITLE
i add rust-src but "cargo +nightly build" says not found

### ISSUE THREAD

**Issue by Harman-singh-waraich** [paritytech/ink#518]
PS C:\Users\hp\desktop\generalized-dex\flipper> cargo +nightly contract build
 [1/4] Collecting crate metadata
 [2/4] Building cargo project
ERROR: Building with xbuild

Caused by:
    `rust-src` component not found. Run `rustup component add rust-src`.
PS C:\Users\hp\desktop\generalized-dex\flipper> rustup component add rust-src
info: component 'rust-src' is up to date

**Comment by pepyakin** [comment]
does `rustup component add rust-src --toolchain=nightly` work?

**Comment by Harman-singh-waraich** [comment]
yes it worked. I also had to specify an older nightly version:

rustup component add rust-src --toolchain=nightly-2020-08-23
cargo +nightly-2020-08-23

**Comment by clearloop** [comment]
```
 𝝺 cargo +nightly-2020-10-05 contract build
 [1/4] Collecting crate metadata
 [2/4] Building cargo project
ERROR: Building with xbuild

Caused by:
    `rust-src` component not found. Run `rustup component add rust-src`.
 𝝺 rustup component remove rust-src --toolchain nightly-2020-10-05
info: removing component 'rust-src'
 𝝺 rustup component add rust-src --toolchain nightly-2020-10-05
info: downloading component 'rust-src'
info: installing component 'rust-src'
info: Defaulting to 500.0 MiB unpack ram
 𝝺 cargo +nightly-2020-10-05 contract build                    
 [1/4] Collecting crate metadata
 [2/4] Building cargo project
ERROR: Building with xbuild

Caused by:
    `rust-src` component not found. Run `rustup component add rust-src`.
 𝝺 

```

**Comment by NachoPal** [comment]
I got exactly the same error that @clearloop Changing the nightly version seems not to work.
```
cargo 1.45.1 (f242df6ed 2020-07-22)
rustup 1.22.1 (b01adbbc3 2020-07-08)
```
