### ISSUE TITLE
nightly versioning issues 

### ISSUE THREAD

**Issue by wheresaddie** [paritytech/ink#525]
It mentions you should install the `nightly-2020-10-06` but it should be `nightly-2020-10-05`. The former might work bit the latter is known to be the last version that does not contain the regression we are trying to avoid.. 

In the rest of the tutorial that version should be referenced in the commands so the correct toolchain is used. So whenever writing cargo `+nightly` ... you should write cargo `+nightly-2020-10-05` ... instead.

**Comment by wheresaddie** [comment]
:people_holding_hands:

**Comment by athei** [comment]
As per discussion with @riusricardo the tutorial is actually correct.

1. ink! does not actually need the specific nightly. Only the node does. So no need for the long `+nightly-2020-10-05`.
2. rustup actually uses `2020-10-05` when you specify `2020-10-06`. Ingenious!. So the correct nightly is used by specifying the one from one day later (as it is already done in the tutorial).
