### ISSUE TITLE
supporting for erc721 string on explorer

### ISSUE THREAD

**Issue by puffanddmx** [paritytech/ink#526]
After building erc721, I am testing after deploying the explorer below. I am trying to test by putting some string information in the corresponding id of erc721 through self-customization to support string writing, but it seems that I can't actually write using strings in explorer. (It seems to be only bytes.) Is there a way?

https://polkadot.js.org/apps/#/

**Comment by jacogr** [comment]
I would suggest re-logging it in the apps repo (GitHub link on top right of the UI), sadly having it here means it won't be tracked and done.

**Comment by Robbepop** [comment]
@puffanddmx can you please open a new issue there?

**Comment by Robbepop** [comment]
I just copied the issue at the correct repo. Closed.
