### ISSUE TITLE
I can't upload my wasm when using Balance * Balance

### ISSUE THREAD

**Issue by ByteRui** [paritytech/ink#543]
I write a function like in my contract file

#[ink(message)]
pub fn test()->Balance{
      let a = Balance::from(1000u128);
      let b = Balance::from(1100u128);
     a * b
}

the contract can be compiled.But the wasm flle can't be uploaded though canvas-ui to the canvas-node.
the version of cargo-contract is v0.7.1

**Comment by Robbepop** [comment]
Thanks for the bug report!

The code you pasted above is not valid ink! code since its message is missing a receiver.
Please paste your entire contract source code as well as your `Cargo.toml` so we can actually help you.
Also please tell us what exactly is the error the Canvas UI has with it.

**Comment by ByteRui** [comment]
[profile.release]
overflow-checks = false

add this code in Cargo.toml, this wasm can been putted.
