### ISSUE TITLE
CI fails with "failed to download"

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink#556]
As much as I like our CI, I recently often have problems with jobs failing with this reason:

```
    Updating crates.io index
error: failed to download `libc v0.2.80`
Caused by:
  unable to get packages from source
Caused by:
  failed to parse manifest at `/ci-cache/ink/cargo/cmichi-add-transferred-balance-example/build-wasm/registry/src/github.com-1ecc6299db9ec823/libc-0.2.80/Cargo.toml`
Caused by:
  no targets specified in the manifest
```

It's mostly two crates for which it fails: `libc v0.2.80` or `paste v1.0.2`.

Here are two jobs which failed recently:
https://gitlab.parity.io/parity/ink/-/jobs/701265
https://gitlab.parity.io/parity/ink/-/jobs/701277

Re-running them sometimes helps, but most often not. I just re-run from time to time and at one point it works.

Currently I have problems getting them to run for https://github.com/paritytech/ink/pull/555. I re-run them from time to time since yesterday, but they don't run through.

I talked to @TriplEight and he suspects a race-condition somewhere during the execution of `pre_cache.sh`.

**Comment by TriplEight** [comment]
It is the [bug](https://github.com/rust-lang/cargo/issues/8120) in cargo, `CARGO_HOME` more specifilally.

**Comment by TriplEight** [comment]
I'll try another approach to mitigate it, vendoring.

**Comment by Robbepop** [comment]
`CARGO_HOME` caching has just been removed. Hopefully fixing the bug. If not, then please re-open. Closed.
