### ISSUE TITLE
How to call a runtime function from within a contract?

### ISSUE THREAD

**Issue by GalaIO** [paritytech/ink#558]
hi, I want to know how to call runtime function which defined in pallet, please~

**Comment by qaibeibei** [comment]
I also want to know that some of the ones I found are old versions

**Comment by Robbepop** [comment]
This is not yet possible unfortunately.
We are working on a solution called "chain extensions" that will allow runtimes to customize the contracts API in order to further allow calling into the runtime if the runtime chooses to provided this functionality.
However, implementation on the Substrate side is not yet done.
@athei

**Comment by XSvr** [comment]
> This is not yet possible unfortunately.
> We are working on a solution called "chain extensions" that will allow runtimes to customize the contracts API in order to further allow calling into the runtime if the runtime chooses to provided this functionality.
> However, implementation on the Substrate side is not yet done.
> @athei

Parity is a cross chain ecology, but the biosphere is a prison. I'm so sad @Robbepop @athei

**Comment by Robbepop** [comment]
The chain-extension feature is well on the top of our priority list to work on. Hopefully won't take too long to get it done.

**Comment by ianhe8x** [comment]
Is `Call contract from runtime` the same case as this one and can be supported by the chain-extension feature?

**Comment by athei** [comment]
Yes. Chain extensions is the means to call custom functions in your runtime.

**Comment by Robbepop** [comment]
Chain extensions have just been implemented in https://github.com/paritytech/ink/pull/592.
Closed.
