### ISSUE TITLE
The upload button does not work for ABI

### ISSUE THREAD

**Issue by lana-shanghai** [paritytech/ink#586]
Hello! I'm connected to Canvas testnet. The contract ABI is recognized, but the upload button is grey. Please see attached image
<img width="983" alt="Screenshot 2020-11-18 at 15 14 12" src="https://user-images.githubusercontent.com/31368580/99541582-4811ac00-29b1-11eb-967e-12047cadf556.png">

**Comment by Robbepop** [comment]
We probably need more info. Also this seems to be an issue with the UI and not with ink! itself.
Please re-open this issue on the Polkadot JS Apps repository: https://github.com/polkadot-js/apps

@jacogr

**Comment by jacogr** [comment]
Duplicate here, it is already answered there. (I generally don't comment here at all, since I cannot track what I don't see). So yes, issues to the correct repos and only one, please.
