### ISSUE TITLE
Need an example to show how to use trait-contract as a storage in contract.

### ISSUE THREAD

**Issue by atenjin** [paritytech/ink#590]
**Is there a way to load a contract from an AccountId directly?**

**Describe the details**
Example `delegator` and `multisig_plain` show how to do a contract call another contract. However I'm interesting in that whether ink! allow to load a contract from an AccountId?
In example `delegator`, the contract call should pass the contract type, and in example `multisig_plain`, the contract allow to pass an AccountId, but call some function need to pass the selector and encoded params.

So is there a way to load a contract from an AccountId? I look though the code and find the trait:
```rust
pub trait FromAccountId<T>
where
    T: Environment,
{
    /// Creates the contract instance from the account ID of the already instantiated contract.
    fn from_account_id(account_id: <T as Environment>::AccountId) -> Self;
}
```
But there is no example to show how to use this trait. And in expanded code for a contract, this trait is not implemented for the contract.
Thus, I don't know whether this thing "load a contract from an AccountId" is allowed?
If this thing is allowed, then, how can I use it?
(
Sorry for I don't understand the doc comments in create_builder.rs file:
https://github.com/paritytech/ink/blob/3803a2662e89dfa97b6f8b17e87c0cce2d873f48/crates/env/src/call/create_builder.rs#L146-L164
)

In my mind, what I expect is like:
```rust
// load a contract from an AccountId
let erc20_instance: Erc20 = Erc20::from_account_id(account_id);
``` 

And it seems that the `trait-*` design like the example "trait-erc20", "trait-flipper" is a way to solve this situation? May be we need more example to show how to use `trait-*` contract to design a contract specification.

**Comment by atenjin** [comment]
for example the trait-contract may could be used like(I guess):
```rust
    #[ink(storage)]
    pub struct ExampleContract {
        holder: Lazy<dyn BaseErc20>,
    }
```
to receive different erc20 implementation. (But I can't compile it now).

Thus the final thing what I expect is like the interface in solidity. The caller contract could load an Address to an interface and call the real contract.

But now I don't know how to use `from_account_id` to those things, and there is no example to show how to use trait-contract in a contract.

**Comment by atenjin** [comment]
I think I figure out how to use `FromAccountId::from_account_id`. 
This method is only used in the condition like `delegator` example.

contract A crate is depended by contract B crate, like `accumulator` is depended by `delegator` in `delegator` example. In B cargo.toml, the A must open feature `ink-as-dependency`, then in conditional compilation for A, the macro would generate the implementation `FromAccountId::from_account_id` for struct `A`, and then, in contract B, could use
```rust
            use ink_env::call::FromAccountId;
            let instance: A = A::from_account_id(address);
```
to load contract A from an address/account_id.

But now I still don't know how to use trait-contract as a storage.

**Comment by Robbepop** [comment]
> for example the trait-contract may could be used like(I guess):
> 
> ```rust
>     #[ink(storage)]
>     pub struct ExampleContract {
>         holder: Lazy<dyn BaseErc20>,
>     }
> ```
> 
> to receive different erc20 implementation. (But I can't compile it now).
> 
> Thus the final thing what I expect is like the interface in solidity. The caller contract could load an Address to an interface and call the real contract.
> 
> But now I don't know how to use `from_account_id` to those things, and there is no example to show how to use trait-contract in a contract.

This has not yet been implemented for ink! but we are aware that this is needed and are already working out some possible designs for this feature.

**Comment by Robbepop** [comment]
Closed since superseeded by https://github.com/paritytech/ink/issues/631.
Please continue discussion in the linked issue.
