### ISSUE TITLE
How do we encoded execution result decode correctly?

### ISSUE THREAD

**Issue by thashimoto1998** [paritytech/ink#591]
How do we encoded execution result decode correctly?

 I already checked smart contract execution correctly, but I got error that encoded execution result is not decoded correctly when runtime module handle decode.

```
smart contract 
#[ink(message)]
        pub fn is_finalized(&self, query: bool) -> bool {
            query 
        }
```

``` 
Runtime module 1
celer_contracts Module
pub fn call_contract_condition(
		origin: T::AccountId,
		virt_addr: T::Hash,
		gas_limit: u64,
		input_data: Vec<u8>,
	) -> sp_std::result::Result<Vec<u8>, DispatchError> {
		let deployed_addr = VirtToRealMap::<T>::get(&virt_addr)
			.ok_or(Error::<T>::DeployedAddrNotExist)?;
		let (exec_result, _) = Self::bare_call(
			origin,
			deployed_addr,
			Zero::zero(),
			gas_limit,
			input_data
		);
		let exec_return_value = match exec_result.map(|value| value) {
			Ok(value) => value,
			Err(e) => Err(e.error)?,
		};
		ensure!(exec_return_value.is_success(), Error::<T>::RevertedError);

		Ok(exec_return_value.data)
	}
```

```
Runtime Module 2
let is_finalized_result = celer_contracts::Module::<T>::call_contract_condition(
                caller.clone(),
                smart_contract_call_data.virt_addr,
                smart_contract_call_data.is_finalized_call_gas_limit,
                smart_contract_call_data.is_finalized_call_input_data,
)?;
let is_finalized: bool = bool::decode(&mut &is_finalized_result[..]).map_err(|_| Error::<T>::MustBeDecodable)?;
```
Error message is MustBeDecodable

**Comment by Robbepop** [comment]
Could you please reformulate your question as I cannot seem to understand what exactly you are asking for or what exactly your problem precisely is.

**Comment by thashimoto1998** [comment]
Question: 
According to pallet-contract API, we call `bare_call` API to call  a smart contract from the runtime module code and `bare_call` API return execution result. This execution result contains the encoded return value of the smart contract function. What format is encoded return value of the smart contract function? How do we decode encode return value correctly?

```
bare_call API
/// Perform a call to a specified ccontract.
///
/// It returns the execution result and the amount of used weight
pub fn bare_call(
	origin: T::AccountId,
	dest: T::AccountId,
	value: BalanceOf<T>,
	gas_limit: Gas,
	input_data: Vec<u8>,
) -> ContractExecResult {}
```

Error:
I called the function of smart contract that returns bool value and decoded it as follows code, but it was not decoded correctly.

```
let is_finalized: bool = bool::decode(&mut &is_finalized_result[..]).map_err(|_| Error::<T>::MustBeDecodable)?;
```

Smart contract function
```
#[ink(message)]
        pub fn is_finalized(&self, query: bool) -> bool {
            query 
        }

```

**Comment by HCastano** [comment]
@thashimoto1998 Sorry for taking so long to answer this!

The return type should be SCALE encoded. However, instead of trying to decode the `bool` I believe you need to decode the [`ContractExecResult`](https://github.com/paritytech/substrate/blob/7f09a7619c863c964a93ceb915d6e0b9ddc39e2e/frame/contracts/common/src/lib.rs#L61) and pull the [`result`](https://github.com/paritytech/substrate/blob/7f09a7619c863c964a93ceb915d6e0b9ddc39e2e/frame/contracts/common/src/lib.rs#L57) from there.

You'd need to change your code to be something like:

```rust
let is_finalized = ContractExecResult::decode(&mut &encoded_is_finalized_output[..]).unwrap().result;
```

Maybe @athei can double check here

**Comment by athei** [comment]
The `ContractExecResult` does not need to be decoded:

```rust
let result = pallet_contracts::bare_call(...);
let is_finalized: bool = encoded_is_finalized_output.result.unwrap().data().decode();
```

In any proper code you wouldn't call `unwrap()` of course.
