### ISSUE TITLE
Where is impl SpreadLayout for basic type ?

### ISSUE THREAD

**Issue by yjhmelody** [paritytech/ink#617]
I find every storage type impl the SpreadLayout. But all of them's inner type need to impl SpreadLayout excepting the `Memory` type. And obviously basic type can works. But where is impl SpreadLayout for basic type ?

Such as flipper example code generated by proc macro:
```rust
 fn push_spread(&self, __key_ptr: &mut ::ink_storage::traits::KeyPtr) {
                match self {
                    Flipper { value: __binding_0 } => {
                        ::ink_storage::traits::SpreadLayout::push_spread(
                            __binding_0,
                            __key_ptr,
                        );
                    }
                }
            }
```

`__binding_0` is bool type. but I search nothing about the impl.

**Comment by cmichi** [comment]
@yjhmelody You mean where the implementation of `SpreadLayout` for `bool` happens? 

We have [this macro](https://github.com/paritytech/ink/blob/master/crates/storage/src/traits/impls/prims.rs#L47-L56) which provides the implementation for a number of Rust primitives.

**Comment by yjhmelody** [comment]
@cmichi Thanks, I just find `impl_always_packed_layout`.
