### ISSUE TITLE
Public ChainExtension trait make it more flexible

### ISSUE THREAD

**Issue by tylerztl** [paritytech/ink#620]
`ChainExtension` trait is a great function, but I encountered a little problem when using it that i can't use it  out of `ink_env` because of it is not public.  I can't input ChainExtension instance when calling `register_chain_extension`

**Comment by Robbepop** [comment]
The chain extension implementation is under active development at the moment.
You can find more information about it here: https://github.com/paritytech/ink/pull/592
Please feel free to provide us with your ideas and proposals for improvements.

**Comment by tylerztl** [comment]
> The chain extension implementation is under active development at the moment.
> You can find more information about it here: #592
> Please feel free to provide us with your ideas and proposals for improvements.

Thanks!

**Comment by Robbepop** [comment]
Could you please describe the problems you have had while using the unfinished and unstable chain extensions feature in ink! ?
For example; I do not understand what exactly you mean by the `ChainExtension` trait because there is none.
There is only a `chain_extension` proc. macro and a `ChainExtension` associated type of the `Environment` trait in `ink_env`.

**Comment by tylerztl** [comment]
> Could you please describe the problems you have had while using the unfinished and unstable chain extensions feature in ink! ?
> For example; I do not understand what exactly you mean by the `ChainExtension` trait because there is none.
> There is only a `chain_extension` proc. macro and a `ChainExtension` associated type of the `Environment` trait in `ink_env`.

I plan to develop an independent tool library that relies on `ChainExtension`. Currently, the existing interface `onchain` can be implemented through public `call_chain_extension `, but the `offchain` method requires impl `ChainExtension` for custom struct, but the `ChainExtension` trait is private.

**Comment by Robbepop** [comment]
I think you are trying to use what currently exists for chain extensions in the `master` branch of ink!.
However, as already said we currently heavily develop this feature. The most advanced proposal for its ink! design can be found here:
https://github.com/paritytech/ink/pull/592#issuecomment-754782511

We are happy about suggestions based on the linked design proposal.

**Comment by Robbepop** [comment]
Closed due to missing reply. Will re-open once @tylerztl comes up with non-resolved outstanding issues here.
