### ISSUE TITLE
does ink support like EVM script? or contract call?

### ISSUE THREAD

**Issue by GalaIO** [paritytech/ink#634]
like this exec EVM script
https://github.com/aragon/aragon-apps/blob/631048d54b9cc71058abb8bd7c17f6738755d950/apps/voting/contracts/Voting.sol#L355

or call erc20 transferFrom
https://github.com/aragon/aragon-apps/blob/631048d54b9cc71058abb8bd7c17f6738755d950/apps/token-manager/contracts/TokenManager.sol#L318

**Comment by GalaIO** [comment]
@Robbepop @ascjones help, how to call another contract function  in ink!  call erc20 transferFrom
https://github.com/aragon/aragon-apps/blob/631048d54b9cc71058abb8bd7c17f6738755d950/apps/token-manager/contracts/TokenManager.sol#L318

**Comment by atenjin** [comment]
contracts call can do this.
But your solidity should be complied into WASM, currently the tool Solang can do this [https://github.com/hyperledger-labs/solang](https://github.com/hyperledger-labs/solang).

Our patract tool [Redspot](https://redspot.patract.io/) would add Solang plugin and provide a way to compile with ink together in future, currently not in plan now.

**Comment by GalaIO** [comment]
> contracts call can do this.
> But your solidity should be complied into WASM, currently the tool Solang can do this https://github.com/hyperledger-labs/solang.
> 
> Our patract tool [Redspot](https://redspot.patract.io/) would add Solang plugin and provide a way to compile with ink together in future, currently not in plan now.

how to call contract in pure ink, i found a example https://github.com/paritytech/ink/tree/master/examples/delegator , but it pass code_hash not the contract address.

**Comment by boyswan** [comment]
Here's an example
https://gist.github.com/hugopeixoto/aac7e632fb439b0f5ebdbd85db6a8f14

**Comment by hychen** [comment]
You'll need to use low level API `builld_call` until generic trait feature is implemented if the contract you want to call which implements traits.

I made another example of executing cross contract call via high level  API `FromAccounand::from_account_id` and low level API `build_call`.  Link is below:
https://github.com/hychen/redspot/tree/cross-contract-call/examples/cross-contract-call

**Comment by HCastano** [comment]
Closing since it looks answered
