### ISSUE TITLE
Add missing docs for ink_storage_derive proc. macros

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#637]
Documentation of them is currently missing entirely.
Also we want to provide an example per proc. macro for deriving a `struct` and an `enum`.

![2021-01-21-203301_1478x299_scrot](https://user-images.githubusercontent.com/8193155/105402584-e0354700-5c27-11eb-8afa-0c4c1402290e.png)

**Comment by cmichi** [comment]
I'm closing this issue, since the docs were added in https://github.com/paritytech/ink/commit/b66730ba6ead82e7d48431e311ed5ff758124203.
