### ISSUE TITLE
how to use chain extensions to read/write runtime storage

### ISSUE THREAD

**Issue by GalaIO** [paritytech/ink#640]
can give a example in ink/examples, and compile with cargo-contract

rel #592

**Comment by Robbepop** [comment]
An example is given in the docs here: https://paritytech.github.io/ink/ink_lang/attr.chain_extension.html#example-definition
Note that for chain extensions to work you also need to provide a definition on the runtime side.
The `#[ink::chain_extension]` marked traits acts as a bridge between runtime and smart contract.

**Comment by GalaIO** [comment]
> An example is given in the docs here: https://paritytech.github.io/ink/ink_lang/attr.chain_extension.html#example-definition
> Note that for chain extensions to work you also need to provide a definition on the runtime side.
> The `#[ink::chain_extension]` marked traits acts as a bridge between runtime and smart contract.

when I compile, get error https://github.com/paritytech/cargo-contract/issues/158

**Comment by ascjones** [comment]
As metntioned in that issue the `TypeInfo` derive is only for `std` `#[cfg_attr(feature = "std", derive(scale_info::TypeInfo))]`

**Comment by GalaIO** [comment]
> As metntioned in that issue the `TypeInfo` derive is only for `std` `#[cfg_attr(feature = "std", derive(scale_info::TypeInfo))]`

but it will be compiled to wasm.... have another solution?

**Comment by kuleleyokn42** [comment]
I have met the same problem, waiting for a solution. Thanks.

**Comment by ascjones** [comment]
> > As metntioned in that issue the `TypeInfo` derive is only for `std` `#[cfg_attr(feature = "std", derive(scale_info::TypeInfo))]`
> 
> but it will be compiled to wasm.... have another solution?

The `TypeInfo` is only required for metadata generation which is done in `std`. So this should work if you apply it to all your types.

If you *did* require the `TypeInfo` for whatever reason in the wasm environment then you could just remove `optional = true` from the `scale-info` dependency in your `Cargo.toml`. I don't think this is necessary in your case/

**Comment by GalaIO** [comment]
> optional = true

when compile, got
```bash
cargo +nightly contract build                     
ERROR: Error invoking `cargo metadata`

Caused by:
    failed to run `cargo metadata`: error: failed to parse manifest at `/Users/galaio/RustProjects/kylin-node/contracts/get_prices/Cargo.toml`
    
    Caused by:
      feature `std` includes `scale-info`, but `scale-info` is not an optional dependency
      A non-optional dependency of the same name is defined; consider adding `optional = true` to its definition.

```

It seems scale-info is neccessary;

**Comment by GalaIO** [comment]
> An example is given in the docs here: https://paritytech.github.io/ink/ink_lang/attr.chain_extension.html#example-definition
> Note that for chain extensions to work you also need to provide a definition on the runtime side.
> The `#[ink::chain_extension]` marked traits acts as a bridge between runtime and smart contract.

can ink give some compilable and runable example, like the example in ink/examples, https://github.com/paritytech/ink/tree/master/examples

**Comment by Robbepop** [comment]
> It seems scale-info is neccessary;

No the error tells you to remove `scale-info` from the `Cargo.toml` list of your `std` feature implications, that's all. ;)

> can ink give some compilable and runable example, like the example in ink/examples, https://github.com/paritytech/ink/tree/master/examples

We will be providing an example in the future! :)

**Comment by GalaIO** [comment]
> > It seems scale-info is neccessary;
> 
> No the error tells you to remove `scale-info` from the `Cargo.toml` list of your `std` feature implications, that's all. ;)
> 
> > can ink give some compilable and runable example, like the example in ink/examples, https://github.com/paritytech/ink/tree/master/examples
> 
> We will be providing an example in the future! :)

when? We're in a hurry in the project

**Comment by Robbepop** [comment]
Since the chain extension feature needs to be orchestrated between ink! and the contracts-pallet from Substrate we plan on delivering such an example and documentation with cross-concerns (not only for ink!) as soon as we ship the orchestrated release between contracts-pallet 3.0 and ink! 3.0 which is expected to happen in roughly 2 weeks without guarantee.

**Comment by GalaIO** [comment]
> Since the chain extension feature needs to be orchestrated between ink! and the contracts-pallet from Substrate we plan on delivering such an example and documentation with cross-concerns (not only for ink!) as soon as we ship the orchestrated release between contracts-pallet 3.0 and ink! 3.0 which is expected to happen in roughly 2 weeks without guarantee.

hi, How's it going?

**Comment by Robbepop** [comment]
https://github.com/paritytech/ink/tree/master/examples/rand-extension

**Comment by GalaIO** [comment]
> https://github.com/paritytech/ink/tree/master/examples/rand-extension

what version of pallet contract？not found in substrate v2.0.1

**Comment by Robbepop** [comment]
it uses ink! `master` and Substrate `master`.

**Comment by HCastano** [comment]
This seems pretty stale. @GalaIO feel free to re-open if you think this is unresolved
