### ISSUE TITLE
Issues with checked_div when using function parameters

### ISSUE THREAD

**Issue by paurosello** [paritytech/ink#642]
**Questions**

- Is this a bug concerning building of ink! smart contracts?
   No
- Is this a bug that appears when interacting with smart contracts via the Polkadot JS browser UI?
    No

It is a bug when trying to deploy the contract in a local node.

**FAQ**

- Are you using the nightly Rust channel to compile your smart contract?
Yes
- Are you using an up-to-date `cargo-contract`? Check via `cargo contract --version`.
cargo-contract 0.8.0
- Are you using an up-to-date ink! version in your smart contract?
ink_lang = { version = "3.0.0-rc2", default-features = false }

**Describe the bug**
- Create a new contract with `cargo contract new test`
- Add the following function:
```
        #[ink(message)]
        pub fn multiplication(&self, input1: Balance, input2: Balance) -> Balance {
            input1.checked_mul(input2).unwrap()
        }
```
- Build and upload via polkadot.js.org to local node, it will **succeed**.
- Add the following function:
```
        #[ink(message)]
        pub fn division(&self, input1: Balance, input2: Balance) -> Balance {
            input1.checked_div(input2).unwrap()
        }
```
- Build and upload via polkadot.js.org to local node, it will **fail**.
- Node DEBUG logs
```
2021-01-25 20:53:00.002  DEBUG tokio-runtime-worker runtime:DispatchError    
2021-01-25 20:53:00.002  DEBUG tokio-runtime-worker runtime:Invalid module for imported function    
2021-01-25 20:53:00.002  DEBUG tokio-runtime-worker runtime:PostInfo:     
2021-01-25 20:53:00.002  DEBUG tokio-runtime-worker runtime:actual_weight=    
2021-01-25 20:53:00.002  DEBUG tokio-runtime-worker runtime:max-weight    
2021-01-25 20:53:00.002  DEBUG tokio-runtime-worker runtime:pays_fee=    
2021-01-25 20:53:00.002  DEBUG tokio-runtime-worker runtime:Yes    
```

Other experiments:
**Works**
```
       #[ink(message)]
        pub fn division(&self) -> Balance {
            let input2: u128 = 10;
            let input1: u128 = 10;
            input1.checked_div(input2).unwrap()
        }
```
**Fail**
```
       #[ink(message)]
        pub fn division(&self, input2: Balance) -> Balance {
            let input1: u128 = 10;
            input2 / input1
        }
```
**Works** WAT?
```
       #[ink(message)]
        pub fn division(&self, input2: Balance) -> Balance {
            let input1: u128 = 10;
            input1 / input2
        }
```

I do not nee a difference between using '/' or checked_div func.

**Expected behavior**
Division should work fine

**Screenshots**
![image](https://user-images.githubusercontent.com/1133954/105758244-54852880-5f4f-11eb-95a4-c8251a7efd2f.png)

**Additional context**
Check additional discussion in: https://matrix.to/#/!tYUCYdSvSYPMjWNDDD:matrix.parity.io/$161159985517869MbkkG:matrix.org?via=matrix.parity.io&via=matrix.org&via=corepaper.org

**Comment by Robbepop** [comment]
Have you tried setting `overflow-checks = false` in your `Cargo.toml` under `[profile.release]` section?
There is a known Rust compiler bug that commonly causes this problem.

**Comment by paurosello** [comment]
that did the job! wow thanks :) 

Is there any drawback on using this? Is this a sane default for all contracts?

**Comment by Robbepop** [comment]
The drawback is that you do not have safe math by default if you disable `overflow-checks`. So you are back at Solidity level which is very unfortunate and we cannot really fix this in ink! since it is a Rust compiler bug.
The good side is that with those `checked_add` functions it is kinda easy to circumvent the fact that checks are no longer implicit.

**Comment by Robbepop** [comment]
Since this problem is resolved I'd like to close this issue. Ok?

**Comment by paurosello** [comment]
Yes sure! Will try to see if there any workaround that might work like leaving this function on its own contract and call it from a different place.
