### ISSUE TITLE
Provide off-chain tests for smart contract example: rand-extension

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#664]
We are currently missing some proper off-chain tests that utility the off-chains ability to emulate chain extension method calls.

**Comment by HCastano** [comment]
@hammeWang I've unassigned you, but feel free to open a PR for this if you wish.

**Comment by Robbepop** [comment]
Note that this has already happened: https://github.com/paritytech/ink/blob/master/examples/rand-extension/lib.rs#L68

Closed.
