### ISSUE TITLE
u128 checked_div  contracts.put_code error

### ISSUE THREAD

**Issue by z330789559** [paritytech/ink#666]
**Questions**

u128 checked_div  contracts.put_code error
if in ink contract ,you have codes that contain u128.checked_div(u128)  , when upload the wsam to chain ,it will case  other: unkouwn error ,

**Comment by Robbepop** [comment]
put `overflow-checks = false` into the `[profile.release]` section of your smart contract's `Cargo.toml` file.

**Comment by atenjin** [comment]
related to #636 
We advice to add `verflow-checks = false` in `cargo-contract` matadata parser process, so that developer do not need to put this in Cargo.toml

**Comment by cmichi** [comment]
In https://github.com/paritytech/cargo-contract/pull/171 we have implemented functionality now which makes `cargo-contract` recommend to add `overflow-checks = false` in case this particular issue is detected.

This detection is available in the latest `cargo-contract` master and will be in the next release.
