### ISSUE TITLE
[ci] Failing fuzz tests on master (02 Feb 2021)

### ISSUE THREAD

**Issue by devops-parity** [paritytech/ink#673]
The CI job [799290](https://gitlab.parity.io/parity/ink/-/jobs/799290) just failed.

The offending commit is [Do not stop CI stage on exit code 1](https://github.com/paritytech/ink/commit/2852f8c7feec6c8dfd4c0b94e06683b75f14f6ec).

**Comment by cmichi** [comment]
Created as a result of https://github.com/paritytech/ink/pull/671.
