### ISSUE TITLE
[ci] Failing fuzz tests on master (02 Feb 2021)

### ISSUE THREAD

**Issue by devops-parity** [paritytech/ink#674]
The CI job [799829](https://gitlab.parity.io/parity/ink/-/jobs/799829) just failed.

The offending commit is [Debug why no issue is created for failing fuzz test (#671)](https://github.com/paritytech/ink/commit/36c94019f9724f77154be55f0bf2ec02c2f12a77).

**Comment by cmichi** [comment]
This issue is expected. It's good that the automatic issue creation works now.

Next stop: Fix the actual issue which causes this.
