### ISSUE TITLE
Dont deploy contract

### ISSUE THREAD

**Issue by Daelon02** [paritytech/ink#679]
I write contact like in tutorial(https://substrate.dev/substrate-contracts-workshop/#/2/supporting-approvals-and-transfer-from)
But when I try to deploy contract, I have error 
![Screenshot_1](https://user-images.githubusercontent.com/63471940/106857869-773edc00-66c9-11eb-80ce-8be75e038749.png)

**Comment by cmichi** [comment]
@Daelon02 I just tried to reproduce your error, but for me deploying works fine. If you post the code of the contract which you are trying to deploy we can pinpoint the problem?

Also note that the tab `Potential Solution` in the workshop displays the code which should be working (that's also the code which I used for trying to reproduce your error). So you could also compare that code against the one you are trying to deploy.

**Comment by cmichi** [comment]
Closing this now as I think it should be fixed (see comment above). Feel free to comment otherwise.
