### ISSUE TITLE
Create template-contract project for CLI `contract new <name>`

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/ink#69]
Create a dedicated contract template (maybe flipper, maybe extend it) and have the CLI use this template to instantiate new projects.

This involves:

- [ ] Copying all the files
- [ ] Renaming the different parts of the project
- [ ] Other magic I can't think of atm...

Step 1 should be to simply update the CLI so that things are not broken as is.

**Comment by shawntabrizi** [comment]
This addresses step 1: https://github.com/paritytech/ink/pull/70

**Comment by ascjones** [comment]
Resolved by #90
