### ISSUE TITLE
Run test for ERC20 example

### ISSUE THREAD

**Issue by deadblackclover** [paritytech/ink#691]
When running the tests for the ERC20 contract from the example, various libraries are compiled for me.
And at this moment, the assembly stops with an error.

```
error [E0034]: multiple applicable items in scope
    -> /home/deadblackclover/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.20.1/src/order.rs:339:15
     |
339 | if ct == R :: BITS {
     | ^^^^ multiple `BITS` found
     |
note: candidate # 1 is defined in the trait `BitMemory`
```

And this is one of the many bugs that occur when building packages.

And if you use libraries not from the repository and replace the versions with versions from the cargo-contract template, then PrefixedValue does not work.

```
nightly-x86_64-unknown-linux-gnu (overridden by +toolchain on the command line)
rustc 1.52.0-nightly (8e54a2113 2021-02-13)

cargo-contract 0.8.0
```

**Comment by Robbepop** [comment]
Thanks for reporting. We are aware of this problem which is a problem with the transitively depended on `funty` dependency. We have created a hotfix for it which we will soon(TM) merge into ink! `master`.

**Comment by cmichi** [comment]
@deadblackclover We just merged a fix for this issue. Can you please try again with `master`?

**Comment by deadblackclover** [comment]
Great, now everything works. Thank!
