### ISSUE TITLE
examples-> delegator  execute build-all.sh failed

### ISSUE THREAD

**Issue by qaibeibei** [paritytech/ink#695]
![image](https://user-images.githubusercontent.com/42369700/108680954-76ab9f80-7529-11eb-82ef-39d2ef2911fb.png)

version 3.0.0

execute build-all.sh  An error occurred

**Comment by cmichi** [comment]
@qaibeibei Ah yeah, this is because our ink! master is compatible with `cargo-contract`'s `master`. Can you do a `cargo install --git https://github.com/paritytech/cargo-contract cargo-contract --force`?

This way you will be using the `master` of `cargo-contract`.

**Comment by qaibeibei** [comment]
> @qaibeibei啊，是因为我们的墨水！主是兼容`cargo-contract`的`master`。
> 
> 你可以做
> 
> ```
> cargo install --git https://github.com/paritytech/cargo-contract cargo-contract --force
> ```
> 
> ？你会使用这种方式`master`的`cargo-contract`。


![image](https://user-images.githubusercontent.com/42369700/108699516-4e7b6b00-7540-11eb-896a-ede49960fe6a.png)

How to install wasm-opt

**Comment by cmichi** [comment]
@qaibeibei See https://github.com/paritytech/cargo-contract#installation, if you're e.g. on Ubuntu `binaryen` is a package which you can install using `sudo apt-get install binaryen`.
