### ISSUE TITLE
The wasm-opt optimization failed

### ISSUE THREAD

**Issue by XSvr** [paritytech/ink#699]
when build examples\delegator  use build-all.sh
i got some error:

[1/5] Building cargo project
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /tmp/cargo-contract_AoDzPK/accumulator/Cargo.toml
workspace: /tmp/cargo-contract_AoDzPK/Cargo.toml
    Updating `https://mirrors.sjtug.sjtu.edu.cn/git/crates.io-index` index
    Finished release [optimized] target(s) in 1.22s
 [2/5] Post processing wasm file
 [3/5] Optimizing wasm file
ERROR: The wasm-opt optimization failed.
A possible source of error could be that you have an outdated binaryen package installed.

The error which wasm-opt returned was:
Unknown option '--zero-filled-memory'

is any thing miss?

**Comment by cmichi** [comment]
@XSvr Your locally installed `binaryen` package is outdated. If you execute `wasm-opt --version` it should return a number > 98.

**Comment by XSvr** [comment]
@cmichi 
how to update  wasm-opt

**Comment by leeduckgo** [comment]
same problem
and `wasm-opt --version` is useless.
![Uploading image.png…]()

**Comment by cmichi** [comment]
@leeduckgo I think this flag `--version` was only introduced from a certain version on in that tool. So you most probably have an outdated version of that package.

What is your operating system? For example `binaryen` (which contains that tool) is a package for [Debian/Ubuntu](https://tracker.debian.org/pkg/binaryen), [Homebrew](https://formulae.brew.sh/formula/binaryen) and [Arch Linux](https://archlinux.org/packages/community/x86_64/binaryen/).
