### ISSUE TITLE
DuplicateTopics error when emitting event with equal values in topics

### ISSUE THREAD

**Issue by usetech-llc** [paritytech/ink#704]
**FAQ**

- Are you using the nightly Rust channel to compile your smart contract?
Yes, nightly-2021-01-15

- Are you using an up-to-date `cargo-contract`? Check via `cargo contract --version`.
    - If you are unsure please tell us your version noted there.
cargo contract 0.8.0

- Are you using an up-to-date ink! version in your smart contract?
    - You can check this by looking into the `[dependencies]` section of your `Cargo.toml`.
    - If you are unsure please tell us your version noted there.

v3.0.0-rc2

**Describe the bug**
When I post this event:
```
            Self::env().emit_event(WithdrawNFT {
                address: user,
                collection_id,
                token_id,
            });
```

with collection_id = 1 and token_id = 1, I get DuplicateTopics error. But when I change token ID to 2, I don't get it, transaction runs OK.

**Comment by cmichi** [comment]
@usetech-llc Thanks for the bug report! I'm having a hard time replicating it though. I used [this contract](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3774835f8e608bd0728ed5fc7651d3b0) as a minimal example and can't provoke the error. I'm using the [flipper/Cargo.toml](https://github.com/paritytech/ink/blob/master/examples/flipper/Cargo.toml), the [canvas-node](https://github.com/paritytech/canvas-node) as the Substrate instance, and the [Canvas UI](https://paritytech.github.io/canvas-ui/#/) for deployment.

Could you give some more details? What version of Substrate and ink! are you using? Your `Cargo.toml` contains information about the ink! versions.

What are the data types of `collection_id` and `token_id`?

**Comment by athei** [comment]
Isn't that #594? Those changes are in master but unreleased.

**Comment by usetech-llc** [comment]
We are using older (January ~8) version of Contracts pallet, but updating it at the moment. When we are done with update, I'll test it again and let you know, thanks!

**Comment by athei** [comment]
The problem isn't the old version of the pallet. The bug was in ink!. If you are using v3.0.0-rc2 the fix is not in.

**Comment by usetech-llc** [comment]
I see, thanks! Do you have any plans to release rc3 or the final release 3.0?

**Comment by cmichi** [comment]
@usetech-llc Yes, we want to do a rc3 asap. At the moment we are just waiting for a bug in our `bitvec` dependency to be fixed. This requires a nasty hotfix in every `Cargo.toml` and we don't want to require users to apply that hotfix in order for our rc3 to work.

@athei Good catch!
