### ISSUE TITLE
Resolve confusion of #[test] vs. #[ink::test]

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink#714]
Escalated from https://github.com/paritytech/cargo-contract/pull/190.

## Problem
There is often confusion when to use `#[test]` vs. `#[ink::test]`.

The implication of `#[ink::test]` is that the test annotated with it is run in a emulated chain environment (we call this "off-chain testing"). This comes with a bit of overhead for spawning this emulation. This emulation is not needed for every test, only for the ones where e.g. chain storage or the `env()` API is involved.

For users starting out with ink! it can be hard to know when it's necessary to have an emulated chain, which can result in strange errors if `#[test]` is used but an emulation is necessary.

## Proposals

1. Just replace `#[test]` with `#[ink::test]` for every single test and live with the slight performance overhead.
1. Improve naming and split attribute like this:
    ```
    #[test]
    #[ink::emulate_chain]
    fn foo_test() { ... }
    ```
  
## My opinion

My opinion is that we will always have this issue as long as we use different attributes for tests which require an emulated chain and ones which don't. I would just replace `#[test]` with `#[ink::test]` in all examples and public documentation and trade a slight decrease in performance for an improved UX with less friction.

**Comment by hychen** [comment]
I prefer proposal#1. As a developer who builds something on ink!, I'll assume I should always use [ink!...] macros provided by ink! everywhere as minimum build blocks of my smart contracts. To figure out when to use #[test], when to use #[ink:test] is kind of an abstract leak to me.

**Comment by cmichi** [comment]
All necessary repos have been adapted, closing this issue.
