### ISSUE TITLE
vers 0.8.0 or vers 0.7.0

### ISSUE THREAD

**Issue by J-Cook-jr** [paritytech/ink#725]
On substrate.dev, the ink docs recommend using 0.8.0 but I'm not sure if this version is the most stable version. Should I use 0.7.0 or go with 0.8.0 . There is a lot of info out there but I can't find any clarity on which version is the best to use. I'm asking because I started building a substrate-node-template which has a current version of 3.0.0 but I started running into issues later during the building process. So, I ended up falling back to v2.0.1 and that allowed me to follow the substrate.dev tutorials without running into issues. Is ink setup the same way? Is there a specific version of I should be using to avoid compilation issues or what? Please let me know. Thanks!

**Comment by cmichi** [comment]
@J-Cook-jr Thanks for writing the issue, we've updated the workshop by now to better reflect the versions. It's best to use the most recent released versions, at the time of writing this is:
* ink! ‒ `3.0.0-rc3`
* `cargo-contract` ‒ `0.11.1`
* `canvas-node` ‒ `0.1.5`

You can find installation instructions with these version numbers in the workshop or [here on our documentation portal](https://paritytech.github.io/ink-docs/getting-started/setup).

I'm closing the issue for now, if you still encounter issues they are most likely bugs we don't know about. In this case please create another issue :-).
