### ISSUE TITLE
test cross-contract calling

### ISSUE THREAD

**Issue by master-davidlee** [paritytech/ink#726]
I've seen the "example/delegator" contract
is there any way I can write some tests for this kind of contract?

**Comment by J-Cook-jr** [comment]
Is any of this stuff working for anyone? All I'm running into is compatibility issues across all platforms. ink!, substrate, parity, polkadot etc.... Is there straight forward tutorial where everything is compatible or any solutions at all? I NEED HELP!!! Thanks!

**Comment by Robbepop** [comment]
Hi, sorry for the bad compatibility experiences you have.

ink! 3.0-rc3 is compatible with

    The cargo-contract CLI tool version 0.10.0 or newer.
        Install newest version using cargo install --force cargo-contract.
    Substrate version 3.0 including the contracts-pallet version 3.0.
