### ISSUE TITLE
Memory usage problem

### ISSUE THREAD

**Issue by qaibeibei** [paritytech/ink#729]
![image](https://user-images.githubusercontent.com/42369700/110652725-97494a00-81f7-11eb-8037-ddbb00027955.png)
![image](https://user-images.githubusercontent.com/42369700/110652778-a4663900-81f7-11eb-878e-c855f81fe229.png)
![image](https://user-images.githubusercontent.com/42369700/110652850-b516af00-81f7-11eb-9249-074600ebb543.png)

Memory test, need a very fast operation process, but very slow.  Is it used in the wrong way?

**Comment by Robbepop** [comment]
You should not use `ink_storage` data structures as generic parameter of an `ink_storage::Memory` type since `ink_storage` data structures usually incur overhead for being lazy, caching and storage optimized data structures. Instead try using a normal Rust `HashMap` (via `hashbrown`) or `BTreeMap` instead.

**Comment by qaibeibei** [comment]
> You should not use `ink_storage` data structures as generic parameter of an `ink_storage::Memory` type since `ink_storage` data structures usually incur overhead for being lazy, caching and storage optimized data structures. Instead try using a normal Rust `HashMap` (via `hashbrown`) or `BTreeMap` instead.
> 
> Also note that `.cloned()` should be replaced with `.copied()` in `inner.get(&account).cloned()`.
> And remember that `AccountId` still is a 32-byte big type so it is expected that operations are not as fast as ... let's say if you were using tiny `u32` primitives instead. Most hash table implementations are optimized for small key types.

How to introduce rust HashMap into Prelude ?

**Comment by Robbepop** [comment]
The big problem with Rust's `HashMap` is that it is not compatible with `no_std` environments such as WebAssembly to which ink! smart contracts compile. This is why you cannot find `HashMap` in ink!'s prelude. However, there is a Rust crate called `hashbrown` (https://crates.io/crates/hashbrown) which has built-in support for `no_std` environments. I personally encourage you to use Rust's `BTreeMap` that we expose via `ink_prelude` but if you really want to make use of a hash table instead here are the points to follow:

Add `hashbrown` as dependency to your ink! smart contract `Cargo.toml`:
```toml
[dependencies]
hashbrown = "0.9.1"
```
Then you can use `HashMap` from the `hashbrown` crate as follows:
```rust
use hashbrown::HashMap;

// Either via the import above:
fn foo() -> HashMap<i32, String> { .. }

// Or without the need of an import:
fn foo() -> hashbrown::HashMap<i32, String> { .. }
```
Note that in the above example `i32` key and `String` value are just demonstrative examples. Insert your own types.
As long as `hashbrown::HashMap` is used within `ink_storage::Memory<hashbrown::HashMap>` no further adjustments are required.

**Comment by XSvr** [comment]
> You should not use `ink_storage` data structures as generic parameter of an `ink_storage::Memory` type since `ink_storage` data structures usually incur overhead for being lazy, caching and storage optimized data structures. Instead try using a normal Rust `HashMap` (via `hashbrown`) or `BTreeMap` instead.
> 
> Also note that `.cloned()` should be replaced with `.copied()` in `inner.get(&account).cloned()`.
> And remember that `AccountId` still is a 32-byte big type so it is expected that operations are not as fast as ... let's say if you were using tiny `u32` primitives instead. Most hash table implementations are optimized for small key types.

normal accountid is used as an index key, is it  way convert to tiny  'u32'?

**Comment by Robbepop** [comment]
> > You should not use `ink_storage` data structures as generic parameter of an `ink_storage::Memory` type since `ink_storage` data structures usually incur overhead for being lazy, caching and storage optimized data structures. Instead try using a normal Rust `HashMap` (via `hashbrown`) or `BTreeMap` instead.
> > Also note that `.cloned()` should be replaced with `.copied()` in `inner.get(&account).cloned()`.
> > And remember that `AccountId` still is a 32-byte big type so it is expected that operations are not as fast as ... let's say if you were using tiny `u32` primitives instead. Most hash table implementations are optimized for small key types.
> 
> normal accountid is used as an index key, is it way convert to tiny 'u32'?

not without loss of information.
