### ISSUE TITLE
Make env.* also available for non message functions

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#74]
# Current Situation

Access to `env.*` (e.g. `env.caller()`) is only granted to message functions that have been marked as `pub(external)` but not for other functions such as common helper or utility functions.

# Design Rationale

The reason for this is that one of the design goals of ink! was to not touch user code within implementations while also providing a safe (`ink_model` like) way to access the environment. This is done by serving the environment as `&Env` or `&mut Env` giving restricted access to its features for safe usage.

# Current Implementation

For `pub(external)` messages we currently simply extend its parameter set by another `env: &EnvHandler` right after the `&self` or `&mut self`. This is non critical there because we currently do not allow to call message functions from within the contract which is why we flag it using `pub(external)` which reads as "public but only for external users" inherited from the `pub(restricted)` syntax of Rust.

# The Problem: Code Inspection & Transformation

If we also extended functions the same way that are callable from within the same contract we would have the problem that we would need to adjust calling code to add the additional `env` parameter. In theory this requires semantics checks to be done right that are not available during `ink_lang` passes so we need another approach.

# Current Workaround

https://github.com/paritytech/ink/wiki/FAQ#how-to-use-env-in-non-message-functions

# Solution

## Avoiding function body instrumentation

Has yet to be found!

## Involving function body instrumentation

In messages as well as functions we could search and replace `self.{msg_name|fn_name}(..)`
with `self.{msg_name|fn_name}(env, ..)` and add the `env` parameter to all method definitions just like it is already done for the message definitions.
I currently see no breakage here as long as we respect scoping rules correctly.
For example this will break if we disrespect scoping rules here:
```rust
contract! {
    struct MyContract { ... }
    ...
    impl MyContract {
        pub(external) fn my_message() {
            self.my_method() // Implicitely propagates `env` here
            fn local_fn(self: &Self) {
                self.my_method() // BREAKS! if we disrespect scoping rules (hard)
            }
            let this = self;
            this.my_method(); // HARD! we might not be able to detect this -> failure
        }
 
        fn my_method() {
            let caller = env.caller(); // Using `env.*` here
            ...
        }
    }
}
```

So the general conclusion in my opinion (@Robbepop) is that we really want to avoid having to instrument code within messages and functions in order to get anything like this to be working.

**Comment by Robbepop** [comment]
I was thinking about this today again.
The current major problem is that we want the `env` syntax on the one hand but do not want to make changes to internal code on the other hand.

For this we need to generate special code that handles this efficiently:

```rust
// Concerning this contract code:


contract! {
    struct OwnedValue {
        owner: AccountId,
        value: storage::Value<i32>,
    }

    impl Deploy for OwnedValue {
        fn deploy(&mut self) {
            self.owner = env.caller();
        }
    }

    impl OwnedValue {
        pub(external) fn get(&self) -> Option<i32> {
            self.get_impl()
        }

        pub(external) fn set(&mut self, to: i32) {
            self.set_impl()
        }
    }

    impl OwnedValue {
        fn get_impl(&self) -> Option<i32> {
            if env.caller() != self.owner {
                return None
            }
            *self.value
        }

        fn set_impl(&mut self, to: i32) {
            if env.caller() != self.owner {
                return;
            }
            *self.value = to;
        }
    }
}

// This is what could be generated to solve the problem:

struct OwnedValue<'a> {
    owner: AccountId,
    value: storage::Value<i32>,
    env: &'a mut ink_model::EnvHandler,
}

impl<'a> OwnedValue<'a> {
    pub fn get(&self) -> Option<i32> {
        let env = &self.env;
        {
            self.get_impl()
        }
    }

    pub fn set(&mut self, to: i32) {
        let env = &mut self.env;
        {
            self.set_impl(to)
        }
    }
}

impl<'a> OwnedValue<'a> {
    fn get_impl(&self) -> Option<i32> {
        let env = &self.env;
        {
            if env.caller() != self.owner {
                return None
            }
            *self.value
        }
    }

    fn set_impl(&mut self, to: i32) {
        let env = &mut self.env;
        {
            if env.caller() != self.owner {
                return;
            }
            *self.value = to;
        }
    }
}
```

**Comment by shawntabrizi** [comment]
Having read through this, I am a fan of abstracting this from the user through macro magic, but I also understand that this is quite intrusive to the code.

I think the middle ground option of having the user explicitly include an `env` parameter, but we take care of the nasty type is a reasonable option for the time being.

So this:

```
fn transfer_impl(&mut self, env: &mut ink_model::EnvHandler, from: AccountId, to: AccountId, value: Balance) -> bool {}
```

Would become:


```
fn transfer_impl(&mut self, env, from: AccountId, to: AccountId, value: Balance) -> bool {}
```

and called like:

```
self.transfer_impl(env, from, to, value)
```

**Comment by holygits** [comment]
This may be an over simplification but can't you just include `env` in a sort of ink std prelude?

**Comment by Robbepop** [comment]
This is going to be implemented through implementing https://github.com/paritytech/ink/issues/181.
