### ISSUE TITLE
Identical calls executing instantiation of a sub contract fail if made from a message call, succeed from another constructor

### ISSUE THREAD

**Issue by vminkov** [paritytech/ink#740]
Using ink! 3.0.0-rc3 , it always results in ContractTrapped when trying to instantiate a contract (like the delegator example) from an `#[ink(message)]` call. The same exact code succeeds when attempted to instantiate from a constructor.
Different salt is used every time, increased block size and weight - it still says ContractTrapped with no details for the error.
 
I am attaching a repo that reproduces the case with Mocha (polkadot.js) test cases. 

https://github.com/vminkov/ink-substrate-issue

**Comment by vminkov** [comment]
found the problem, deploy() needs to be payable

**Comment by forgetso** [comment]
This should be the error message instead of `ContractTrapped`!

**Comment by cmichi** [comment]
@forgetso I looked into this issue and `payable` is not actually required. If you have some sample contract I could look into why the contract fails. In general I would recommend running your node with `--tmp --dev -lerror,runtime::contracts=debug`. This way you would e.g. see output like `panicked at 'failed at instantiating the new `sub` contract: CodeNotFound'` on the console for the ink! message (no output is currently shown for constructors).

@vminkov I got your `ink-substrate-issue` contract to work with something along those lines:
```rust
fn internal_deploy(&mut self, init_val: u32, version: u32, code_hash: Hash) -> Subcontract {
    let total_balance = self.env().balance();
    let salt = version.to_le_bytes();
    Subcontract::new(init_val)
        .endowment(total_balance / 2)
        .code_hash(code_hash)
        .salt_bytes(salt)
        .instantiate()
        .expect("failed at instantiating the new `sub` contract")
}

#[ink(message)]
pub fn deploy(&mut self, version: u32, code_hash: Hash) {
    let subcontract = self.internal_deploy(1111, version, code_hash);
    self.from_method = ToAccountId::to_account_id(&subcontract);
}
```
I had to modify the testing contract in your repo though. If uses `let total_balance = Self::env().balance();` in a method which is called by a constructor as well as a message (so should be `self.env().balance` for the message). But `Self` is also not passed to the method.

**Comment by forgetso** [comment]
Thanks for investigating @cmichi. I'm running into this issue again and I'm using the contracts node with `substrate-contracts-node --dev --tmp --unsafe-ws-external --rpc-cors all --ws-port=9944 -lerror,runtime::contracts=debug` but I don't get anything printed at all. The ink! function I'm calling has lines like `ink_env::debug_println!("{:?}", caller);`. Any thoughts on why nothing appears in the terminal?

**Comment by forgetso** [comment]
Hi @cmichi , I've found a reproducible example of `ContractTrapped` appearing when `payable` is not added as a decorator.

If you take this repos contract: https://github.com/prosopo-io/protocol/blob/master/contracts/lib.rs

And remove the `payable` function from this function:

```
        // Stake and activate the provider's service
        #[ink(message)]
        #[ink(payable)]
        pub fn provider_stake(&mut self) -> Result<(), ProsopoError> {
```

You get `ContractTrapped`. Add it back in and it works fine.

Reproducing this requires a fair amount of cloning repos and setup. The instructions are included in the readme [here](https://github.com/prosopo-io/provider).

```
rustup --version
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.56.1 (59eed8a2a 2021-11-01)`
```

**Comment by xgreenx** [comment]
@forgetso This function requires the user to send the native token to it. If you send tokens to function without payable decorate, you will get contract trapped(or in case of debug mode you will see an error about the reason for the trap).

<img width="1098" alt="image" src="https://user-images.githubusercontent.com/18346821/142402275-ee8f006a-6d48-4872-986c-412b7a5b63dd.png">

**Comment by forgetso** [comment]
Ok, well that's good to know. I'm still building in `release` mode due to the contract size. I will change my node so that I can deploy the full size contract and get these more helpful messages!

**Comment by xgreenx** [comment]
> Ok, well that's good to know. I'm still building in `release` mode due to the contract size. I will change my node so that I can deploy the full size contract and get these more helpful messages!

I suggest you comment empty functions and start to use `ink_storage::lazy::Mapping` instead of `InkHashMap`=)

**Comment by forgetso** [comment]
I thought `Mapping` was still a work in progress. Nice to hear it's available. Thanks for all the tips!
