### ISSUE TITLE
Error() from core::result::Result<T, Error> should result in reversion of the state changes of a transaction

### ISSUE THREAD

**Issue by vminkov** [paritytech/ink#745]
Currently the return values such as core::result::Result<T, Error> are ignored 

As @naps62 wrote earlier [here](https://matrix.to/#/!tYUCYdSvSYPMjWNDDD:matrix.parity.io/$1616600415978CiSyE:corepaper.org?via=matrix.parity.io&via=matrix.org&via=corepaper.org)
> looking at the official example for the ERC721 implementation, this is a snippet of the `transfer` call:

```
            self.remove_token_from(from, id)?;
            self.add_token_to(to, id)?;
            self.env().emit_event(Transfer {
                from: Some(*from),
                to: Some(*to),
                id,
            });
            Ok(())
```

> So does it mean it could, in theory, succeed with `remove_token_from` but then fail on `add_token_to` resulting in an inconsistent state?

The current only way to revert the state change is with panics, which isn't a graceful way to do that. We need a way to handle error messages and  `core::result::Result<T, Error>` is good enough for this.

**Comment by vminkov** [comment]
Can we have the ability to define our own error handling logic, like this

```
impl<T> std::ops::Try for LoggedResult<T, Error> {
    type Ok = T;
    type Error = Error;
    #[inline]
    fn into_result(self) -> Self {
        self
    }
    #[inline]
    fn from_error(v: Error) -> Self {
        // here is my custom error handling
        Self::env().emit_event( ErrorEvent {
            message: "logged error".into()
        });
        LoggedResult::Err(v)
    }
    #[inline]
    fn from_ok(v: T) -> Self {
        LoggedResult::Ok(v)
    }
}
```

**Comment by vminkov** [comment]
@hychen , we also refer to the same problem here  
(original issue : paritytech/ink#641 )

**Comment by HCastano** [comment]
Closing in favour of #641.
