### ISSUE TITLE
how to send unit balance where call contract function?

### ISSUE THREAD

**Issue by GalaIO** [paritytech/ink#748]
like eth, we can call contract function with msg.value(it's eth to contract), how about on ink! and substrate?

**Comment by HCastano** [comment]
@GalaIO During the process of [building a call](https://paritytech.github.io/ink/ink_env/call/fn.build_call.html) you should be able to use the [`transferred_value()`](https://paritytech.github.io/ink/ink_env/call/struct.CallBuilder.html#method.transferred_value) method to achieve this.

**Comment by GalaIO** [comment]
> @GalaIO During the process of [building a call](https://paritytech.github.io/ink/ink_env/call/fn.build_call.html) you should be able to use the [`transferred_value()`](https://paritytech.github.io/ink/ink_env/call/struct.CallBuilder.html#method.transferred_value) method to achieve this.

hi  how to achieve on polkadot.js api?
