### ISSUE TITLE
send cross chain message from ink contract

### ISSUE THREAD

**Issue by master-davidlee** [paritytech/ink#757]
Can we send cross-chain message from ink contract?

**Comment by RoyTimes** [comment]
I'm no expert on this topic but you might wanna check out https://github.com/Ink-Bridge

**Comment by ascjones** [comment]
I'm assuming that the way to do this would be to provide a [chain extension](https://github.com/paritytech/ink/pull/592) which would allow sending of cross chain messages. I've not looked into this too deeply yet, but that is the first avenue I would investigate.

**Comment by HCastano** [comment]
@master-davidlee Like Andrew said, your starting point should be chain extensions. What you do afterwards depends on the specific type of chain you want to connect to.

For example, if your chain is a part of the Polkadot ecosystem you should be able to hook into the [XCM](https://github.com/paritytech/polkadot/tree/master/xcm/pallet-xcm) pallet. If it's not part of Polkadot but still built on Substrate you may use some of the code in [`parity-bridges-common`](https://github.com/paritytech/parity-bridges-common), such as the [messaging pallet](https://github.com/paritytech/parity-bridges-common/tree/master/modules/messages).
