### ISSUE TITLE
Why the hash strategy of allowances and balances in erc20 are exactly the same

### ISSUE THREAD

**Issue by yjhmelody** [paritytech/ink#758]
I’m curious whether storing data in this way will cause conflicts? If not, how to avoid it.

Is it because the globally incremented `offset` is still used?

**Comment by HCastano** [comment]
@yjhmelody I don't quite understand your question. Are you asking why entries of `balance` and `allowances` in the struct below don't overlap with each other, or are you asking about items within each field (so why keys in an `ink_storage::collection::HashMap<K, V>` don't conflict?

```rust
    #[ink(storage)]
    pub struct Erc20 {
        /// Total token supply.
        total_supply: Lazy<Balance>,
        /// Mapping from owner to number of owned token.
        balances: StorageHashMap<AccountId, Balance>,
        /// Mapping of the token amount which an account is allowed to withdraw
        /// from another account.
        allowances: StorageHashMap<(AccountId, AccountId), Balance>,
    }
```

**Comment by Robbepop** [comment]
> Is it because the globally incremented offset is still used?

From how I understand your question: Yes, that increment solves all the conflicts usually.

**Comment by cmichi** [comment]
I'll close the issue, since it is inactive since a while and my understanding is that the question has been answered.
