### ISSUE TITLE
Research and implement new `layout` metadata format

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink#767]
Blocker for https://github.com/paritytech/cargo-contract/issues/101.

I'm just copy/pasting from the discussion there:

>The current metadata format cannot represent some more or less common scenarios and really needs some restructuring. When I tried some weeks ago I immediately hit a wall for recursive data structures.
>
>We first have to define semantics, definitions and structures for a new and better `layout` metadata section before we should tackle this issue. We have to think about cases like:
>
>- recursively defined data structures such as `enum Tree { Leaf(i32), Node(Box<Tree>, Box<Tree>) }` or in case of `ink_storage`: `ink_storage::Vec<ink_storage::Vec<i32>>`, packed elements where some elements actually have some further pointers `Pack<(i32, ink_storage::Box<i32>)` and more.
>
>Maybe we have to restrict the final metadata to not support certain use cases because their metadata format would become too complex otherwise.

**Comment by HCastano** [comment]
In https://github.com/paritytech/ink/pull/1331 we updated the how the storage was defined in the metadata. I believe it should be parsable now, allowing to work on https://github.com/paritytech/cargo-contract/issues/101.

cc @xermicus
