### ISSUE TITLE
Create instances of *Spec types for any Form type

### ISSUE THREAD

**Issue by mattsse** [paritytech/ink#770]
It seems that currently creating instances `*Spec` types (`MessageSpec`, `ConstructorSpec`) is only possible for `F = MetaForm`, hence creating the corresponding builders is limited to `&'static str`. 

Is there a specific reason for that restriction? This could probably be easily mitigated by implementing the builder constructors within a generic implementation, like:

```rust
impl<F:Form> MessageSpec<F> {
    
  pub fn from_name(name: F::String) -> MessageSpecBuilder<F> {...}

```

instead of 

```rust

impl MessageSpec {
  pub fn from_name(name: &'static str) -> MessageSpecBuilder {...}
}
```

**Comment by HCastano** [comment]
Not sure, maybe @ascjones or @Robbepop can answer this?

**Comment by ascjones** [comment]
The `PortableForm` is intended only to be constructed at runtime internally by `scale-info`.

However we could add those generic builder implementations if there is a valid use case, off the top of my head it might be useful for testing.

**Comment by SkymanOne** [comment]
The question seems to be answered. Closing the issue due to inactivity
