### ISSUE TITLE
Add metadata information of how selector hashes have been produced

### ISSUE THREAD

**Issue by yjhmelody** [paritytech/ink#777]
At present, what I think about is that the generated information about the `selector` should be added, such as adding a `selectorHash` to provide the hash algorithm used, if it is directly specified by the user, it is "none" value.  If the hash currently supported by ink is blake256, the value is "blake256".

In addition, there is the `event` https://github.com/paritytech/ink/issues/759 mentioned earlier. I personally think that an `id` should be added to mark the `Event` instead of relying on the order. Beacuse  the order is very unfriendly to events that are reused by multiple contracts.

**Comment by Robbepop** [comment]
Hi @yjhmelody , can you tell us a bit about the use case for storing the hash algorithm into the metadata instead of just relying on a single fixed hash algorithm for all contracts?

**Comment by yjhmelody** [comment]
Who knows, it’s always beneficial to provide more information. At least I want to know how this selector comes. If some websites want to check metadata and contracts more strictly, they can hash `name` according to the specification to check whether the selector is generated correctly.

**Comment by yjhmelody** [comment]
For example, I don’t know if this is appropriate. If metadata.json is modified later. A function called by selector A is message B, and their parameters are just compatible.

**Comment by Robbepop** [comment]
In ink! there is no message overloading so a message or constructor is uniquely identified by its identifier which is the only thing that ink! currently uses for generating the selector hashes. However, for trait implementations this is a bit more complex since we need to support traits with overlapping message signatures.

**Comment by yjhmelody** [comment]
Well, I found that if the chain can guarantee a one-to-one relationship between the contract and metadata, for example, pallet-contract can store the hash of metadata.json, then selectorHash is really irrelevant.

**Comment by Robbepop** [comment]
Hmm, ... so far we only have this single `code_hash` to be able to verify a Wasm blob from within a metadata file. However, not vice versa. Maybe it is possible to store this hash onto the chain but I am not sure whether this is actually useful since the chain itself would not profit from this information and therefore the information should not be stored there.

**Comment by yjhmelody** [comment]
> Hmm, ... so far we only have this single `code_hash` to be able to verify a Wasm blob from within a metadata file. However, not vice versa. Maybe it is possible to store this hash onto the chain but I am not sure whether this is actually useful since the chain itself would not profit from this information and therefore the information should not be stored there.

If metadata.json is always required for the smart contract of the pallect-contract system, a metadata_hash should be provided, which is very helpful, and a third party needs to obtain it to verify whether the metadata has been modified.

**Comment by Robbepop** [comment]
Another solution is to put code hash of the associated metadata into the Wasm blob custom section.

**Comment by yjhmelody** [comment]
> Another solution is to put code hash of the associated metadata into the Wasm blob custom section.

This is impossible. Here is wasm first and then metadata.
If there is metadata first, then the Wasm blob custom section is undefined

**Comment by Robbepop** [comment]
> And it is impossible for Wasm to know its own code_hash when compiling.

For that we have our `cargo-contract` tool that can manage this well.

**Comment by yjhmelody** [comment]
> > And it is impossible for Wasm to know its own code_hash when compiling.
> 
> 
> 
> For that we have our `cargo-contract` tool that can manage this well.
> 
> But you are right that it will be very important to get the hashes right in combination.

metadata has wasm code hash，if wasm has metadata hash，there is dependency loop. So we need to split wasm code and metadata hash to two places

**Comment by HCastano** [comment]
@Robbepop @yjhmelody Do you guys have any next steps in mind here, or can I close this?

From my point of view it looks like your concerns should be covered with https://github.com/paritytech/ink/issues/806 and https://github.com/paritytech/ink/issues/759.

**Comment by yjhmelody** [comment]
> @Robbepop @yjhmelody Do you guys have any next steps in mind here, or can I close this?
> 
> From my point of view it looks like your concerns should be covered with #806 and #759.

What this issue wants to discuss now is that the hash value of metadata needs to be stored on the chain together with the contract.

**Comment by Robbepop** [comment]
From what i can remember I spoke with @athei about this and we came to the solution that the simplest path forward is to put this hash for metadata in a Wasm custom section of the compiled contract. Then this hash lives on the chain, third party tools can inspect and check against it. This will guard against changes of the associated metadata.

**Comment by athei** [comment]
Yes. It could be implemented with this: https://github.com/paritytech/substrate/issues/8423

By doing this the information stored there is transparent to pallet_contracts and semantics can be defined by user space.

**Comment by athei** [comment]
The title of the issue does not match what is discussed here. And to the discussion I say: Everything but deterministic compilation does not protect you. What if the Wasm lies about its metadata hash?
