### ISSUE TITLE
Why Packed collection still call functions of PackedLayout for its sub fields

### ISSUE THREAD

**Issue by yjhmelody** [paritytech/ink#779]
For Packed data, its PackedLayout implementation will recursively call the PackedLayout method for its subfields. What's the point of this?

Packed data relies on SpreadLayout to implement specific logic (forward_xxx_packed), while PackedLayout just keeps calling subfield methods.

If the current data structure is defined as Packed (such as Std Vec), what is the purpose of its continued recursion?
```rust
for elem in self {
    <T as PackedLayout>::push_packed(elem, at)
}
```

**Comment by Robbepop** [comment]
It allows some types to react to being pushed/pulled within a packed representation. This is for example very important for the storage `Box` type that allows to go from packed to spread layout again.

**Comment by yjhmelody** [comment]
I want to confirm one thing, if I define a type and implement PackedLayout without content for it (SpreadLayout is automatically derived), generally speaking, there will be no problems? (Except for the Box type you mentioned)

**Comment by Robbepop** [comment]
you generally are adviced to use the derive implementations. but if your type is non generic and has no fields that require special treatment for pushing and pulling then, yes, an empty implementation of packed layout should be fine.

**Comment by HCastano** [comment]
@yjhmelody This seems answered to me, feel free to open if you don't think so
