### ISSUE TITLE
Provide Gitpod support for all ink! Examples

### ISSUE THREAD

**Issue by adibhanna** [paritytech/ink#785]
I recently worked on creating a [Gitpod playground ](https://github.com/paritytech/ink-playgroung-flipper)that provides zero-config environment to work with ink! using the Flipper contract example. 

I would like to add support for all ink! [examples](https://github.com/paritytech/ink/tree/master/examples) found in this repo. 

Idea: 
Create a new branch that will have the Gitpod configuration file which will help create the coding environment for all of the contract examples. 

Question: 
Can we extract these examples into a dedicated repo? The reason is that we'll be able to have an an env. for each example. which makes things a lot cleaner.

**Comment by cmichi** [comment]
>Question:
>Can we extract these examples into a dedicated repo? 

We had this discussion a number of times with the conclusion that it's best to have them in the same repo as the ink! source code. Some of the advantages are that we immediately see if the tests for examples break when some core code is changed and that it's ensured that the examples are always in sync with the latest ink! version.

Maybe git submodules in your repo (or something along those lines) could work?

**Comment by Robbepop** [comment]
Closed since be abandoned the Gitpod based ink! playground.
