### ISSUE TITLE
token transfer failed while calling it at the second times.

### ISSUE THREAD

**Issue by bwhour** [paritytech/ink#799]
we had deployed two polkadot asset tokens just like erc20. 
the repo link is here https://github.com/Coinversation/coinpro/tree/test_trans/contracts/pat_standard . the two tokens we just called them XXX, YYY. and we aslo approve the test contract enough allowence to transfer.

the test contract is here https://github.com/Coinversation/coinpro/tree/test_trans/contracts/test .
when we called the api via the ui [https://polkadot.js.org/apps/#/contracts](url). we can see the first time transfer is successful. but the second time is failure. 

Not sure why this happened ?    anyone can give some help ?

the second time failure picture is here.

![图片](https://user-images.githubusercontent.com/8485901/119799766-fa9d6b00-bf0e-11eb-9cd4-3eff71b747e2.png)

some other info :
    "hash": "0x1202fed234dc7afec85bdd6d1a843333f8fb9016d3bd3d012d8211609cf4caf4",
    "language": "ink! 3.0.0-rc3",
    "compiler": "rustc 1.53.0-nightly"
cargo-contract version :
    cargo-contract 0.12.0-unknown-x86_64-macos

**Comment by cmichi** [comment]
@bwhour The error code `17` on your screenshot refers to this one: https://github.com/paritytech/substrate/blob/master/frame/contracts/src/lib.rs#L556 (index 17 in the `enum`) ‒ `CodeNotFound`.

Could it maybe be that the contract was evicted because of it running out of funds to pay the storage rent? See [here](https://substrate.dev/substrate-contracts-workshop/#/0/troubleshooting?id=contract-state-rent) for more info.

The easiest way to test this would be to increase the contract endowment and see if the second call then works.

You can also verify that it's an issue with the contract running out of funds to pay rent and thus being evicted by deploying the contract via https://polkadot.js.org/apps/#/contracts. This UI will show you a rent projection of how long the contract will probably survive with its current funding:
![117951030-0d5f4f80-b314-11eb-9432-8f66c594a30f](https://user-images.githubusercontent.com/241530/119813831-09bdf200-beea-11eb-8e60-5220f142c04c.png)

Was this the issue?

**Comment by bwhour** [comment]
> @bwhour Could it maybe be that the contract was evicted because of it running out of funds to pay the storage rent? See [here](https://substrate.dev/substrate-contracts-workshop/#/0/troubleshooting?id=contract-state-rent) for more info.
> 
> The easiest way to test this would be to increase the contract endowment and see if the second call then works.
> 
> You can also verify that it's an issue with the contract running out of funds to pay rent and thus being evicted by deploying the contract via https://polkadot.js.org/apps/#/contracts. This UI will show you a rent projection of how long the contract will probably survive with its current funding:
> 
> ![117951030-0d5f4f80-b314-11eb-9432-8f66c594a30f](https://user-images.githubusercontent.com/241530/119813831-09bdf200-beea-11eb-8e60-5220f142c04c.png)
> 
> Was this the issue?
> 
> Also: The output you posted was changed in more recent Substrate versions, so you could try using a more recent Substrate? Are you using `canvas-node`?

Hi, i am afraid it's not the reason. 

i have gave enough endowment, and also transfered 1million erc20 deployed token to the 
contract account. it still failed.   

i deployed them on jupiter and plasm dusty chain. they both failed.

**Comment by cmichi** [comment]
There is an assertion [here](https://github.com/Coinversation/coinpro/blob/test_trans/contracts/test/lib.rs#L84), which fails under [this condition](https://github.com/Coinversation/coinpro/blob/test_trans/contracts/pat_standard/lib.rs#L262-L264):
```
let allowance = self.allowance(from, caller);
if allowance < value {
    return Err(IError::InsufficientAllowance);
}
```
 Have you checked if it's that ‒ i.e. that the allowance is not set high enough?

**Comment by bwhour** [comment]
> There is an assertion [here](https://github.com/Coinversation/coinpro/blob/test_trans/contracts/test/lib.rs#L84), which fails under [this condition](https://github.com/Coinversation/coinpro/blob/test_trans/contracts/pat_standard/lib.rs#L262-L264):
> 
> ```rust
> let allowance = self.allowance(from, caller);
> if allowance < value {
>     return Err(IError::InsufficientAllowance);
> }
> ```
> 
> Have you checked if it's that ‒ i.e. that the allowance is not set high enough?

Hello, yes. i have print the log. it's not here. it finished transfer and print the log in function transfer_from_to as following.

![image](https://user-images.githubusercontent.com/8485901/120167416-4bbf9e80-c230-11eb-96fc-8fbd66c322c4.png)

but after printing  emit_event log, the **DispatchError** error ejected， the outer log i added didnot print out.

I am not sure whether it is caused by the condition that contract calls contract and the stack seems confused.
And i have met this situation many times. 
Some transfer api  will be ok when i encapsuled this api into a single function in the contract.

that's very weird.

**Comment by cmichi** [comment]
Is it possible for you to test the contract with the latest https://github.com/paritytech/canvas-node?

```
cargo install canvas-node --git https://github.com/paritytech/canvas-node.git --force --locked
```

Then we can be sure that the strange behavior also appears with recent versions of Substrate.

**Comment by xgreenx** [comment]
The second transfer sends a token from THIS contract to the caller. Are you sure that you set the allowance for this contract(So you need allowance from THIS to THIS=) So better to use simple transfer here instead of transfer_from to avoid strange errors)

**Comment by bwhour** [comment]
> The second transfer sends a token from THIS contract to the caller. Are you sure that you set the allowance for this contract(So you need allowance from THIS to THIS=) So better to use simple transfer here instead of transfer_from to avoid strange errors)

yes， actually i use the token.transfer api in the origin code. 
it threw out the error log when it's going to quit the transfer_from_to.

**Comment by bwhour** [comment]
> Is it possible for you to test the contract with the latest https://github.com/paritytech/canvas-node?
> 
> ```
> cargo install canvas-node --git https://github.com/paritytech/canvas-node.git --force --locked
> ```
> 
> Then we can be sure that the strange behavior also appears with recent versions of Substrate.

thx, i will try when i am free.
