### ISSUE TITLE
Events cannot have same name as a function

### ISSUE THREAD

**Issue by ascjones** [paritytech/ink#80]
While [converting](https://github.com/paritytech/ink/commit/9b2dab47912782336ed3736165bc3f9949ac268e) the ERC 20 contract to the new event syntax I got the following error:

```
error[E0255]: the name `Transfer` is defined multiple times
```

It collides with a `struct Transfer` which is generated for the `pub(external) fn transfer`.

**Comment by Robbepop** [comment]
Good catch!

I am going to improve the general codegen so that items generated through it are better encapsulated. This should also fix this issue since this is basically just an unfortunate naming collission.

**Comment by Robbepop** [comment]
Fixed by https://github.com/paritytech/ink/commit/b1bd2235aea7e833dcae3b90299ed44377826ad1.
