### ISSUE TITLE
`seal_gas_left` should be `Weight`(u64), not `T::Balance` (u128)

### ISSUE THREAD

**Issue by atenjin** [paritytech/ink#801]
**seal_gas_left should be `Weight`(u64), not `T::Balance` (u128)**

**Describe the bug**
In ink!, code is:

https://github.com/paritytech/ink/blob/master/crates/env/src/api.rs#L93-L100

the `gas_left` return `T::Balance`. But the default Balance is u128.

But in substrate pallet-contracts

https://github.com/paritytech/substrate/blob/master/frame/contracts/src/wasm/runtime.rs#L1070

the `ctx.ext.gas_meter().gas_left()` will return `Weight`, it's `u64`.

Thus if call seal_gas_left in ink!, must meet decode error.

**Comment by Robbepop** [comment]
Good find!
Since `Weight` is not customizable in the contracts pallet we should change the return type to plain `u64`.

**Comment by HCastano** [comment]
@atenjin feel free to open a PR for this!

**Comment by cmichi** [comment]
Closed via https://github.com/paritytech/ink/pull/797.
