### ISSUE TITLE
`RentFraction` not a member of trait `Environment`

### ISSUE THREAD

**Issue by garrettmaring** [paritytech/ink#802]
**Questions**

I'm getting an error when compiling the `rand-extension` example.

https://github.com/paritytech/ink/blob/master/examples/rand-extension/lib.rs

**FAQ**

- Are you using the nightly Rust channel to compile your smart contract?

> Yes

- Are you using an up-to-date `cargo-contract`? Check via `cargo contract --version`

> cargo-contract 0.12.0-unknown-x86_64-macos

- Are you using an up-to-date ink! version in your smart contract?

> 3.0.0-rc3

**Describe the bug**

This fails to compile

```
type RentFraction = <ink_env::DefaultEnvironment as Environment>::RentFraction;
```

**Expected behavior**

`ink_env` exports `RentFraction`

**Screenshots**

![Screen Shot 2021-06-03 at 3 38 34 PM](https://user-images.githubusercontent.com/8270120/120720925-c5020000-c481-11eb-90c8-22f05f71398f.png)

**Comment by HCastano** [comment]
@garrettmaring I just tried building the example (`cargo +nightly contract build --manifest-path examples/rand-extension/Cargo.toml`) with:
- Ink commit e1486563d9cf3a0ab3154686a989cd88aca579d1
- `cargo-contract 0.12.1-443d343-x86_64-linux-gnu`
- `rustc 1.54.0-nightly (0a8629bff 2021-06-11)`

and it built fine.

I'm gonna close this, but feel free to re-open if you run into issues again.
