### ISSUE TITLE
Is there a way to check if an AccountId is a contract?

### ISSUE THREAD

**Issue by bakasura980** [paritytech/ink#804]
I need to check if behind an AccountId there is an uploaded code. Is there a way to do that?

**Comment by athei** [comment]
Right now there is no API to get this information. We could add something like `seal_caller_is_contract`.

**Comment by bakasura980** [comment]
@Robbepop , let's say I need to ensure a given account Id is a contract to perform some operations and expect some results. Unfortunately, this is all the information I can share right now.
I thought for having a method on account id like get_code_hash() and if  get_code_hash() != 0 it is a contract

**Comment by xgreenx** [comment]
If you want to perform some operation you need to call some method. So it means that you can try to call that method directly and if you get Error::NotCallable it will mean that callee doesn't support this method.
Here is an [example](https://github.com/Supercolony-net/openbrush-contracts/blob/main/contracts/token/erc721/impls.rs#L271) of how you can use it.

**Comment by Robbepop** [comment]
@athei could something like this be implemented as chain extension eventually?

**Comment by athei** [comment]
> @athei could something like this be implemented as chain extension eventually?

Sure. But I think this functionality is of general interest and not chain specific. We just have to see what would be a good API. I would favour something like `seal_caller_is_origin`.  I am not sure if this really helps the issue startet. It seems that they want to fetch the `code_hash` of an arbitrary contract. Not sure why, though.

**Comment by HCastano** [comment]
> It seems that they want to fetch the code_hash of an arbitrary contract. Not sure why, though.

It's because having a non-zero `code_hash` would be indicative of being a contract. There's a similar trick in Solidity in which you check if an address has `code_size > 0`, and if it does it means it's a smart contract

**Comment by athei** [comment]
> > It seems that they want to fetch the code_hash of an arbitrary contract. Not sure why, though.
> 
> It's because having a non-zero `code_hash` would be indicative of being a contract. There's a similar trick in Solidity in which you check if an address has `code_size > 0`, and if it does it means it's a smart contract

Is is it important to be able to query the `code_hash` of an arbitrary address or would something like `caller_is_origin()` already suffice?

**Comment by bakasura980** [comment]
@HCastano is rights, I don't really need the code_hash itself, it was just an idea of how to handle the check. So basically I need in general a function like is_contract(accoundId) as the account could be provided as an argument to a function as well. Having that I believe it would be really easy after that to check caller_is_origin as well

**Comment by athei** [comment]
So the following API should be able to solve all your issues?

```rust
enum Status {
    NoContract,
    Tombstone,
    Alive,
}

fn is_contract(account_id: AccountId) -> Status;
fn caller_is_origin() -> bool;
```

Technically, `caller_is_origin` might not be required as `is_contract(self.caller())` could be used for that. However, `caller_is_origin` can be implemented without any storage lookup and therefore uses much less gas.

**Comment by Robbepop** [comment]
> ```rust
> enum Status {
>     NoContract,
>     Tombstone,
>     Alive,
> }
> ```

How about returning `Option<Status>` for when an `AccountId` does not exist as instance, yet?

**Comment by athei** [comment]
What do you mean with "user instance"? Do you mean whether there is an entry in the balances module? That would be a fourth case and not the same as `Status::NoContract`. It would require accessing a second storage item.

**Comment by Robbepop** [comment]
> What do you mean with "user instance"? Do you mean whether there is an entry in the balances module? That would be a fourth case and not the same as `Status::NoContract`. It would require accessing a second storage item. I don't think this is a useful check. No knowledge is gained from the fact that there is an entry in balances for it.

Yes that fourth state is exactly what I mean and i would model it as `Option<Status>` since that perfectly describes the absence of an account. Why do you think that this knowledge is of no use to anyone?

**Comment by athei** [comment]
>  Why do you think that this knowledge is of no use to anyone?

I genuinely don't know why anyone would be interested in that in this context. If something is no contract that it does not matter whether it currently hold some balance or not. Holding balance does not even proof that someone possessed the private keys at some point.   I would rather see another function like `seal_balance_of` if someone is interested in the current balance of an arbitrary account.

**Comment by bakasura980** [comment]
> So the following API should be able to solve all your issues?
> 
> ```rust
> enum Status {
>     NoContract,
>     Tombstone,
>     Alive,
> }
> 
> fn is_contract(account_id: AccountId) -> Status;
> fn caller_is_origin() -> bool;
> ```
> 
> Technically, `caller_is_origin` might not be required as `is_contract(self.caller())` could be used for that. However, `caller_is_origin` can be implemented without any storage lookup and therefore uses much less gas.

That would be perfect, Thanks a lot

**Comment by xgreenx** [comment]
Another topic but related to that. Will be cool to have a function that will allow checking that some contract supports some set of selectors. Solidity has analog [Erc165](https://eips.ethereum.org/EIPS/eip-165), but it requires the contract to implement an additional method and worry about initialization. 

Maybe `Alive` enum can contain the list of selectors of supported methods. Or maybe we can add another function that allow passing an array of selectors and if some contract by `AccountId` supports all selectors from the array, it will return true?

**Comment by Robbepop** [comment]
> Another topic but related to that. Will be cool to have a function that will allow checking that some contract supports some set of selectors. Solidity has analog Erc165, but it requires the contract to implement an additional method and worry about initialization.

This cannot be easily done by the contracts pallet alone and I think a better solution is to have an (already planned) hash added to the custom section of a Wasm smart contract that clearly associates a metadata to the Wasm blob. Then third party tools can simply check if a metadata and a Wasm blob are associated (by checking if the hash is equal to the hash over the metadata representation) and thereby know which set of selectors is supported by the contract.

**Comment by athei** [comment]
> This cannot be easily done by the contracts pallet alone and I think a better solution is to have an (already planned) hash added to the custom section of a Wasm smart contract that clearly associates a metadata to the Wasm blob. Then third party tools can simply check if a metadata and a Wasm blob are associated (by checking if the hash is equal to the hash over the metadata representation) and thereby know which set of selectors is supported by the contract.

Please note that even with this functionality you need to trust the contract that it is actually contains the code you think it does. It can embed arbitrary metadata. To **verify** a contract one would either need some kind of decompilation or use reproduceable compilation and compare code hashes.

**Comment by Robbepop** [comment]
> > This cannot be easily done by the contracts pallet alone and I think a better solution is to have an (already planned) hash added to the custom section of a Wasm smart contract that clearly associates a metadata to the Wasm blob. Then third party tools can simply check if a metadata and a Wasm blob are associated (by checking if the hash is equal to the hash over the metadata representation) and thereby know which set of selectors is supported by the contract.
> 
> Please note that even with this functionality you need to trust the contract that it is actually contains the code you think it does. It can embed arbitrary metadata hashes. To **verify** a contract one would either need some kind of decompilation or use reproduceable compilation and compare code hashes.
> 
> That said, I can imagine some service that does exactly this. You upload your contract sources and it verifies using conditional compilation that everything matches and then give you a green checkmark and a link to the source code.

Given this custom hash and a metadata it should be simple to verify (via RPC calls) if the associated metadata is correct at least given the parts of the Wasm blob it properly represents by simply calling into all functions and looking for the returned error. Ideally we differentiate between parameter decoding errors and selector mismatch errors. Also in the future there will be wildcard selectors: Contracts that accept any selector.

**Comment by xgreenx** [comment]
> > > This cannot be easily done by the contracts pallet alone and I think a better solution is to have an (already planned) hash added to the custom section of a Wasm smart contract that clearly associates a metadata to the Wasm blob. Then third party tools can simply check if a metadata and a Wasm blob are associated (by checking if the hash is equal to the hash over the metadata representation) and thereby know which set of selectors is supported by the contract.
> > 
> > 
> > Please note that even with this functionality you need to trust the contract that it is actually contains the code you think it does. It can embed arbitrary metadata hashes. To **verify** a contract one would either need some kind of decompilation or use reproduceable compilation and compare code hashes.
> > That said, I can imagine some service that does exactly this. You upload your contract sources and it verifies using conditional compilation that everything matches and then give you a green checkmark and a link to the source code.
> 
> Given this custom hash and a metadata it should be simple to verify (via RPC calls) if the associated metadata is correct at least given the parts of the Wasm blob it properly represents by simply calling into all functions and looking for the returned error. Ideally we differentiate between parameter decoding errors and selector mismatch errors. Also in the future there will be wildcard selectors: Contracts that accept any selector.

I agree with you. My concern was about another moment. If someone wants to check inside of the code of contract that another contract(we have some `AccountId` and `is_contract` returned `Alive`) supports some set of methods. 

It is a similar case of usage like for `is_contract`.

```rust
enum Status {
    NoContract,
    Tombstone,
    Alive,
}

// For example method get_contract_info returns ContractInfo which contains Status and also has additional useful methods. 
let contract_info: Option<ContractInfo> = self.env().get_contract_info(some_address);
if contract_info.is_some() && contract_info.is_alive() && contract_info.supports(vec![ TRANSFER_SELECTOR, MINT_SELECTOR, BALANCE_OF_SELECTOR ]) {
  ...
}
```

**Comment by xgreenx** [comment]
> I agree with you. My concern was about another moment. If someone wants to check inside of the code of contract that another contract(we have some `AccountId` and `is_contract` returned `Alive`) supports some set of methods.
> 
> It is a similar case of usage like for `is_contract`.
> 
> ```rust
> enum Status {
>     NoContract,
>     Tombstone,
>     Alive,
> }
> 
> // For example method get_contract_info returns ContractInfo which contains Status and also has additional useful methods. 
> let contract_info: Option<ContractInfo> = self.env().get_contract_info(some_address);
> if contract_info.is_some() && contract_info.is_alive() && contract_info.supports(vec![ TRANSFER_SELECTOR, MINT_SELECTOR, BALANCE_OF_SELECTOR ]) {
>   ...
> }
> ```

So, what do you think about the API described above? Or you think that it is not needed and better to implement [Erc165](https://eips.ethereum.org/EIPS/eip-165) for each contract?

**Comment by cmichi** [comment]
>So, what do you think about the API described above?

In terms of checking if an `AccountId` is a contract I think it is fine. With this we have specified everything now for the original issue. For the `contracts` we have created this issue: https://github.com/paritytech/substrate/issues/9064, as soon as the `contracts` pallet one is done we can implement it in ink!.

>Or you think that it is not needed and better to implement Erc165 for each contract?

I think a standard alike to Erc165 would be best for finding out if a contract supports certain functionality. Maybe as another PSP?

**Comment by xgreenx** [comment]
> I think a standard alike to Erc165 would be best for finding out if a contract supports certain functionality. Maybe as another PSP?

Yes, Erc165 can be implemented like a PSP. My idea was that a contract pallet can answer a question that some contract has a method with `selector`. Because incase of Erc165 and the `supportsInterface` method you need to load the whole storage and call only one method. Be more optimal to do that on the contract pallet level(if it can be implemented easily).
