### ISSUE TITLE
[Bug] contract-transfer does not compile

### ISSUE THREAD

**Issue by VadneyK** [paritytech/ink#805]
**Describe the bug**
I copied the code from [here](https://github.com/paritytech/ink/tree/master/examples/contract-transfer) but the code doesn't compile with the given error. I made a contract based on this code here and got around this error by using rc2 instead of rc3 but I [am getting this issue](https://github.com/PlasmNetwork/dusty-faucet/issues/2) so I figured i should be using rc3 instead but I am getting the same error there as well.

the standard `cargo contract new <name>` and `cargo +nightly contract build` combo works on the fresh repo so I tried getting rid of the non-std [features] in std = [...] and removint the git links but that didn't work as well...

**Expected behavior**
contract should build

**Screenshots**
# Error [in my repo:](https://github.com/PlasmNetwork/dusty-faucet/tree/main/contract)
![Screen Shot 2021-06-07 at 5 51 22 PM](https://user-images.githubusercontent.com/57117207/121105449-fac42300-c7b8-11eb-9c8d-3215ba890e35.png)

# Error in the[ cloned & modified contract-transfer example:](https://github.com/VadneyK/contract-trasfer-practice)
![Screen Shot 2021-06-07 at 5 59 12 PM](https://user-images.githubusercontent.com/57117207/121106044-12e87200-c7ba-11eb-94ef-7a121d64d986.png)

**Additional context**
MacOs BigSur 11.2.3 M1 chip
![Screen Shot 2021-06-07 at 5 52 49 PM](https://user-images.githubusercontent.com/57117207/121105560-2e06b200-c7b9-11eb-9ebe-1c3ec95365fc.png)

**Comment by xgreenx** [comment]
To fix the compilation problem you need to remove `cargo-contract = "^0.9.1"` from your [cargo file](https://github.com/VadneyK/contract-trasfer-practice/blob/main/cargo.toml#L8).

Linking with `cargo-contract` crate case you to link with [parity-scale-codec](https://github.com/paritytech/cargo-contract/blob/master/Cargo.toml#L31) which defines the `oom` with the same naming.

**Comment by VadneyK** [comment]
did the trick, thanks!

**Comment by VadneyK** [comment]
Actually a seperate bug but I'm trying to [compile this cloned repo as mentioned above](https://github.com/VadneyK/contract-trasfer-practice) but am getting this issue:
kentarovadney@Kentaros-MacBook-Air contract-play % cargo +nightly contract build
 [1/5] Building cargo project
    Updating git repository `https://github.com/paritytech/ink`
    Updating crates.io index
   Compiling contract_transfer v3.0.0-rc3 (/private/var/folders/r_/74rntmcx51zgp8k_z7xncyq00000gn/T/cargo-contract_k17Tt7)
error: expected item, found `/`
 --> /Users/kentarovadney/Desktop/code/contract-play/lib.rs:1:1
  |
1 | / Copyright 2018-2021 Parity Technologies (UK) Ltd.
  | ^ expected item

error: aborting due to previous error

error: could not compile `contract_transfer`

To learn more, run the command again with --verbose.
ERROR: `"/Users/kentarovadney/.rustup/toolchains/nightly-aarch64-apple-darwin/bin/cargo" "build" "--target=wasm32-unknown-unknown" "-Zbuild-std" "-Zbuild-std-features=panic_immediate_abort" "--no-default-features" "--release" "--target-dir=/Users/kentarovadney/Desktop/code/contract-play/target/ink"` failed with exit code: Some(101)

**Comment by xgreenx** [comment]
You missed "/"=)

**Comment by VadneyK** [comment]
thanks!
