### ISSUE TITLE
Add additional methods to wrapper around the account of contract

### ISSUE THREAD

**Issue by xgreenx** [paritytech/ink#808]
When we import some contract with the feature `ink-as-dependency`, ink! generates wrapper around the `AccountId`.
This wrapper allows us to call methods of some contract in a native manner.
```rust
let token: Erc20 = FromAccountId::from_account_id(_address_of_contract);
token.transfer(_to, _amount);
```

It will do something the next inside of this transfer:
```rust
build_call::<DefaultEnvironment>()
  .callee(_address_of_contract)
  .exec_input(
      // Selector of Erc20::transfer
      ExecutionInput::new(Selector::new([0x7a, 0x22, 0x87, 0x43]))
          .push_arg(_to)
          .push_arg(_amount),
  )
  .returns::<ReturnType<Result<(), Erc20Error>>>()
  .fire().expect("Bla bla bla")
```

The problem is that it calls `expect` after a `fire` call. So if the execution of the function failed, we can't handle the error of execution by ourselves.

Maybe we can add additional function during codegen like `token.transfer_raw(_to, _amount);`.
To have the ability to write code like:
```rust
match token.transfer_raw(_to, _amount)
{
    Ok(result) => match result {
        Ok(_) => Ok(()),
        _ => Err(Erc20Error::CallFailed),
    },
    Err(e) => match e {
        Env_error::NotCallable => Ok(()),
        _ => Err(Erc20Error::CallFailed),
    },
}
```
For example, it can be used [here](https://github.com/Supercolony-net/openbrush-contracts/blob/main/contracts/token/erc721/impls.rs#L253).

**Comment by Robbepop** [comment]
You can already do this today. Just use the so-called long-hand calling notation by `call()` and `call_mut()`:
```rust
match token.call_mut().transfer(_to, _amount).gas_limit(foo).transferred_value(bar).fire() {
    Ok(_) => ...,
    Err(_) => ...
}
```

**Comment by xgreenx** [comment]
Oh yea, thanks!=)

But I still have the problem(it because I defined [stub](https://github.com/Supercolony-net/openbrush-contracts/blob/main/contracts/token/erc721/stub.rs#L8) implementation of the contract in the crate with [another contract](https://github.com/Supercolony-net/openbrush-contracts/blob/main/contracts/token/erc721/impls.rs#L320)).

It generates two metadata so it causes a compilation error. Because during generation of metadata you don't use `CrossCallingConfig` [here](https://github.com/paritytech/ink/blob/master/crates/lang/codegen/src/generator/metadata.rs#L39)

So this doesn't allow to use attribute `compile_as_dependency` fully=) Do you plan to fix that?

**Comment by xgreenx** [comment]
The initial issue is resolved, so we can close it=) If you want you can create another issue for the problem described above

**Comment by Robbepop** [comment]
> It generates two metadata so it causes a compilation error. Because during generation of metadata you don't use CrossCallingConfig here

Sorry for the confusion there but ink! currently is intended to place each contract into its own crate.

**Comment by xgreenx** [comment]
I understand that ink! doesn't support two contracts inside of one crate=) But `compile_as_dependency` can allow us to do that. It easy can be fixed but his change:
https://github.com/Supercolony-net/ink/commit/e861950f40c9252e4b4f8a7b776105188ddf3be9
