### ISSUE TITLE
Is it possible to get the account_id of an instantiated contract?

### ISSUE THREAD

**Issue by KaiserKarel** [paritytech/ink#819]
```
let token = Erc20::new( supply)
            .endowment(100)
            .code_hash(self.erc20_hash)
            .salt_bytes(todo!("generate salt"))
            .instantiate()?;

let account_id: AccountId = token.get_account_id();
```

Is there some API that can accomplish this?

**Comment by HCastano** [comment]
I don't think this is possible as the moment.

The only thing I can think of right now is to add a method like `Erc20::address_of()` which itself calls [`ink_env::account_id()`](https://paritytech.github.io/ink/ink_env/fn.account_id.html).

@Robbepop Maybe there's also some way to implement `Info<AccountId> for <things with #[ink(storage)]>`?

**Comment by KaiserKarel** [comment]
>The only thing I can think of right now is to add a method like Erc20::address_of() which itself calls ink_env::account_id().

Yeah that is what I'm currently using; in this case I control the contract code.

**Comment by cmichi** [comment]
I agree that an API function for this would be nice. In the meantime this is a workaround, which doesn't require adding a special method to the contract.
```
let adder_params = Adder::new(accumulator.clone())
    .endowment(total_balance / 4)
    .code_hash(adder_code_hash)
    .salt_bytes(salt)
    .params();

let id = Self::env().instantiate_contract(&adder_params)
    .expect("failed at instantiating the `Adder` contract");

let adder: Adder = ink_env::call::FromAccountId::from_account_id(id);
```

**Comment by Robbepop** [comment]
There should be `ink_lang::IntoAccountId` implemented by contracts for exactly this purpose.

**Comment by KaiserKarel** [comment]
So in this case the [ToAccountId](https://paritytech.github.io/ink/ink_lang/trait.ToAccountId.html) is what one should use. :)
