### ISSUE TITLE
`debug_println!` doesn't work in `#[ink(constructor)]`

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink#821]
To reproduce one can use the `contract-transfer` example. Just modify the constructor in this way:
```rust
/// Creates a new instance of this contract.
#[ink(constructor)]
pub fn new() -> Self {
    ink_env::debug_println!("constructor!");
    Self {}
}
```

Start the `canvas-node` this way:
```
$ canvas --tmp --dev -lerror,runtime::contracts=debug
```

If you deploy and interact with the contract the `debug_println!`'s in the `#[ink(message)]`'s will show up on the console, but not the one from the constructor.

Note that https://github.com/paritytech/ink/pull/820 needs to be merged to reproduce this.

**Comment by Robbepop** [comment]
Might it be possible that this is not an ink! related issue but resides in the contracts pallet instead? I cannot see a reason atm why constructors and messages would behave different in ink!. Do you?

**Comment by cmichi** [comment]
Nope, it was also my intuition that an investigation would probably lead to the `contracts` pallet. I haven't looked deeper though.

Does @athei maybe have an immediate hunch if this could be caused by the `contracts` pallet?

**Comment by athei** [comment]
AFAIK no UI dry-runs the constructor as RPC before deploying. Remember: Debugging is not enabled during on-chain execution. Only during RPC calls.

**Comment by cmichi** [comment]
Ok, but in principle it's possible to do a dry-run of the constructor, right? Then I would create follow-ups for the UI's.

**Comment by athei** [comment]
Yes. This functionality was added somewhat recently.

**Comment by cmichi** [comment]
Things left to do for this ticket:

- [ ] Test if this bug still appears when instantiating a contract with `cargo contract instantiate`.
- [ ] Test if it still happens with `polkadot-js`.
- [ ] Test if it still happens with `contracts-ui`.

If it happens in none of those we can close this issue.

**Comment by SkymanOne** [comment]
Closing as the bug no longer appears on ink! 4.1
