### ISSUE TITLE
Towards the ink_api entrance crate

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#825]
## Description

Introduce an `ink` or `ink_api` crate that acts as a central unified re-export layer on top of all ink! related crates.

## Motivation

Currently, if you want to write an ink! smart contract your contract has to depend on several different ink! related crates such as `ink_env`, `ink_storage`, `ink_primitives`, `ink_prelude` as well as some other non-ink! crates such as `parity_scale_codec` and `scale-info` crates.
On top of that there is the need to properly forward crate features such as `std`, `ink-debug` and `ink-as-dependency` to the respective crates.
This isn't such a big deal usually because `cargo-contract` takes care of it mostly, however, it is yet another hurdle for new 
developers especially.

## Ideal Solution

The ideal is to only have to depend on a single ink related crate that manages all the details for all the contracts that depend on it.
We call this entry crate `ink_api` or sometimes even just `ink`.
This `ink_api` crate won't define anything by itself but merely acts as a layer that provides a unified way to access all the different parts of ink! via re-exports or re-definitions of functions, types, macros etc.

## Problems

So why didn't we implement this already?
The problem starts with procedural macros which are pervasive to the idea of ink!.
There currently exists no sane way to properly deal with build system related information from within a proc. macro.
For our use case it will be important to support both: using ink! crates as it happens nowadays as well as the proposed new solution via the centralized and unifying `ink` or `ink_api` crate layer.

The problem is that within a proc. macro it is hard (or impossible) to properly extract the information how exactly a project has been or will be built and therefore the proc. macro is kind of unable to properly align its generated code with respect to this. So depending on if the user actually uses this new `ink_api` crate or not the proc. macro is required to generate code a little differently and this is not possible without introducing impure hacks to take measures into the proc. macro itself.

## Outlook

The Rust team constantly improves the situation and API surrounding proc. macros. There are ideas to make inspection of build processes and other information possible to inspect from within a proc. macro in the future and we could build upon this when it is ready to be used.

Another possible way forward is to simply implement the hacks that the previous section talks about. We refer to them as "hacks" since they are not a clean solution that covers the entire space but only acts on a limited set of common patterns that users are expected to go for when designing their contract architecture. Besides that this will make ink! proc. macros impure with respect to the fact that they will have the need to inspect the file system during compilation of an ink! smart contract which is nothing you want to happen usually, also with respect to file caching and build artifacts etc.

**Comment by HCastano** [comment]
Related https://github.com/paritytech/ink/issues/328.

**Comment by atenjin** [comment]
related #778
we help to export seal_extenstion to outside in ink_api

**Comment by cmichi** [comment]
This would btw. be a perfect application to utilize our https://crates.io/crates/ink namespace. Then a smart contract would just have to depend on the `ink` crate.

**Comment by Robbepop** [comment]
> This would btw. be a perfect application to utilize our https://crates.io/crates/ink namespace. Then a smart contract would just have to depend on the `ink` crate.

This was the original plan of doing `use ink_lang as ink;` in the examples all the time.
