### ISSUE TITLE
Cannot add mut to message arguments

### ISSUE THREAD

**Issue by JayPavlina** [paritytech/ink#826]
```
#[ink(message)]
pub fn do_something(&mut self, mut token: Erc20) {}
```
This causes the following error:
```
error: expected expression, found keyword `mut`
```

**Comment by HCastano** [comment]
Hi @JayPavlina, what you're presenting isn't valid Rust (see this [Rust playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9e6bd529c234c22f6c19a8b98c546e5e)).

What you're likely looking for is `&mut token`.

**Comment by xgreenx** [comment]
He described a valid rust:)
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=251ff6bcbaa41aabc68a35b9818b1bd3)

**Comment by HCastano** [comment]
> He described a valid rust:)
> [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=251ff6bcbaa41aabc68a35b9818b1bd3)

I misread it, good catch 😅

**Comment by Robbepop** [comment]
In the past we were overly restrictive with respect to checks like the one mentioned in this issue.
I currently see no reason why we should not allow `mut` specifier for message or constructor parameters as long as there are good examples.
@JayPavlina can you provide us with a good real-world usage example to where the above `mut` specifier would help you in particular? Thank you!

**Comment by JayPavlina** [comment]
```
#[ink(message)]
pub fn transfer_erc20(&mut self, to: AccountId, value: Balance, mut token: Erc20) {
  token.transfer(self.env().caller(), to, value);
}
```
Without the `mut`, you have to do something like this before (if it implements Copy, I can't remember if it does)
```
let mut token = token;
```
