### ISSUE TITLE
Add new default bump allocator for heap memory allocations

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#827]
Currently we are using `wee_alloc` (https://crates.io/crates/wee_alloc) for allocating heap memory in smart contracts.
This allocator was specifically designed for WebAssembly usage and smart contracts and features relatively low footprint.
However, its footprint is still significant and blows up the complexity and Wasm file size of non-trivial smart contracts measurably.

On Ethereum it is not uncommon to use the most trivial heap memory allocator: The bump allocator which just increases a counter.
The downside of a bump allocator is that it usually cannot deallocate memory and therefore if an executable does lots of allocations during execution the memory will be drained or wasted.
However, since smart contracts execute in s short lived manner this should never really become a problem at all.

Therefore we want to add a bump allocator and set it as the new default allocator for ink! smart contracts. This also includes research into how this unfolds for Wasm binary size for non-trivial smart contracts. We not only expect the bump allocator to take significantly less space but we also expect that common routines such as `alloc` and `dealloc` will take a lot less space. So there are many potential gains for more complex contracts in this regard.

## ToDo

- Implement a very simply bump allocator in the `ink_allocator` crate.
    - Even due to the hint below it might make sense to check how much the `bumpalo` bump allocator already helps.
- Make it possible to switch between `wee_alloc` and the new `bump_alloc` via a crate feature for example.
- Set the new bump allocator as the new default allocator.
- Use our default contracts (or others) to research into how the different allocator unfolds into Wasm binary size gains (or not).

## Hints

I have looked at the `bumpalo` crate on crates.io. While it looks fine, is decently implemented and has respected authors it is not a perfect match for our use case unfortunately since it is design for non embedded use cases mostly where you might have the need to allocate much more than 4GB.
For our use case we could go with a much simpler and more light weight design that resembles some allocator that operates on some fixed size stack space, e.g. another 16kB buffer. Contract executions should rarely have the need to allocate a lot of heap memory during their short execution times.

**Comment by HCastano** [comment]
From what I can tell we aren't able to use `bumpalo`. This is because it has a pretty fundamental assumption baked in, which is that it [allocates and deallocates memory using an already exiting global allocator](https://github.com/fitzgen/bumpalo/issues/100#issuecomment-792972404). This would leave us in the same situation since we're using `wee_alloc` as the global allocator.

As the crate author mentions in that comment though, we could fork `bumpalo` and make those `alloc/dealloc` calls manually.

**Comment by cmichi** [comment]
I'm closing the issue since from what I can tell @HCastano's PR checked all ToDo's.
