### ISSUE TITLE
Derive macro for a default SpreadLayout

### ISSUE THREAD

**Issue by mmagician** [paritytech/ink#829]
When adding a custom struct to smart contract storage, as shown in the [docs](https://github.com/paritytech/ink-docs/pull/21), I found that implementing all the methods for SpreadLayout (default) is tedious. 

Would it make sense to have a derive macro which does automatically generates these methods? I've already built an example of what this would look like [in this implementation of DefaultSpreadLayout](https://github.com/mmagician/merkle_tree/blob/master/custom_derive/src/lib.rs#L19). It's functional for simple structs already, though it'd obviously need more testing with more complex ones, and perhaps with recursion too. 

Let me know if I can contribute to the codebase with this feature. Potentially something similar could be done for PackedLayout.

**Comment by Robbepop** [comment]
How is this derive macro different from the one we already are providing for the `SpreadLayout` trait?

**Comment by mmagician** [comment]
Never mind me 🤦🏼
