### ISSUE TITLE
storage::HashMap hash function performance

### ISSUE THREAD

**Issue by maciejhirsz** [paritytech/ink#83]
Currently the HashMap probing is using a `u32` quadratic index probing, with seed generated from the first 4 bytes of `keccak256` of the key. I'm wondering if there is much of a point in using keccak if all we use is 4 bytes, and if something like SipHash might be a better fit (in terms of DDOS resistance and overall performance / gas costs).

@burdges could you give us some input here?

**Comment by burdges** [comment]
As a rule, siphash with a random secret seed should suffice for DoS protection in the sense that it protects the seed from the adversary's probes.  If the seed is not random or not secret, then no hash function can protect you from DoS anyways.

**Comment by Robbepop** [comment]
So in order to make this work properly we need to get a proper implementation of https://github.com/paritytech/ink/issues/57 done ... if that is possible for smart contracts.

**Comment by burdges** [comment]
We cannot use randomness or secrets inside execute block itself.  Instead, we need native call outs for anything using randomness or secrets, so run your hash table in native.  In fact, your hash table's WASM interface should disallow easy iteration, although you could iterate in sorted order.  There is a suggestion to support WASM code that responsible uses randomness and secrets via some module interface, maybe even SPREEs.

**Comment by burdges** [comment]
It's plausible some crate like OrderMap or IndexMap might provide an interface almost safe for execute block already, but not sure if you can get randomness tricks approved for just one safe crate like that.

I'd think higher level languages like Go assume randomness too, so not sure how they behave when writing an execute block function.

**Comment by burdges** [comment]
If the hashmap is build and consumed quickly, then one might explore using Fiat-Shamir here, but sounds dubious.

**Comment by maciejhirsz** [comment]
If using SipHash over Keccak isn't really that much faster, then the whole point is really moot anyway. I guess it would suffice to dynamically link to keccak in the contracts module whenever linking becomes possible (or just moving the whole HashMap internals there), and setting the gas metering there instead.

**Comment by burdges** [comment]
I'd think the Keccak variant you currently use is slower than SipHash on most existing hardware.  

Gas metering?  If this runs on ethereum then maybe SipHash does not exist native there?

**Comment by maciejhirsz** [comment]
No, this is running on a Wasm interpreter in Substrate contracts module. Neither SipHash nor Keccak is native in this environment (yet, afaik).

**Comment by DemiMarie-parity** [comment]
Can we switch from `HashMap` to `BTreeMap`?  `BTreeMap` has no DoS risks and no need for randomness.

**Comment by Robbepop** [comment]
> Can we switch from `HashMap` to `BTreeMap`? `BTreeMap` has no DoS risks and no need for randomness.

This is already planned but has not yet been implemented. You are free to do so. :)

**Comment by burdges** [comment]
I always love probabilistic data structures, but yeah Ink doing them well sounds like crossing the WASM boundary, which sounds like too much dev time for too little gain.. 

We'll worry more about probabilistic data structures for actual parachain code, so if some nice solution appears there then maybe we could support it here too.

**Comment by Robbepop** [comment]
I close this with the conclusion that we should not further follow this path since `storage::HashMap` is going to be deprecated and replaced eventually by `storage::BTreeMap`.
