### ISSUE TITLE
Implement binary_search for ink_storage::Vec

### ISSUE THREAD

**Issue by KaiserKarel** [paritytech/ink#834]
It seems that ink_storage::Vec is missing some useful methods, such as binary search. Is such a feature wanted?

**Comment by HCastano** [comment]
Having `binary_search` seems reasonable to me. Feel free to open a PR

**Comment by Robbepop** [comment]
I would love to see that!

**Comment by KaiserKarel** [comment]
I think that for the search we will need to access storage for the comparison, but no more than that.

**Comment by HCastano** [comment]
Closed by #836.
