### ISSUE TITLE
unresolved import `other_contract`

### ISSUE THREAD

**Issue by vidarthedev** [paritytech/ink#839]
Trying to compile the example of two contracts calling itself. 

I get the error:

error[E0432]: unresolved import `other_contract`

other_contract Cargo.toml 

other_contract = { path = "../other_contract", default-features = false, features = ["ink-as-dependency"] }

the contract that calls it has: 

use other_contract::OtherContract;

The contracts are exactly the same as those in the example: https://paritytech.github.io/ink-docs/basics/cross-contract-calling

I have issues with another set of contract with exactly the same error. 

Can anyone help me what I am missing here? Maybe something changes or I miss some configuration? 

I build first other_contract and the contract that calls it using: cargo +nightly contract build

Any help will be appreciated.

**Comment by cmichi** [comment]
@vidarthedev Sorry for the late reply. It's hard to tell what exactly the failure in your case is, could you maybe post a minimal example of the `Cargo.toml` + `lib.rs` of both contracts?

Alternatively what you could do is look at our [`delegator`](https://github.com/paritytech/ink/tree/master/examples/delegator) example, it does cross-contract calling and you could take these files as templates:
* For the parent contract: `delegator/Cargo.toml` and `delegator/lib.rs`
* For the "other contract": `adder/Cargo.toml` and `adder/lib.rs`

Maybe you can find the difference to how you included your `other_contract` in that example?

**Comment by tk-o** [comment]
@vidarthedev I think I had the same issue while trying to include one contract into another contract.

Please check the `Cargo.toml` file of the contract you'd like to provide to another one. It must have `rlib` setting provided in `lib.crate-type` section:
```toml
crate-type = [
    # Used for normal contract Wasm blobs.
    "cdylib",
    # Used for ABI generation. Required for contracts to be included in other contracts.
    "rlib",
]
```

**Comment by vidarthedev** [comment]
@tk-o Thank you. I was missing "rlib". 

However, I still get strange error:

5 | use other_contract::OtherContract;
  |     ^^^^^^^^^^^^^^^^-------------
  |     |               |
  |     |               help: a similar name exists in the module: `other_contract`
  |     no `OtherContract` in the root

Any ideas?

**Comment by cmichi** [comment]
@vidarthedev Did you manage to fix the issue? If not, could you post a minimal example reproducing your issue?

**Comment by vidarthedev** [comment]
I did not. Adding "rlib" helped but I get that error:

5 | use other_contract::OtherContract;
| ^^^^^^^^^^^^^^^^-------------
| | |
| | help: a similar name exists in the module: other_contract
| no OtherContract in the root

Please see below the simple example. Maybe something wrong with the setup. I've added:
crate-type = [
    # Used for normal contract Wasm blobs.
    "cdylib",
    # Used for ABI generation. Required for contracts to be included in other contracts.
    "rlib",
]

I build it using: cargo +nightly contract build

First contract:
--------------------
#![cfg_attr(not(feature = "std"), no_std)]
use ink_lang as ink;

use ink_storage::Lazy;
use other_contract::OtherContract as OtherContract;

//--snip--
#[ink(storage)]
struct MyContract {
    /// The other contract.
    other_contract: Lazy<OtherContract>,
}

impl MyContract {
    /// Instantiate `MyContract with the given
    /// sub-contract codes and some initial value.
    #[ink(constructor)]
    pub fn new(
        other_contract_code_hash: Hash,
    ) -> Self {
        let other_contract = OtherContract::new(1337)
            .endowment(total_balance / 4)
            .code_hash(other_contract_code_hash)
            .instantiate()
            .expect("failed at instantiating the `OtherContract` contract");
        Self {
            other_contract
        }
    }

    /// Calls the other contract.
    #[ink(message)]
    pub fn call_other_contract(&self) -> i32 {
        self.other_contract.get_value()
    }
}
//--snip--
--------------------

Second contract:
--------------------
#![cfg_attr(not(feature = "std"), no_std)]
use ink_lang as ink;

#[ink::contract]
pub mod other_contract {
    /// Storage for the other contract.
    #[ink(storage)]
    pub struct OtherContract {
        value: i32,
    }

    impl OtherContract {
        /// Initializes the contract.
        #[ink(constructor)]
        pub fn new(value: i32) -> Self {
            Self { value }
        }

        /// Returns the current state.
        #[ink(message)]
        pub fn get_value(&self) -> i32 {
            self.value
        }
    }
}
--------------------

**Comment by cmichi** [comment]
@vidarthedev I think what you are likely missing is a
```
pub use self::other_contract::OtherContract;
```
in your `other_contract.rs`. For `delegator` we have this here in the sub-contracts: https://github.com/paritytech/ink/blob/master/examples/delegator/adder/lib.rs#L17.

Does it work then?

PS: You can use [Markdown syntax](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to format code blocks on GitHub.

**Comment by vidarthedev** [comment]
Wow, it works. Thank you so much !!!

**Comment by cmichi** [comment]
:+1:
