### ISSUE TITLE
Implement `ext_now`

### ISSUE THREAD

**Issue by lsaether** [paritytech/ink#84]
Add the ability to get the current timestamp from `lang`.

Not sure if there's any current blockers to this as I'm still understanding the code base.

**Comment by Robbepop** [comment]
To implement SRML contract API like `ext_now` you need to touch `core/src/env/api.rs`, `core/src/env/test-env.rs`, `core/src/env/srml/srml_only/impls.rs` and `model/src/exec_env.rs`.
