### ISSUE TITLE
Improve `expect` messages for decoding failure

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink#840]
Follow-up for https://github.com/paritytech/ink/pull/797.

Copy/Pasted from @Robbepop's comment there:

> Seeing code like
> 
> ```rust
> ink_env::account_id::<T>().expect("couldn't decode contract account id")
> ```
> 
> all over the place I come to believe we need a follow-up PR that replaces those `expect` calls with `unwrap_or_else(|error| panic!("couldn't decode contract account id: {}", error))` that provides more information about the underlying error.

**Comment by gangov** [comment]
is this still available?

**Comment by cmichi** [comment]
@gangov Yes, fell free to assign it to yourself 👍.

**Comment by gangov** [comment]
thanks, a couple of things to clear if that's okay:

1. I cannot assign the issue to myself
2. There are a dozen places in the code where we cannot use .unwrap_or_else because we're dealing with Option<T>. The error we have is the same all-over-the-place 
error[E0593]: closure is expected to take 0 arguments, but it takes 1 argument
What would be the best approach here?
3. Should we include the files in the examples directory and the ones for the tests?

**Comment by cmichi** [comment]
Sorry @gangov, the notification for your comment fell under the table.

1. Are you still interested in it? I'd assign it to you then.
2. You can ignore `Option`.
3. Tests no, examples directory yes.

**Comment by gangov** [comment]
hey @cmichi, no worries about the notification. Yes, I'd like to give it a try, please assign it to me. I'll ignore `Option` and tests, but then follow up on the rest as per the initial comment

**Comment by gangov** [comment]
hey, @cmichi I created the PR a couple of minutes ago, but I did it from a forked repo. Please let me know if that troubles you in some way to review, so I can adjust

**Comment by gangov** [comment]
hey again @cmichi this is the PR [https://github.com/paritytech/ink/pull/1456](https://github.com/paritytech/ink/pull/1456) 

There were some cases in which we had tests in the examples, so I didn't change those, please let me know if that needs an update, too

**Comment by gangov** [comment]
hey @cmichi the above mentioned PR has been merged, I guess we can close this one

**Comment by HCastano** [comment]
Closed by #1456
