### ISSUE TITLE
How contract receive the AccountId and amount when user or other contract transfer coin(not erc20 token). 

### ISSUE THREAD

**Issue by Quantiex-Lab** [paritytech/ink#865]
How contract receive the AccountId and amount when user or other contract transfer coin(not erc20 token) to this contract.

**Comment by KaiserKarel** [comment]
If they do a regular transfer, I do not think there is a way for the contract to inspect that transfer. However you can make methods payable to allow for extra transfers.

**Comment by HCastano** [comment]
Yeah, if you're transferring native tokens I don't think the smart contract has any insight into that. You can however, as part of the smart contract execution, check the current balance using [`ink_env::balance()`](https://paritytech.github.io/ink/ink_env/fn.balance.html).

I think what you're looking for, as KaiserKarel mentioned, are [`payable` messaages](https://paritytech.github.io/ink/ink_lang/attr.contract.html). Then you can inspect the sender `AccountId` and `Balance` like this:

```rust
#[ink(message, payable)]
pub fn fund(&self) {
  let caller = self.env().caller();
  let value = self.env().transferred_balance();
}
```

**Comment by Quantiex-Lab** [comment]
Payable can resolve my problem. Thank you very much!! @HCastano @KaiserKarel
