### ISSUE TITLE
Confused about the returned blockNumber value of `env().random()` 

### ISSUE THREAD

**Issue by yjhmelody** [paritytech/ink#868]
The returned value is always lower than the current latest block height.

**Comment by HCastano** [comment]
@yjhmelody can you provide us with more context/some code?

**Comment by yjhmelody** [comment]
```rs
        #[ink(message)]
        pub fn random(&self, arr: Vec<u8>) -> (Hash, BlockNumber) {
            return self.env().random(&arr);
        }
```

Just call it simply.

I use [Europa](https://github.com/patractlabs/europa) to execute these codes. I am confused about this return value

**Comment by HCastano** [comment]
I think it makes sense that the block number is always lower, since the randomness was "generated" at some earlier block. From the docs:

> ... block number since which it was determinable by chain observers

That being said, I'm not sure when a block is "determinable", but I suspect that's dictated by the contracts pallet. Pinging @athei who can probably give you a better answer than me.

**Comment by athei** [comment]
Works as intended. The contracts pallet only forwards the randomness provided by `pallet_contracts::Config::Randomness`. See the [`Randomness`](https://substrate.dev/rustdocs/latest/frame_support/traits/trait.Randomness.html) trait:

> NOTE: The returned seed should only be used to distinguish commitments made before the returned block number. If the block number is too early (i.e. commitments were made afterwards), then ensure no further commitments may be made and repeatedly call this on later blocks until the block number returned is later than the latest commitment.
