### ISSUE TITLE
seal_terminate do not support seal1

### ISSUE THREAD

**Issue by yjhmelody** [paritytech/ink#869]

**Comment by HCastano** [comment]
@yjhmelody can you provide us with more context/some code?

**Comment by yjhmelody** [comment]
I mean [seal0] seal_terminate is deprecated. Ink! should use [seal1]

**Comment by HCastano** [comment]
Gotcha. Yeah you're right. It doesn't look like there's anything stopping us from updating this (and a few others). I've opened #879, feel free to open a PR against that.
