### ISSUE TITLE
Add off-chain tests to all the examples

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/ink#88]
Seems that the Core examples are not up to date with the latest changes.

If possible, we should be checking that all the examples compile, and pass some tests during CI

**Comment by Robbepop** [comment]
I even thought about removing all non-`lang` examples as programming `lang` is what we want to advertise in the first place.

**Comment by shawntabrizi** [comment]
That sounds reasonable, but it also makes sense to have at least one contract which is written in each form. Maybe it can help with debugging. Maybe it can help with the transparency of what is happening between the layers.

**Comment by Robbepop** [comment]
What contract would you recommend?

**Comment by shawntabrizi** [comment]
Probably ERC20 if possible.

Would want it to include all the major parts of a contract:
- Storage Value
- Storage Map
- Events
- Message Functions
- Non-message Functions
- Deployment
- println
- (other?)

**Comment by xlc** [comment]
Having at least one contract for each layer is definitely very useful. It help me to see all the magic behind the macro and better understand how everything plays together.

**Comment by Robbepop** [comment]
I think this has been implemented quite recently. Closed.
