### ISSUE TITLE
Can I use frame_support::PalletId inside ink?

### ISSUE THREAD

**Issue by frankli-dev** [paritytech/ink#880]
**Questions**

Can I use frame_support::PalletId inside ink?

**Comment by tk-o** [comment]
Perhaps you need to take a look at https://paritytech.github.io/ink/ink_env/chain_extension/index.html

**Comment by cmichi** [comment]
@frankli-dev What are you trying to achieve by having the `PalletId` inside ink!? I agree with @tk-o, that you probably want to look into chain extensions. Here are two more possibly helpful resources:
* https://paritytech.github.io/ink-docs/macros-attributes/chain-extension ‒ extensive documentation
* https://github.com/paritytech/ink/tree/master/examples/rand-extension ‒ code xample

**Comment by frankli-dev** [comment]
> @frankli-dev What are you trying to achieve by having the `PalletId` inside ink!? I agree with @tk-o, that you probably want to look into chain extensions. Here are two more possibly helpful resources:
> 
> * https://paritytech.github.io/ink-docs/macros-attributes/chain-extension ‒ extensive documentation
> * https://github.com/paritytech/ink/tree/master/examples/rand-extension ‒ code xample

I would like to define like the following. If I use chain extension just to get the pallet id, does it cost much gas?
```
fn account_id(&self) -> AccountId {
    PalletId(*b"abcdefgh")
}
```

**Comment by frankli-dev** [comment]
Ah, I got it. I don't need to use PalletId inside ink directly. Figuring out with chain extension. Thanks
