### ISSUE TITLE
Contract delegator release error  ContractTrapped

### ISSUE THREAD

**Issue by qaibeibei** [paritytech/ink#881]
I ran into a problem when I released the contract,The latest version of 3.0rc4 is used.

Error  ContractTrapped

delegator version = ?

**Comment by cmichi** [comment]
@qaibeibei What are the steps you are taking to get this error? Are you using the latest versions of `canvas-node` and `cargo-contract`? You can update via:

```
cargo install canvas-node --git https://github.com/paritytech/canvas-node.git --tag v0.1.9 --force --locked
cargo install cargo-contract --vers ^0.13 --force --locked
```

**Comment by qaibeibei** [comment]
![image](https://user-images.githubusercontent.com/42369700/127460199-32f53abf-72f2-488e-af27-cb5f247bd219.png)
![image](https://user-images.githubusercontent.com/42369700/127460339-8e1368c1-f224-4732-8736-4d13abfe1a2f.png)

I use substrate monthly-2021-07 ， 
Start command  ./target/release/substrate --dev,  
contract version  cargo-contract 0.13.0-unknown-x86_64-linux-gnu

**Comment by HCastano** [comment]
@qaibeibei since you mention you're using a `monthly` tag that indicates that you're not using the `canvas-node`. Can you please follow Michi's advice and try to reproduce this using the latest `canvas-node`? 

The Substrate `master` branch moves fast, and being "just" a month behind can mean a lot of breaking changes.

**Comment by cmichi** [comment]
Could you also try with an endowment of 10000 please? I can't see how this would cause the trap, but we're using 10000 in our End-to-End tests.

**Comment by qaibeibei** [comment]
Thinks,  When donated to 10000,   it can be instantiated.
