### ISSUE TITLE
Encode and Decode is not implemented for `u8` - workaround needed

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#92]
For optimization reasons there is no `parity_codec::{Encode, Decode}` impl for `u8` since it would clash with the specialized impl of `Vec<u8>` with its general case `Vec<T>`.

Either specialization or [`optin_builtin_traits`](https://github.com/rust-lang/rust/issues/13231) feature would solve this issue.

We want to provide `u8` support for users of ink! well before that thus requiring a work arround.
One possible work arround could be to replace all instances of `u8` with a thin-wrapper type.
This, however, is intrusive and changes code semantics probably confusing users.
We could also simply introduce a `byte` type that has a similar interface to `u8` and does the trick.

**Comment by tomusdrw** [comment]
Why not use `i8` or `[u8; 1]`? The first only requires `as` and the latter is pretty much the same as the thin-wrapper type you mention.

**Comment by Robbepop** [comment]
That's another possibility.
The problem is that I really want to avoid manipulating user code in the macro as much as I can because this is always the first step into confusion for users.

**Comment by gavofyork** [comment]
replacing with `i8` would be minimally invasive and should be safe, no?

**Comment by Robbepop** [comment]
In my opinion this is definitely not a big issue since we are just talking about the use of a single `u8` which could always replaced by something like `[u8;1]`, `(u8,)` or technically `i8` as mentioned.

Instead of doing some magic conversions in the back I conclude that it might also be possible to just disallow `u8` as an interfacing type or we do these conversions hidden from the user. Within a proc macro we do not have access to type information so we would need to offload this conversion into some traits that would do the trick. One naive solution would be to wrap the `parity_codec::{Encode, Decode}` traits for this purpose or actually make use of the nightly features mentioned above to just fix the problems locally for smart contracts since they are using nightly Rust already anyway.

**Comment by Robbepop** [comment]
Fixed by depending on the newest `parity-codec` 4.1.
Also a newer PR for depending on the superseeding `parity-scale-codec` works as well.
