### ISSUE TITLE
Follow-up #665: Make ink! chain extensions use is_result_type! utility macro

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#952]
The https://github.com/paritytech/ink/pull/665 PR introduces some new `is_result_type!` utility macro to check at compile time whether some type is a `Result` using the Rust type system.
This means that we can get rid of the `returns_result: bool` ink! attribute of ink! chain extensions since it is now possible to infer this information via the proc. macro itself.

**Comment by HCastano** [comment]
We should have this in for ink! 4.0 (#1343). @SkymanOne or @lean-apple this might be something for one of you to take on
