### ISSUE TITLE
What is good documentation? (Discussion)

### ISSUE THREAD

**Issue by lsaether** [paritytech/ink#97]
This issue comes out conversations I've had with @shawntabrizi and @Robbepop regarding the documentation of `ink!`. 

## Why good documentation for  `ink!`

`ink!` right now is the only smart contract language targeting the SRML contract module. Projects like [Edgeware](https://edgewa.re) have signaled that they will use the SRML contract module for smart contracts on their own chain and therefore they will likely use also `ink!`. Since the contract module will be easily usable by any chain which builds on Substrate, I anticipate that there will be more (possibly a great deal more) chains (including multiple chains which will connect to Polkadot as parachains) that will also be using `ink!`. 

Smart contracts have many tradeoffs compared to building and maintaining a full chain (either sovereign chain with Substrate or parachain for Polkadot). These include 1) cheaper deployment costs, 2) quicker development time, 3) easier for less complex applications.  It could also be possible that developers of future decentralized applications will go through an iteration process of creating a prototype with smart contracts and later moving to full on chains. These developers will use `ink!`. 

## What is good documentation?

Right now, `ink!` has Shawn's awesome tutorial for workshops, the [Substrate contracts workshop]() that covers the basics, ERC20 tokens, and ERC721 tokens. There are also reference  docs which are generated from the code comments (afaik). However, there needs to be some approachable documentation which sits between these two.

```
Reference Docs ----------- Middle Documentation ------------ Workshops
```

If we compare some successful projects from outside the smart contract space we can take the Rust language as an example. Rust has reference docs for the [standard library](https://doc.rust-lang.org/std/index.html), [the book](https://doc.rust-lang.org/book/), and [the Rustlings course](https://github.com/rust-lang/rustlings/) among other things. 

Furthermore we can reference documentation of other popular smart contract languages such as [Solidity](https://solidity.readthedocs.io/en/v0.5.8/) and [Vyper](https://vyper.readthedocs.io/en/v0.1.0-beta.6/). 

## Discuss

So the idea of this issue is to start the discussion on the documentation for `ink!` and how to get it right so that its an enjoyable and powerful tool for developers to use.

**Comment by lsaether** [comment]
On my end I've been working on some examples and material based loosely on the [Vyper by example](https://vyper.readthedocs.io/en/v0.1.0-beta.6/vyper-by-example.html) section of the Vyper docs. I'm writing it in markdown and using [mdbook](https://vyper.readthedocs.io/en/v0.1.0-beta.6/vyper-by-example.html) as the static site generator. I can share the source soon (needs more work done).

**Comment by Robbepop** [comment]
I would really love something like `ink! by example` but I guess it currently is too early to develop such documentation because they grow out of experience using the language and the user base is currently not experienced enough to have developed their techniques for certain things. I would still love to see progress there.

Concerning something like an ink! book: I think this is really needed but right now ink! is too much under development so I fear that while writing the book we would have to rewrite the book constantly in order to keep pace with the project. On the other side we really try very hard not to break things in general. So might be worth a try if there is enough to say at this point.

Our dev docs are quite old already and could need some polish.
Shawns workshop is awesome and I hope we can extend it in the future to cover a great part of ink!.

**Comment by shawntabrizi** [comment]
@Robbepop you can get an "ink! by example" feel with something like "ink! recipes".

Less formal, but a collection of code snippets which are minimal and complete which do things.

Keeping these up to date with the latest code should not be so hard in this case since they each live on their own.

**Comment by Robbepop** [comment]
Can we close this then?

**Comment by lsaether** [comment]
Is the consensus to use Shawn's tutorial as main documentation for now?

**Comment by Robbepop** [comment]
Shawns tutorial covers everything there is (in an isolated and simplistic manner) and tries to be up-to-date.

**Comment by shawntabrizi** [comment]
I would like there exists 4 main docs:
* Less than 1 hour independent tutorial to deploy a contract
    * Goals to try and differentiate deployment from ethereum and to show that end to end things work
* Less than 1 hour independent tutorial to write flipper
    * Goals to try and explain any magic which happens in `cargo contract new` so that even from a template, users know what is going on
* In depth walkthrough, with no upper limit to length
    * Actually go into details about anything we want to teach them
* Recipes page as a quick cheat sheet for common patterns

Along with that a well managed FAQ

**Comment by Robbepop** [comment]
Closed because this is better kept at the actual docs repo at the Substrate developer hub.
