### ISSUE TITLE
Invalid ABI file — Error: Invalid JSON ABI structure supplied, expected a recent metadata version

### ISSUE THREAD

**Issue by pormeu** [paritytech/ink#976]
Hey guys, the repo for the beginner ink! workshop looks archived, so I'm trying to ask my question here.

For context, my development environment looks like the following (from dependencies in `Cargo.toml`):
```
ink_primitives = { version = "3.0.0-rc6", default-features = false }
ink_metadata = { version = "3.0.0-rc6", default-features = false, features = ["derive"], o    ptional = true }
ink_env = { version = "3.0.0-rc6", default-features = false }
ink_storage = { version = "3.0.0-rc6", default-features = false }
ink_lang = { version = "3.0.0-rc6", default-features = false }
scale = { package = "parity-scale-codec", version = "2.1", default-features = false, featu    res = ["derive"] }
scale-info = { version = "1.0.0", default-features = false, features = ["derive"], optiona    l = true }
```

Also, you can note that I use the following version with `cargo`, and `rust`:
```
cargo version: cargo 1.57.0-nightly (7fbbf4e8f 2021-10-19)
cargo contract version: cargo-contract 0.15.0-unknown-x86_64-macos
compiler: rustc 1.58.0-nightly
```

With this setup, I have followed each and every step of the tutorial for building and deploying the `flipper` contract on a local development node. All libraries are installed and the build completes successfully. Yet, when uploading the `flipper.contract` file on the Canvas UI, I get the following error:

```
Invalid ABI file — Error: Invalid JSON ABI structure supplied, expected a recent metadata version
```

I would however expect to run it smoothly. Do you know what I am doing wrong here? 

Thanks :)

**Comment by cmichi** [comment]
I'm closing this issue since https://github.com/paritytech/canvas-ui/pull/114 was merged and the Canvas UI should be working again. Feel free to reopen if you have a different view.
