### ISSUE TITLE
rc6 breaks anything that depends on generated metadata.json

### ISSUE THREAD

**Issue by garrettmaring** [paritytech/ink#980]
**Questions**

How can I pin an rc version in my Cargo.toml? I'd like to stay up-to-date with RCs but they often break dependencies. For example, the new rc6 release changes the generated metadata.json for ink contracts causing https://github.com/polkascan/py-substrate-interface/blob/f8b37fee552c7d12562d3d1f0f030ad3d3c88fc5/substrateinterface/contracts.py to fail.

**Describe the bug**

It seems like various changes. Now things like `types` are nested underneath a `V1`. I changed that but still see an issue with `metadataVersion`.

**Expected behavior**

RC candidates, which automatically update since they cannot be pinned, should be compatible. If not, 3.0.0 -> 4.0.0 would be a more useful semver pattern to consume as a developer such that we aren't blindsided with breaking changes.

**Screenshots**
![Screen Shot 2021-10-23 at 1 03 52 PM](https://user-images.githubusercontent.com/8270120/138569935-d4f006b8-6e9f-4788-89e9-c85a39983024.png)
![Screen Shot 2021-10-23 at 1 04 01 PM](https://user-images.githubusercontent.com/8270120/138569938-47de1421-69df-44e9-8ce4-816723259f4e.png)
![Screen Shot 2021-10-23 at 1 05 34 PM](https://user-images.githubusercontent.com/8270120/138569984-0375fe2f-dfa0-4bb6-aac6-c962485ee5d1.png)

**Additional context**
https://github.com/polkascan/py-substrate-interface/issues/147

I've added `=3.0.0-rc5` now to my Cargo.toml to rebuild with a prior version. However, now I'm seeing an unimplemented `Display` trait for `DispatchError`
![Screen Shot 2021-10-23 at 5 29 41 PM](https://user-images.githubusercontent.com/8270120/138575344-52720a21-cee2-4a9f-844a-efe9d33d0c9c.png)

**Comment by garrettmaring** [comment]
I've added `=3.0.0-rc5` now to my Cargo.toml to rebuild with a prior version. However, now I'm seeing an unimplemented `Display` trait for `DispatchError`

![Screen Shot 2021-10-23 at 5 29 20 PM](https://user-images.githubusercontent.com/8270120/138575339-87a75d41-3466-43ab-84b9-26459c2665f0.png)

**Comment by cmichi** [comment]
@garrettmaring My understanding is that your problems have been solved and I'll close the issue therefore. Feel free to reopen otherwise.
