### ISSUE TITLE
New `trait_definition` fails if to use two traits.

### ISSUE THREAD

**Issue by xgreenx** [paritytech/ink#982]
A new `trait_definition` [generates](https://github.com/paritytech/ink/blob/e8d4739649293a458c3958bec802d2d750067d98/crates/lang/codegen/src/generator/as_dependency/call_builder.rs#L100) `CallBuilder`. But the builder is not unique, so the usage of two traits will generate two same builders. It causes an error during compilation.

What do you think to create one general `CallBuilder` on the ink! level and apply implementation of each trait to this general builder? It allows generating implementation for `CallBuilder` during trait definition instead of implementation block(this feature allows us to support default implementation in traits in the future).

**Comment by forgetso** [comment]
Hi, just chiming in to say this bug fix is necessary for us to use `rc8` `ink!` with OpenBrush so that we can more easily manage our rapidly growing contract. It's reached 2000 lines, including tests, and it would be nice to break it up into smaller chunks!

**Comment by HCastano** [comment]
@forgetso Yep, gonna look into it this week. Can you post a link to your contract, I'm curious to see it

**Comment by forgetso** [comment]
Great! Here is the contract - https://github.com/prosopo-io/protocol/blob/master/contracts/lib.rs. Critique welcome!

**Comment by cmichi** [comment]
Closed with https://github.com/paritytech/ink/pull/1141.
