### ISSUE TITLE
How to upgrade ink! version?

### ISSUE THREAD

**Issue by frankli-dev** [paritytech/ink#986]
What is the stable version of Ink?
I need to implement unit testing of ink contracts. Which version is appropriate for this?
To upgrade to that ink version (from 3.0.0-rc3), what changes needed?
- substrate version
- cargo-contract version
- nightly version
- ink version

**Comment by HCastano** [comment]
@frankli-dev I'm gonna close this, let us know if your issue isn't resolved.

**Comment by frankli-dev** [comment]
Yeah, it is resolved

Thank you
