### ISSUE TITLE
Implement utility function for spread allocate contract initialization

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#992]
Currently when using the new `SpreadAllocate` trait to initialize an ink! smart contract a lot of things have to be orchestrated by the ink! smart contract author themselves.

One of the things is the verbose smart contract allocation and transferal to the initialization function as shown below extracted from the adjusted ERC-20 example from this PR: https://github.com/paritytech/ink/pull/979
```rust
#[ink(constructor)]
pub fn new(initial_supply: Balance) -> Self {
    let root_key = Key::from([0x00; 32]);
    let mut key_ptr = KeyPtr::from(root_key);
    let mut instance = Self::allocate_spread(&mut key_ptr);
    instance.new_init(initial_supply);
    instance
}
```
Instead of enforcing this verbose and labor intense task onto the smart contract author we should provide some simple utility functions and traits in the `ink_lang` crate:
```rust
pub trait ContractRootKey {
    const ROOT_KEY: Key;
}

impl ContractRootKey for Erc20 {
    const ROOT_KEY: Key = Key::new([0x00; 32]);
}

#[inline]
fn initialize_using<C, F>(f: F) -> C
where
    C: ContractRootKey + SpreadAllocate,
    F: FnOnce(&mut C),
{
    let mut key_ptr = KeyPtr::from(<C as ContractRootKey>::ROOT_KEY);
    let mut instance = <C as SpreadAllocate>::allocate_spread(&mut key_ptr);
    f(&mut instance);
    instance
}
```
The `ContractRootKey` can be used by other utility functions already defined in the `ink_lang` crate and it represents the contract's storage root key which usually is `[0x00; 32]`. This trait makes sense since all of these routines need to use the same underlying root key in order to work together. Also it allows us to later make it possible for smart contract authors to adjust it using ink!.

The `initialize_using` is the simple initialization routine that simply allocates a smart contract instance and forwards it to an initialization function `f` and afterwards returns the instance back to the caller.
We might want to add another `try_initialize_using` for fallible ink! constructors, however, they have not yet been implemented.

When implemented properly the above example ERC-20 contract constructor may look like the following code:
```rust
impl Erc20 {
    /// Creates a new ERC-20 contract with the specified initial supply.
    #[ink(constructor)]
    pub fn new(initial_supply: Balance) -> Self {
        initialize_using(|contract| Self::new_init(contract, initial_supply))
    }

    /// Default initializes the ERC-20 contract with the specified initial supply.
    fn new_init(&mut self, initial_supply: Balance) {
        let caller = Self::env().caller();
        self.balances.insert(&caller, &initial_supply);
        Lazy::set(&mut self.total_supply, initial_supply);
        Self::env().emit_event(Transfer {
            from: None,
            to: Some(caller),
            value: initial_supply,
        });
    }
}
```

**Comment by HCastano** [comment]
Close by #995.
