### ISSUE TITLE
Add derive macro for SpreadAllocate trait

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#993]
https://github.com/paritytech/ink/pull/978 has added a new `SpreadAllocate` trait which is useful for default initializing ink! contracts onto some storage region which was not really possible before.

This trait is very much needed for non-caching storage facilities and collections such as the `Mapping` type first introduced in https://github.com/paritytech/ink/pull/946 and refined in https://github.com/paritytech/ink/pull/979.

However, currently we are missing a simple way for users to derive the trait.
This issue is about implementing a derive macro for the new `SpreadAllocate` trait.
The `where` clause should make sure that it is only implemented on types where all fields are `SpreadAllocate`, too.

For this the `ink_storage_derive` crate has to be adjusted.

**Comment by HCastano** [comment]
Closed by #995.
